### ISSUE TITLE
Hide Index::list_segment_metas() hidden

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1004]
Right now the behavior is confusing as it list the living "SegmentMeta".
If no IndexReader is open, this list will NOT contain the searchable segment metas.

**Comment by evanxg852000** [comment]
In regard to this and the need to merge and query segment meta, I propose we create an `IndexMetaHelper` to just deal with the raw `json` files and keep segmentMeta as is with a change of the interface Index::live_segment_metas(). 
One can always read the meta.json but I think having an `IndexMetaHelper` helps us maintain an api and validation that is in sync with Tantivy metadata schema.
```
IndexMetaHelper::from_file(Path)
IndexMetaHelper::from_buffer(&[u8])
IndexMetaHelper::is_valid() ->  bool
indexMetatHelper::segements()
IndexMetaHelper::schema()
IndexMetatHelper::list_files() very usefull to avoid dir traversal
IndexMetaHelper::merge(Vec<IndexMetaHelper>) -> IndexMetaHelper
IndexMetatHelper::to_json() -> Vec<u8>
IndexMetatHelper::to_file(Path) outputs the json to file

```
Please let me know if this is not related I can create another issue and discuss.

**Comment by fulmicoton** [comment]
This is pretty orthogonal to this ticket, but this is not a bad idea at all... 

If we go that path, I would remove some of the methods in your list though. 
For instance, validity should be checked upon creation to make sure don't have any instance with a weird invalid state.

I'd remove from_file and to_file and force the user to user buffers. This is an advanced API and we don't need to care much this level of usability. Performance wise it does not matter.

list_files(), schema(), segments() are good not bad. 

Let's discuss this today before going with this plan.
