### ISSUE TITLE
Expose a method to merge several `Segment` into one new directory

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1005]
Merging several segment, belonging possibly from different indices into one new directory is necessary in quickwit.

Rather than manipulate meta.json externally, making the process brittle to any change in its format, we should expose method to merge segments in tantivy.

(Disclaimer: We need to check that the schema are equal, which might not be easy)

A possible prototype could be something like that.

```rust
fn merge_segment(indices: &[Index], output_directory: Box<dyn Directory>) -> tantivy::Result<()> {
   //...
}
```

This function will create an IndexMerger with all of the searchable segment from the indices.
Create a new index in output_directory.
Create a new segmetn from the new index.
Serialize index merger into that new segment.
Update the meta.json of the new index.

The first few steps are present in the merge function in segment_updater.rs.
This  last part should be a little bit tricky:
We can probably extract a `pub(crate)` function from `SegmentUpdater::save_metas()`.
A possible prototype could be:

```
fn save_metas(index: &Index, segment_metas: &[SegmentMetas]) -> tantivy::Result<()> {
   // ...
}
```

**Comment by evanxg852000** [comment]
Question: when we serialise the index merger into the new segment, does the merger merges the segment to a new file while the other segments are still dangling around?
https://github.com/tantivy-search/tantivy/blob/main/src/indexer/segment_updater.rs#L133
referring to this comment, what I understand is this merges all segments into on and therefore the IndexMeta will have only one segment at the end which is the one produced by `let segment_meta = index.new_segment_meta(merged_segment_id, num_docs);`
Maybe this new_segment is just added to the other segments?
