### ISSUE TITLE
Sort DocId by key

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1014]
Today, DocId are only allocated using an incremental per-segment id.

In some case, carefully choosing the ordering of ids can improve performance.
For instance, 
- sorting by some a priori quality metric used in scoring (e.g. PageRank) make it possible to stop searching before havingn scored all of the matching results. (Note: that the result then obtained is not necessarily correct)
- sorting by a location field or a tenant id in a multitenant context, can also considerably improve the performance.
- sorting by a sort field like timestamps make it trivial to sort by this field.

It should be possible in tantivy to specify a field in the meta.json file as the ordering key.

- [x] specify and implement how this parameter should be set in the API. 
- [x] implement and test  the logic it for new segment
- [ ] implement and test it for merge
- [ ] understand lifecycle of temp data

# Open questions

- Do we require that field to be a fast field?
A: Generally no, but the first implementation will only support fast fields.

**Comment by PSeitz** [comment]
The current `Schema` de/serializes to an array, which is not ideal for such global options.

It probably would be better to have something for global options
```json
{
    "options": {
        "sort_documents": {"field": "timestamp", "order": "Desc"}
    },
    "fields": []
}
```

Would also be possible to include in the options of the field, but this would mean sorting is always bound to a field, also sorting by multiple fields would be more complicated

```json
 [{
        "name": "count",
        "type": "u64",
        "options": {
                "indexed": false,
                "fast": "single",
                "stored": true,
                "sort_documents": "Asc"
        }
  }
]
```
