### ISSUE TITLE
Important and easy merge speed optimization when sorting by a field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1038]
There is one common special case that we should optimize for...

We should try and detect whether the segments are actually trivially stackable.
For instance, when sorting by timestamp, it is very common to merge segments that are covering
disjoint interval of time.

In that case, the logic stacking the docids is correct.

**Comment by PSeitz** [comment]
For that to be effective, the round robin like distribution of documents would need to be changed.

Currently the min max values are overlapping for almost sorted data, like this.

Segments
|<---value range----->|
_|<---value range----->|
__|<---value range----->|
___|<---value range----->|


If we read the initial data from multiple cursor positions an pass them to some segment creators this could be avoided
|-----json data reader block 1-----||-----json data reader block 2-----||-----json data reader block 3-----|
|---------segment creator 1---------||---------segment creator 2---------||---------segment creator 3---------|

**Comment by fulmicoton** [comment]
It happens already today if you index in single thread, or in quickwit if you run a second generation merge.
