### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lnicola** [quickwit-oss/tantivy#104]
- [x] [Flushing a directory fails on Windows](https://github.com/tantivy-search/tantivy/pull/103)
 - [x] [`simdcompression` feature doesn't build on Windows](https://github.com/tantivy-search/tantivy/pull/105)
 - [x] [Test suite expects deleting a memory-mapped file to succeed](https://github.com/tantivy-search/tantivy/pull/106)
 - [x] [AppVeyor CI](https://github.com/tantivy-search/tantivy/pull/108)
 - [x] ~~Investigate `lz4` build failure with `-gnu`~~ invalid, had to do a clean build to recompile the native libs
 - [x] Edit README.md, add the appveyor badge

**Comment by fulmicoton** [comment]
Thanks for the very clear ticket.

**Comment by fulmicoton** [comment]
@vchugreev Windows is not officially supported on windows just yet, but it should be working. We will change the README message when we have proper continuous integration.

**Comment by KodrAus** [comment]
@fulmicoton I'll set up AppVeyor over the next few days, and then this should be rounded off!

**Comment by fulmicoton** [comment]
Closing. 
I'll edit README with the release.

Good job guys!
