### ISSUE TITLE
Add a iter_document method in `SegmentReader`

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1048]
We could have an iter document method that simply feeds into the `StoreReader` with the `DeleteBitSet` properly set.

**Comment by PSeitz** [comment]
There is a lifetime issue, `StoreReader` is created on demand by `SegmentReader`, so the iterator has no object to bind its lifetime to. I could add a `into_inter` method, but then the iter logic needs to be duplicated or changed. Alternatively `StoreReader` could live inside `SegmentReader`.

**Comment by fulmicoton** [comment]
Ah right. Let's forget it for the moment then...
