### ISSUE TITLE
Relax contraints on field name

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/tantivy#1087]
**Is your feature request related to a problem? Please describe.**
Currently tantivy is very strict on field name as shown by the regex used to validate field names:
`r#"^[_a-zA-Z][_\-a-zA-Z0-9]*$"#`

This can be annoying for users to have this restriction. Major database accepts utf8 string and Lucene too.

**Describe the solution you'd like**
 I suggest to allow any string as field names. 

I don't expect this to be an issue to tantivy as the real identifier for a field is the id.

**Comment by fulmicoton** [comment]
I think lucene allows anything, can you confirm?

**Comment by fmassot** [comment]
Yes there is no restriction as you see [here](https://stackoverflow.com/questions/17839053/how-to-perform-a-lucene-query-containing-special-character-using-queryparser).

It raises some issues when you need to parse, lucene resolves that with using backslash to escape special characters using in the query syntax:
```
Escaping Special Characters
Lucene supports escaping special characters that are part of the query syntax. The current list special characters are

+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ /

To escape these character use the \ before the character. For example to search for (1+1):2 use the query:

\(1\+1\)\:2
```
 
To keep things simple, I will only authorize the "." as this is the only need for Quickwit for now and update the query parser so that it supports that.

This sounds like a dumb request but don't want to distract tantivy task force on that now.

**Comment by fmassot** [comment]
Ok tantivy has to support unicode ;)

https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#unicode-identifiers

<img width="810" alt="Capture d’écran 2021-06-17 à 21 34 14" src="https://user-images.githubusercontent.com/653704/122461590-d3890500-cfb3-11eb-98a5-51622f1802b4.png">
