### ISSUE TITLE
Reproducable benchmark against Lucene

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#11]
It would be great to see track periodically our performance and ideally compare it to Lucene.

Maybe using the same dataset as 
`http://home.apache.org/~mikemccand/lucenebench/`

**Comment by celaus** [comment]
hmm this should probably have its own repository, and comparison will be a bit skewed unless someone has the same hardware available ;)

**Comment by fulmicoton** [comment]
Yes. Whatever benchmark we use we need to run both lucene and tantivy on the same hardware.
I put the lucene benchmark link here as an inspiration and for the dataset, but we need to run the benchmark on both lucene and tantivy on the same hardware.

I agree that this should be in another repository.

**Comment by fulmicoton** [comment]
We'll rely on@jason-wolfe's https://github.com/jason-wolfe/search-index-benchmark-game
