### ISSUE TITLE
uses bytes::Bytes instead of OwnedBytes 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1104]
Confirm that bytes::Bytes does everything required by OwnedBytes:
- slicing is cheap
- accessing data is cheap
- cloning is cheap
- 'static

and then replace OwnedBytes by bytes::Bytes if it makes sense.

**Comment by fulmicoton** [comment]
Ah it might not be possible due to the need to accept MmapDirectory... :-/

**Comment by PSeitz** [comment]
I think we would still need something that owns the bytes after reading data from a file slice?

**Comment by fulmicoton** [comment]
bytes::Bytes does that... but it does not make it possible to work with an external type in charge of holding the data...
We need this for the mmap directory.
