### ISSUE TITLE
tantivy::directory::file_watcher - Meta file "test_index/wikipedia/meta.json" was modified

### ISSUE THREAD

**Issue by carmel** [quickwit-oss/tantivy#1131]
> tantivy::directory::file_watcher - Meta file "test_index/wikipedia/meta.json" was modified

#### Every time I execute a search request, I get this prompt. I would like to ask the following questions:

1. #### is it necessary for the modification of the `meta.json` file ? 
2. #### will it be very performance intensive ?
3. #### is it thread safe?

**Comment by fulmicoton** [comment]
It is only supposed to happen if there was a modification in the index.
You can disable the mechanism when you build the IndexReader.
