### ISSUE TITLE
panicked at 'byte index 149 is not a char boundary; it is inside '”' 

### ISSUE THREAD

**Issue by carmel** [quickwit-oss/tantivy#1134]
**Describe the bug**
- What did you do?

Search for Chinese characters.

- What happened?

> thread '<unnamed>' panicked at 'byte index 149 is not a char boundary; it is inside '”' (bytes 147..150) of `圣经是什么？我们知道，“圣经”这辞的意思是“那书。”但这书是什么？圣经本身说，“圣经都是神的呼出。”（提后三16）圣经乃是神的呼出。牠不单是神的话，或神的思想，更是神的呼出`[...]', /Users/carmel/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/85d23e8/src/snippet/mod.rs:166:30

**Which version of tantivy are you using?**

`tantivy = { git = "https://github.com/tantivy-search/tantivy", rev = "85d23e8" }`

In addition, the use of third-party Chinese word splitting - [tantivy-jieba](https://crates.io/crates/tantivy-jieba).

**To Reproduce**

```rust
...
let g = SnippetGenerator::create(&searcher, &*query, *f).map_err(|e| {
      Error::new(ErrorKind::Other, format!("SnippetGenerator create: {}", e))
  }).unwrap();

println!("{:?}", g.snippet_from_doc(&doc).to_html());
```
Search for "圣经", then it was panicked.

**Comment by carmel** [comment]
I'm not sure if it can be solved using the following code, I tried and failed. Please help!:
```rust
fn fragment_boundary_cut(s: &str, mut range: Range<usize>) -> &str {
      if s.len() <= range.end {
          range.end = s.len();
      } else {
          while !s.is_char_boundary(range.end) {
              range.end += 1;
          }
      }

      if range.start != 0 {
          while !s.is_char_boundary(range.start) {
              range.start -= 1;
          }
      }

      &s[range]
  }
```
The result is as follows：

`<b>圣</b>圣经是什<b>么</b>么？我们知道，<b>“</b>“圣经<b>经</b>”这辞的意<b>思</b>思是“那书。”但这书是什么？圣经本身说<b>，</b>，“圣经都是神<b>神的</b>的呼出。”`

**Comment by PSeitz** [comment]
Hi, 

can you test with the latest commit on master? 4a320fd1ff02f5e2df80d309b844b0bb6bcf3503

There was a bug-fix regarding incorrect positions after merge, which are used in the snippets. It only appears on sorted indices.

**Comment by carmel** [comment]
As you can see, it's the same error.

![image](https://user-images.githubusercontent.com/36031579/128252454-d6b7d458-72d4-447e-8060-42ffed6344f3.png)

Does the index need to be re-add?

**Comment by PSeitz** [comment]
Yes, the index needs to be recreated

**Comment by carmel** [comment]
@PSeitz The whole process was redone, including delete, create, add, then search, and the error was still reported.

**Comment by PSeitz** [comment]
Can you provide a complete example to reproduce?

**Comment by carmel** [comment]
Okay, I'll open the project up later.

**Comment by carmel** [comment]
Hi @PSeitz , my project address is [tantivy-server](https://github.com/carmel/tantivy-server), you can directly execute the test function [test_search_index](https://github.com/carmel/tantivy-server/blob/main/src/index/search.rs)  to reproduce.

**Comment by PSeitz** [comment]
It seems the offsets from tantivy-jieba are wrong, offset_from and offset_to need to be byte offsets:

```
tokens.push(Token {
                offset_from: token.start,
                offset_to: token.end,
                position: token.start,
                text: String::from(&text[(indices[token.start].0)..(indices[token.end].0)]),
                position_length: token.end - token.start,
});
```

**Comment by carmel** [comment]
@PSeitz Great, it's solved. Thank you for spending your valuable time and analyzing my code so carefully, I didn't sleep much for two nights for that. Unfortunately, I only use it without knowing how it works.
