### ISSUE TITLE
[Question] Any plan for a new release?

### ISSUE THREAD

**Issue by shuoli84** [quickwit-oss/tantivy#1137]
I am writing some code depends on changes made in #1084 , seems it does not released yet. Any plan for a release? Thanks for the awesome work.

**Comment by fulmicoton** [comment]
@PSeitz any dangling ticket that would prevent us from releasing?

**Comment by PSeitz** [comment]
@fulmicoton apart the one you created I don't know of any. We wanted to wait for the blocked term dictionary, but it's not really necessary.

**Comment by shuoli84** [comment]
@PSeitz any eta for the term dictionary?

**Comment by fulmicoton** [comment]
0.16 is now released.
