### ISSUE TITLE
Cleanup crates division

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1139]
Let's move back the fastfield codec crate into the main tantivy crate.
Let's also move the common crate back into tantivy. 

The division brings nothing good and broke a lot of things that will be tedious to fix:
- publishing is impossible with a crate named common
- we have a common crate and a common module in the main crate

**Comment by PSeitz** [comment]
I don't agree that it brings nothing good. The fast compile times are really helpful during development and it enforces a clean API. I would prefer to prefix the crates with `tantivy-` and cleanup the common module in main.

**Comment by fulmicoton** [comment]
is it something you measured?

**Comment by fulmicoton** [comment]
I'm ok with this, to the condition that we don't end up with something too ugly with tantivy-common and the discussion do not end up being too lengthy.

**Comment by PSeitz** [comment]
> is it something you measured?

It's instant vs 10 seconds or more.

**Comment by fulmicoton** [comment]
for the compilation of the fastfield code crate right? not the tantivy crate.

**Comment by PSeitz** [comment]
> for the compilation of the fastfield code crate right? not the tantivy crate.

Yes, the fastfield (or bitpacker etc.) crate vs the whole tantivy crate
