### ISSUE TITLE
Add a "no compression" compressoin scheme

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#1142]
Users might supply us an already compressed payload and might want to disable compression in the docstore.

**Comment by PSeitz** [comment]
Just as clarification: The compressed data would be inside a field? e.g. a bytes field

**Comment by shikhar** [comment]
I believe this can be closed now https://github.com/quickwit-inc/tantivy/pull/1208

**Comment by PSeitz** [comment]
yes, thanks for the PR!

**Comment by fulmicoton** [comment]
Thank you @shikhar !
