### ISSUE TITLE
Wildcard expressions

### ISSUE THREAD

**Issue by stijn-uva** [quickwit-oss/tantivy#1143]
**Is your feature request related to a problem? Please describe.**
As I understand it, Tantivy currently does not support wildcard expressions, only full token matching. Wildcard expressions can be extremely useful (and depending on the case, necessary) for more fuzzy search queries, e.g. when searching for words or phrases with known alternate spellings. I found one previous issue mentioning this feature, which was closed with a note that it was quite feasible and that a specific issue for this feature would be opened: #83. But since that issue does not seem to have been created, or at least I could not find another one mentioning wildcard expressions, here is one :-)

**Describe the solution you'd like**
Support for wildcard expressions: e.g. `amsterd*m` would match both `amsterdam` and `amsterdoom`; `m*hamm*d` would match both `mohammed` and `muhammad`, and so on.

**Comment by fulmicoton** [comment]
Tantivy handles both regex queries and fuzzy term query.
https://docs.rs/tantivy/0.15.3/tantivy/query/struct.FuzzyTermQuery.html
https://docs.rs/tantivy/0.15.3/tantivy/query/struct.RegexQuery.html

**Comment by stijn-uva** [comment]
Oh, that's great! Turns out I wasn't searching for the right term :-) Thanks for the quick response!

**Comment by PSeitz** [comment]
Extended the docs a little to cover wildcard https://github.com/tantivy-search/tantivy/commit/13401f46eaa0c50713d89b033ce4d74593bd71bc
