### ISSUE TITLE
is this an in-mem engine?

### ISSUE THREAD

**Issue by shi-yan** [quickwit-oss/tantivy#1173]
Pisa says it's an in-mem engine. the full index needs to be loaded in mem, this could pose a limitation on document size.

I wonder if tantivy is the same?

**Comment by guobayang** [comment]
Just like lucene, tantivy provides "in-mem" or FileDirectory method for indexer

**Comment by fulmicoton** [comment]
It is mostly meant to be used with the mmapdirectory. Very little memory
needs to be loaded in anonymous memory.

Le sam. 9 oct. 2021 à 17:13, yang saijun ***@***.***> a
écrit :
