### ISSUE TITLE
can I store documents in the form of PDFs and use the data from those?

### ISSUE THREAD

**Issue by VaibhavDS19** [quickwit-oss/tantivy#1179]
can I store documents in the form of PDFs and use the data from those?
basically, can I use this like farm-haystack in Python, where I can store txt and pdf texts and search them?
Thanks

**Comment by fulmicoton** [comment]
You could put the pdf payload as a byte field that you only mark as stored, but for the search part you will have to extra the text on your own upstream and build your document with this text field.

**Comment by fulmicoton** [comment]
Marking the issue as closed for triage reasons, but you can add comments if necessary.
