### ISSUE TITLE
Improve the SegmentWriter's HashMap

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#126]
As tantivy's `SegmentWriter` are using a memory arena, tantivy is not using rust standard library hashmap. The current implementation is using very simplistic linear probing with a djb2 hash.

If possible improve the quality of the code there (without hurting performance), and replace linear probing with something more memory efficient (robin hood hashing?).

**Comment by fulmicoton** [comment]
It might be more important than I initially thought. See #135.
Performance are degrading extremely fast when indexing a single field with a very high cardinality.

**Comment by fulmicoton** [comment]
Oops ... Apparently there is no condition over the saturation of the hashmap :|

**Comment by arthurprs** [comment]
I'm not sure RobinHood is a good fit when you don't store the hashes (you need the hash of other items on insert/delete and optionally on lookup).

**Comment by fulmicoton** [comment]
Good point. What do you think would be the best hashmap impl here?

**Comment by fulmicoton** [comment]
It should be properly measured, but it seems to me collision are extremely expensive when indexing the movielens dataset. One strategy we could use to mitigate this cost would be to add some info within the table (1 or 2 extra byte of hash for instance) to make sure that handling most collision do not require to jump in memory to compare the actual strings.

**Comment by fulmicoton** [comment]
We also might want to express the concept of saturation as a collision rate.

**Comment by fulmicoton** [comment]
taking over this issue

**Comment by fulmicoton** [comment]
Actually I think we are ok on that one now.
