### ISSUE TITLE
improve skip performance for SegmentPostings

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#130]
The current implementation of `skip_to` is not specialized for `SegmentPostings`.

`SegmentPostings` is decoding blocks of 128 docs at a time, so rather than doing  a linear search within the block, we could at least check for the last element to see if we can skip the whole block, or do a binary search.

The problem with the latter is that it will perform not as well, when the `skip_to` does not skip much at all. This happens for instance when intersecting to posting list that are covering almost all documents, or that are strongly correlated.

Find a nice heuristic and improve the performance of `SegmentPostings`

**Comment by fulmicoton** [comment]
@lnicola posted a MR here https://github.com/tantivy-search/tantivy/pull/153

**Comment by lnicola** [comment]
Implemented in https://github.com/tantivy-search/tantivy/pull/153.
