### ISSUE TITLE
Indexing the movielens dataset seems comparatively very slow

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#135]
Indexing Movielens is comparatively very slow compared to indexing wikipedia even though it has way less tokens.

is it because it has more fields?
because it has int fast fields?

**Comment by fulmicoton** [comment]
it seems due to the indexed i64 fields with a high cardinality. Plus the performance are not that horrible in the beginning, so it is probably a problem of saturation of the hashmap.

**Comment by fulmicoton** [comment]
Oops ... Apparently there is no "close-segment" condition over the saturation of the hashmap :|

**Comment by arthurprs** [comment]
I think we need to dig the problem further before looking into options. From your post in the other thread it's not clear what's the problem. It appears to have a static size, so how do you size this hashmap in advance?

**Comment by arthurprs** [comment]
Nevermind, I just saw that you have a PR to fix this https://github.com/tantivy-search/tantivy/pull/146

**Comment by fulmicoton** [comment]
The user gives a RAM budget to tantivy. This budget is split between indexing thread. Each of them build a memory arena and stores terms and inverted list in this memory arena.

The terms are stored in a hashmap. The table of this hashmap has a fixed size, which is a ratio of the overall memory arena. The rest of the memory arena is used as a heap with a bumping allocator, and receives both the terms themselves, and the inverted lists.

The terms and the beginning of the inverted list associated to them are allocated one after the other so they lie continguously (at least the beginning of the inverted list) in the memory arena.

Depending on the indexing options, we record either
- the list of doc ids containing the term
- the list of docids and the list of term frequency
- the list of doc ids and the positions of the terms.

You can check the recorder in the code to get the detail. In the end, they are all more or less list of `u32`. 

The datastruct is something halfway between unrolled linked list and a `Vec`.
It is a linked list of blocks with an exponentially increasing size.

After indexing a document, if one of the following two condition is met 
- the table is saturating (currently 1/3rd of the capacity in master, 1/5th of the capacity in the branch you commented on),
- the heap is reaching capacity (full - some kind of margin)

Then the segment is close and flushed to disk. Another one is opened.

This condition can only be checked after each document, so a huge document can actually
exceed capacity of the table or the heap.

There is currently nothing done for the table, and it can be considered a bug. 
The heap on the other hand, is in fact a linked list of heap for this problem.

**Comment by fulmicoton** [comment]
@arthurprs  @kaedroho  @Burntsushi Are you all in a meetup or did you all swing by tantivy's github on the same day by concidence?
