### ISSUE TITLE
How to add index support for other languages?

### ISSUE THREAD

**Issue by sunface** [quickwit-oss/tantivy#137]
I want to add index、tokenlized functionality for chinese language,but have no idea where to start,can someone  help me with that?

**Comment by sunface** [comment]
eg: in elaticsearch,we have ik plugin

**Comment by fulmicoton** [comment]
It is not possible for the moment.

Right now tantivy text analysis pipeline is EXTREMELY naive. There is only a whitespace tokenizer. I plan to have a proper text analysis module for 0.4.0.

Sooo.... not possible at the moment. Maybe it will be possible in a month or so. (it depends on whether i found a solid chinese tokenizer in Rust)

**Comment by sunface** [comment]
Thanks for reply,maybe i can implement the chinese tokenizerthe.
Some questions here:
1.Is the default  tokenizer SimpleTokenizer?
2.if I add chinese tokenizer,should I  add it in mod analysize?
3.Should I wait for 0.4.0,and implement then？

**Comment by sunface** [comment]
A simple way to resolve this: every non-ascii char is a individual token

**Comment by fulmicoton** [comment]
@sunfaces right now, tantivy structure does not allow to welcome different tokenizers, so there is only a super simple tokenizer that really only works for English. I need to do some preliminary work to make tantivy ready to welcome your contribution.

> A simple way to resolve this: every non-ascii char is a individual token

Yes I have heard of this trick. Does it give accurate result in your experience? Do you transform everything into phrase queries in that case?

**Comment by sunface** [comment]
By some simple tests,the result is ok.But i dont really understant phrase queries.
The data is `    let mice_and_men_doc = try!(schema.parse_document(r#"{
       "title": "你好中国",
       "body": "hello,中国人民,你们好吗?"  
    }"#));
let mice_and_men_doc1 = try!(schema.parse_document(r#"{
       "title": "你啊好中国",
       "body": "hello,中国人民,你们好吗?"  
    }"#)); `

The query statement is `let query = try!(query_parser.parse_query("你啊+国"));`

The result is `{"body":["hello,中国人民,你们好吗?"],"title":["你啊好中国"]}`

**Comment by sunface** [comment]
Another question, I want to implement a proxy layer with go language for heavy net io、sharding、data schedule、web ui，how do you think?

**Comment by fulmicoton** [comment]
@sunfaces can you send me your schema? Phrase query only work if you have indexed "positions". Keep in mind they are pretty slow for the moment.

**Comment by fulmicoton** [comment]
@sunfaces Another question, I want to implement a proxy layer with go language for heavy net io、sharding、data schedule、web ui，how do you think?

By proxy layer you mean bindings? Any project using `tantivy`is welcome.
Keep in mind that tantivy is still extremely young and the API is likely to change at every minor version until 1.0.0. The changes are typically a matter of minutes to fix but it can certaintly be annoying.

**Comment by sunface** [comment]
The all code is here: https://gist.github.com/anonymous/e0d1325ac3ffbdd171e55785c0a95837
<br />
Please help me anlysizing the performance,is there anything that i can improve?It seems i'm not using the   
phrase query
