### ISSUE TITLE
Some  issues(maybe performance affected) found when reading the source code

### ISSUE THREAD

**Issue by sunface** [quickwit-oss/tantivy#145]
Hi there:
    I have began to study tantivy's source code,and found two issuses:
   1. why not use std::chan but use a third-party chan (eg: in index_writer.rs), and this third-party one seems to be performance loss 
   
    2. In the function open_index_writer(index_writer.rs), index.opstamp() has been called twice, which seems to be very expensive(meta.json open_read)

**Comment by fulmicoton** [comment]
What do you mean std::chan ? Are you talking about mpsc ?

**Comment by fulmicoton** [comment]
About point 1. What makes you think it would make a difference?
chan is used as a job channel dispatch channel. I don't think we are in the range where chan's performance is a problem.
If you are talking about `mpsc`, it is multi producer and single consumer while want the opposite. It is possible to wrap it in a `Arc<RwLock>`, but it probably has similar performance issues.


About point 2. It is a good point, I'll fix it... but not for the performance but for consistency and code quality. AFAIK Nobody cares if opening an `IndexWriter` is 0.1ms longer.

**Comment by sunface** [comment]
got it , thanks for reply.

**Comment by fulmicoton** [comment]
Reopening. Your point 2 is valid.
