### ISSUE TITLE
Use it to measure similarity between texts?

### ISSUE THREAD

**Issue by LeMoussel** [quickwit-oss/tantivy#15]
Do you think it is possible to use tantivy to measure the similarity between texts?

**Comment by fulmicoton** [comment]
It does compute a similarity metric called tfidf, and you can request the output. You question is a bit too broad though.

**Comment by LeMoussel** [comment]
Excuse me for my poor English, I'm french :)

I am wanting to write a program that will take documents and determine how similar they are. 
My idea of doing this, is to transform the documents into tf-idf vectors, then compute the cosine similarity between them.  Ref: [Vector space model](https://en.wikipedia.org/wiki/Vector_space_model)

Is it possible to do this/determine similarity with tantivy?

**Comment by fulmicoton** [comment]
No it is not possible to do that with tantivy.

To compute the similarity between two specific documents, you probably want something like Lucene's TermVectors.
