### ISSUE TITLE
Have proper examples / test in the rustdoc

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#166]
Especially for collectors and queries

**Comment by drusellers** [comment]
- [x] TopCollector
- [x] MultiCollector
- [x] FacetCollector
- [x] CountCollector
- [x] ChainedCollector

- [x] TermQuery
- [x] RegexQuery
- [x] FuzzyTermQuery
- [x] RangeQuery
- [ ] PhraseQuery
