### ISSUE TITLE
[Bug Report] Phrase query can't get all docs 

### ISSUE THREAD

**Issue by sunface** [quickwit-oss/tantivy#190]
I have done  a simple tokenize solution for non-english letters,every letter turns into a term, so when I search '中国人民', it is a   phrase search with four terms:  '中' 、'国'、'人'、 '民'

In version 0.3.1, the search is very ok,when I index 10 docs include '中国人民'，the search results show them all.
But when in version 0.4.0-alpha, it seems that result is not ok, the total hits usually is smaller than the actual docs,but when I search with '中',then all docs appeared.

Is that a temporary bug? At lease in 0.3.1, there is no such problem.

**Comment by fulmicoton** [comment]
can you share a small list of document that makes it possible to observe the problem?

**Comment by sunface** [comment]
In 11MB wiki-articles.json, you can search '少年中国晨报'

Raw doc:

{"url":"https://en.wikipedia.org/wiki?curid=48634668","title":"Liu Luyin","body":"\nLiu Luyin\n\nLiu Luyin (zh: 刘芦隐, pinyin: Liú Lúyǐn) (b. 1894 - 1969) was a Chinese politician of the Kuomintang and CCP in service to the Republic of China and the People's Republic of China.\nBiography.\nLiu Luyin was born in Yongfeng County, Jiangxi Province during the late Qing Empire\nLiu attended school at Nanchang where he graduated from secondary school. He was thereafter admitted to Fudan University in Shanghai. He transferred abroad to the University of California where he earned his bachelor's degree in economics in 1921.\nHe became the editor in chief of the \"Young China Morning Post\" (zh: 少年中国晨报) and was appointed as the Director-General of the San Francisco Kuomintang Party Headquarters being also active at the party's Canadian branch. In 1922, he was transferred to Shanghai where he became active in the Kuomintang youth organizations at Shanghai University. He later became a professor at Fudan University. He became active in the KMT's information and propaganda wing under Chen Lifu but in 1936, he was purged from the party as a traitor though he escaped execution.\nAfter Sichuan was taken by the Communists, Liu became a member of the Provincial Research Institute of Culture Librarians and a \"Wen Shi Guan\" Team Leader. In 1955, he was elected to the Sichuan Province CPPCC community working group.\nLiu died in 1969 at Ya'an, Sichuan.\n\n"}

**Comment by sunface** [comment]
maybe you need to change this function to 
```
impl<'a, 'b> StreamingIterator<'a, &'a str> for TokenIter<'b> {
    #[inline]
    fn next(&'a mut self) -> Option<&'a str> {
        self.term_buffer.clear();
        // skipping non-letter characters.
        loop {
            match self.chars.next() {
                Some(c) => {
                     if !c.is_ascii() {
                        append_char_lowercase(c, &mut self.term_buffer);
                        return Some(&self.term_buffer);
                    }
                    if c.is_alphanumeric() {
                        append_char_lowercase(c, &mut self.term_buffer);
                        return self.consume_token();
                    }
                }
                None => {
                    return None;
                }
            }
        }
    }
}
```
in analyzer module, this change make a non-english letter into a term

**Comment by fulmicoton** [comment]
I'm currently working on a proper tokenizer/analysis pipeline. Stay tuned.

**Comment by sunface** [comment]
Ok, I will wait for this , and maybe contribute to the chinese tokenizer ，there are billions people on this planet using chinese :).

**Comment by fulmicoton** [comment]
Absolutely. That would really be awesome ! :+1:

**Comment by fulmicoton** [comment]
Closing. See #191 for the analysis pipeline development.
