### ISSUE TITLE
Error in the example: "body" field incorrectly described.

### ISSUE THREAD

**Issue by kyegupov** [quickwit-oss/tantivy#224]
In the documentation: https://fulmicoton.com/tantivy-examples/simple_search.html

> Our first field is body. We want full-text search for it, and we want to be **able to retrieve** the body after the search.

but it is not labelled as `STORED` and in the end of the example we see

> Since the body field was not configured as stored, the document returned will only contain a title.

**Comment by fulmicoton** [comment]
Thank @kyegupov ! That's a good catch.
