### ISSUE TITLE
Display a nicer error when we acquire the IndexWriter lock

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#235]
Currently the error message is

 thread 'main' panicked at 'Indexing failed: Error(FileAlreadyExists(".tantivy-indexer.lock"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916:4

**Comment by petr-tik** [comment]
hey, I have been reading and grepping the codebase and it seems that there is a method in core/index that [checks for already existing lock](https://github.com/tantivy-search/tantivy/blob/master/src/core/index.rs#L158) and 2 tests that check for locks and their release, when index goes out of scope. 

[test1](https://github.com/tantivy-search/tantivy/blob/master/src/indexer/index_writer.rs#L651-L660)
[test2](https://github.com/tantivy-search/tantivy/blob/master/src/indexer/index_writer.rs#L680-L690)

Are there any other use cases? If so, can you please give me steps to reproduce the issue? Thanks

**Comment by petr-tik** [comment]
Using the date of you opening the issue 14/1/2018, I went back to 1edaf7a3126eda8be6c50592c53b3b0fc19cb9bf, which had the same directory_lock checks, which nullifies my previous comment. 

What is the best way for me to reproduce this error, so I can work on a better error message?

**Comment by fulmicoton** [comment]
This is not a bug. This ticket is just about improving the user experience with a nicer error message.

**Comment by petr-tik** [comment]
hey, I didn't phrase it well. I get that it's a improvement and not an issue. By 

> reproduce this error

I meant to ask if there was a test or example that I can step through with rust-gdb and see where this error message comes from, assess the context of the error and start a PR with a better error msg. 

From my reading of the codebase (your blogs are super helpful to learn about the design, but I am still at early stages), I have found several examples where such a panic might throw, but no place where the message contains `Indexing failed`

```bash
$$$ grep -ir "Indexing failed" src/
$$$
```

The function that I suspect does that is `open_index_writer` and one of the places it's called is 
[core/index.rs#L153-L166](https://github.com/tantivy-search/tantivy/blob/master/src/core/index.rs#L153-L166)

Am I on the right track?

**Comment by fulmicoton** [comment]
It should happens if you create an Index and call `.index_writer(...)` twice in a row.

One of the test you pointed reproduces.
See test https://github.com/tantivy-search/tantivy/blob/master/src/indexer/index_writer.rs#L656

We want a more explicit error message there.

**Comment by fulmicoton** [comment]
You can check information about why this lock exsits and what to do when the error happens here.
https://github.com/tantivy-search/tantivy/blob/master/src/indexer/index_writer.rs#L102
