### ISSUE TITLE
Compilation error: missing simdcomp

### ISSUE THREAD

**Issue by Fiedzia** [quickwit-oss/tantivy#24]
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "./cpp/simdcomp/include" "-std=c++11" "-O3" "-mssse3" "-o" "/home/maciej/git/tantivy/target/debug/build/tantivy-c843e95d6308187a/out/cpp/simdcomp_wrapper.o" "-c" "cpp/simdcomp_wrapper.cpp"
cargo:warning=cpp/simdcomp_wrapper.cpp:4:22: fatal error: simdcomp.h: No such file or directory
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))

How should I install it? Documentation doesn't mention it.

**Comment by fulmicoton** [comment]
simdcomp is a git submodule

You need to run

```
git submodule init
git submodule update
```

to download it

**Comment by Fiedzia** [comment]
Thanks, works now.

**Comment by fulmicoton** [comment]
Reopening. I really need to write something in the README.

**Comment by manuel-woelker** [comment]
Ran into this today, would you consider a PR to use git subtree instead to make it easier for new contributors?

**Comment by fulmicoton** [comment]
To be honest I didn't know about git subtree and yes it sounds like a good idea.

I am looking forward to your PR.
