### ISSUE TITLE
can you call load_searchers concurrently with searcher.search?

### ISSUE THREAD

**Issue by pwoolcoc** [quickwit-oss/tantivy#240]
Hello, I was wondering if it would cause problems to call `index.load_searchers` while a search was being run with `searcher.search`? I dug through the code a bit but didn't come up with a good answer.

**Comment by fulmicoton** [comment]
Calling `.load_searchers()` while a search is being running should be fine...

Let me detail the way it works.
Index embeds a pool of `Searcher`. When you search, you are required to borrow a `Searcher`  from the pool. Giving the `Searcher` back is enforced by Rust's typesystem.

As long as the `Searcher` instance exists, all of the resource required to `search` will be available. It's precisely its role. It opens all of the `ReadOnlySource` (mmapped file if you use the `MmapDirectory`) and by contract a `ReadOnlySource` should make it possible to access its data regardless of whether somebody tried to delete the underlying file or not for instance.

For mmap this is aligned with Mmap specification in Mac, Windows and Linux. A tiny twist with Windows is that a file cannot be deleted while it is mmapped. This is one of the main reason why tantivy has a file garbage collector : files get "eventually" deleted. On windows, if you keep an old searcher open forever and merge some segments, this obsolete segment files will only get removed after you release the searcher.

As for `.load_searchers()`, it checks if the index was updated by the index writer, eventually creates new searchers append them to the pool. The old searcher and their resources are still available all the time.

Now, there is an actual bug if you index and search at the same time. The current approach DOES have a race condition that can make `.load_searchers()` return an error. We do not lock anything so between the moment when we read the `meta.json` and the moment when all of the file get opened, if a `.commit()` and a GC happen in a row before you finish loading the searcher, then some files may have been deleted. In that case `.load_searcher()` will return an error.
It should be addressed once we get a proper IndexReader, probably by applying a read lock to the directory.

**Comment by fulmicoton** [comment]
(Thanks for the excellent question)

**Comment by pwoolcoc** [comment]
@fulmicoton oh wow, thanks for the awesome answer! sorry I didn't see this earlier, but I really appreciate you taking the time for such a detailed answer.

I was going to ask about concurrent indexing & search next, so also thank you for mentioning that
