### ISSUE TITLE
can i dynamic index？

### ISSUE THREAD

**Issue by SamPeng87** [quickwit-oss/tantivy#243]
I want impl some dynamic index,but I don't know what happen with that.

my mean is first:I create index a,b,c,d
then,I reopen this index,create index a,b,c,d,e.
is all Ok?

**Comment by fulmicoton** [comment]
I am not entirely sure if I understand your question.

You can index a bunch of documents (docA, docB, docC, docD).
Reopen the index.
Add extra documents (docE).
You then end up with docA, ..., docE.

If you want to update the content of a document, you will need to remove the document first and insert the new version.
