### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by sunface** [quickwit-oss/tantivy#251]
Hi:
   Range query in 0.5.0, is there an example about how to use it?

**Comment by fulmicoton** [comment]
It s not big but there is an example in the docs.

https://tantivy-search.github.io/tantivy/tantivy/query/struct.RangeQuery.html

Note that if the nightly feature is enabled you can use ... for inclusive ranges.

**Comment by sunface** [comment]
very appreciate

**Comment by drusellers** [comment]
@fulmicoton is the range query still nightly? I was thinking you went through and made tantivy available on stable.

**Comment by fulmicoton** [comment]
Tantivy is stable in master, (yet unreleased) . The inclusive range syntax
will be deprecated. (Inclusive range will still be still be possible with a
different syntax)



Le mar. 1 mai 2018 à 5:47 AM, Dru Sellers <notifications@github.com> a
écrit :
