### ISSUE TITLE
Comparison with lucene

### ISSUE THREAD

**Issue by madmaxio** [quickwit-oss/tantivy#252]
Can we discuss how is this project compared to lucene in terms of performance/features? This will help talking people with java background about rust coolness.

**Comment by fulmicoton** [comment]
@jason-wolfe started a benchmark project. We will communicate the results once the project is more complete. https://github.com/jason-wolfe/search-index-benchmark-game

( And if you want to help, please contact him)

So far the two obvious wins are

1. startup time : you can start a process that uses a large tantivy index an run your first query in less than 10 ms if your data is in pagecache. Hundreds of ms if your data is not in cache. Tantivy is therefore great for command line interfaces for instance.
2. no GC. A tiny portion of your traffic will be getting very bad latency.


For the rest...
We do not have a fair benchmark for indexing. Right now tantivy is much faster but Lucene's code is not multithreaded.
We only have bench with scoring disabled and where we just count the number of documents in the docset. Tantivy is much slower than Lucene for some phrase queries. A bit faster than Lucene for the other queries that we tested (assuming cache is disabled).

**Comment by madmaxio** [comment]
Wow that’s exactly what I wanted, should I close the thread? Thx

**Comment by fulmicoton** [comment]
Will do. We'll come back with more exhaustive/more accurate results some day in the future.
