### ISSUE TITLE
Replace LZ4 dependency for a pure rust implementation

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#257]
If it hurts performances, leave it behind a feature gate.

**Comment by drusellers** [comment]
Did you have one in mind? I found - https://crates.io/crates/lz4-compress

**Comment by fulmicoton** [comment]
I did not have one in mind precisely.

`snap` seems like a pretty solid implementation.
On the wikipedia dataset, the storage went from `5.2 GB` to `5.0 GB`. Indexing time and serve time went up quite strongly.
