### ISSUE TITLE
Make MUST a possible default in the query parser

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#27]

**Comment by fulmicoton** [comment]
Requires #57

**Comment by manuel-woelker** [comment]
As far as I can tell this is resolved via QueryParser::set_conjunction_by_default()

Only the doc comment seems to be incomplete, cf.
https://github.com/tantivy-search/tantivy/blob/0.2.0/src/query/query_parser/query_parser.rs#L89

**Comment by fulmicoton** [comment]
You are correct. It was done as part of another ticket and I have forgotten to close this ticket.

**Comment by philippludwig** [comment]
The documentation in https://tantivy-search.github.io/tantivy/tantivy/query/struct.QueryParser.html needs to updated regarding this as well.

**Comment by philippludwig** [comment]
Furthermore, ``OR`` doesn't seem to work after you call this.

**Comment by fulmicoton** [comment]
@philippludwig AND and OR are not supported at all for the moment. See #246.

Only the `[+-]?a` is supported for the moment.
