### ISSUE TITLE
Create `&[u8]` fast fields

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#270]
They can use the double array strategy used for multivalued int.
This requires to add another type in the schema.

We can use base64 for its JSON encoding.

**Comment by fulmicoton** [comment]
@jason-wolfe do you want to take over that one?

**Comment by jason-wolfe** [comment]
Double array strategy but without bitpacking/having to bitunpack the value array entries, right?

Sure! I'll take a look.
