### ISSUE TITLE
Facets silently dropped on segment merge

### ISSUE THREAD

**Issue by jason-wolfe** [quickwit-oss/tantivy#274]
Facets are represented as a pair of indexed fast fields that need to be handled specially in IndexMerger::write_fast_fields, but are not currently.

As a result, they will not work correctly after a merge is performed.

**Comment by fulmicoton** [comment]
Thanks for catching that. It really sucks big time! O_O

I'll fix it and yank `0.5.1` when I get some time.

**Comment by jason-wolfe** [comment]
No problem! I didn't find it from actual breakage of my stuff, at least :)

I guess MultiValueIntFastFields may also be broken but I'm less confident on that one.

**Comment by fulmicoton** [comment]
Probably yes... and `MultiValueIntFastFields` and `HierarchicalFacets` need a different treatment.

**Comment by fulmicoton** [comment]
@jason-wolfe If you want to take over this as part of your work on #270, could you work off the `0.5.1` tag so that I can release a fixed 0.5.2 ?
