### ISSUE TITLE
Add built in functionality for understanding per-field storage size

### ISSUE THREAD

**Issue by jason-wolfe** [quickwit-oss/tantivy#281]
Add libraries to tantivy core for exposing per-thing (where "thing" could be postings, fast field, etc.), per-field information on disk usage.

This should be designed in a way to be able to be called and exposed to the user in tantivy-cli, which should also mean it's sufficient for other programmatic usages.

**Comment by jason-wolfe** [comment]
I prefer having structured data, even if it means adding more structs specific to things. It just makes it easier to consume correctly as a user. But I'm also not opposed to the looser Map if you feel it's sufficiently beneficial.

We could expose a looser homogeneous interface for walking over the tree, for programmatic display.

**Comment by fulmicoton** [comment]
Do you have a use case different than monitoring?

**Comment by jason-wolfe** [comment]
Nope.

EDIT: I think a Map<String, String> would be good.

**Comment by fulmicoton** [comment]
Any opinion on how we namespace?

**Comment by jason-wolfe** [comment]
I'm torn between two completely opposite feelings now.

First there's the fully specialized option as per the pull request and discussion above.

Secondly there's the fully dynamic option, with just enough information to monitor and also to roll up per-field while still supporting path-to-bytes within the field:
```
enum SpaceUsage {
    /// Made up of named parts
    Composite(HashMap<String, Node>),
    /// Made up of fields. Separate from `Composite` for roll-up purposes
    PerFieldUsage(HashMap<Field, Node>),
    /// Bytes!
    Bytes(ByteCount),
}

struct Node {
    entry: SpaceUsage,
    /// Arbitrary associated information at this point in the tree
    misc: HashMap<String, String>,
    // cached_total: ByteCount ?
}
```

The dynamic approach can be handled programmatically and is capable of having changed structures / new associated information without consumers breaking or requiring changes to be fully comprehensive.
