### ISSUE TITLE
Multi-stage Collector

### ISSUE THREAD

**Issue by jason-wolfe** [quickwit-oss/tantivy#283]
The current `Collector` interface has a couple deficiencies.

First and foremost is that `set_segment`+`score` is not very clean / does not integrate well with Rust's type system and idioms. In order to, for example, write a `Collector` that uses a u64 fast field reader, one must resort to having a field of type `Option<FastFieldReader<u64>>`. It will be initialized to `None`, and set to `Some(reader)` in the call to `set_segment`. Then, in the call to `score`, there must be a safety check that the `Option` is in fact set to `Some` (which we should know due to `set_segment` having returned `Ok(())`), and then actually using the `FastFieldReader<u64>`. This results in many unnecessary lines of code and possibly a tiny performance degradation from the branching. This happens for every document that gets sent to the `Collector`.

Secondly, there is no safe way to break up the problem of collecting across all segments to take advantage of execution parallelism.

There are a number of different possible ways to approach these issues.

One way, which I am proposing for now, is to break the `Collector` interface into two parts. 

One part is the existing overall `Collector`, which will still be explicitly created and passed in, and which will contain the final results. The new functionality it will gain is an expectation for creating a per-`Segment` collector (a `SegmentCollector`), and combining the results together at the end.
The result is:

1. A new associated type: `type Child : SegmentCollector`
2. A change to the `set_segment` method, renaming it to `for_segment` and returning `Result<Self::Child>` instead of `Result<()>`.
3. A new `merge_children(&mut self, children: Vec<Self::Child>)` method for combining the per-segment results into itself.

The second part is the above-mentioned `SegmentCollector`. Its only functionality is the `score` method, which moves out of `Collector`.

With this, the `FastFieldReader<u64>` creation per-segment moves into `for_segment`, and the child `SegmentCollector` returned in the `Ok` case doesn't need an `Option` wrapping it and can safely use it.

## Justification from future improvements

This interface also opens the door to no longer collecting against each `Segment` in sequence. We can for example create a fixed thread pool and submit each `SegmentCollector` to the pool, and combine the results together at the end.

## Potential issues

Sharing state across segments can theoretically be useful.

Unit tests become harder, since we now need to to call `for_segment` with a valid `SegmentReader` in theory.

We cannot support a disparately typed `MultiCollector` with the proposed approach.
My hypothesis on this is that people don't actually have disparately / unknown typed collectors, and the main use for `MultiCollector` would be to support conditionally adding Collectors based on runtime logic.
If this is the case, we can add an `impl<T: Collector<Child=S>, S: SegmentCollector> Collector for Option<T>`, where `None` does nothing and `Some(collector)` forwards to `collector`.
With this, if someone wants to use `A`, `B`, sometimes `C`, and always `D`, they could use a `ChainedCollector` of `A`, `B`, `Option<C>`, and `D`.
If I understand correctly, `ChainedCollector` with fully concrete types will have code generated for it with a single dynamic dispatch per document, and the `match c_opt` will be a single, very predictable branch within a given query.

## Alternate solutions:

Have `for_segment` consume an `Option<Self::Child>` which will be `Some(prev_value)` when a previous value existed, or `None` when no such previous value existed. This allows sharing state across segment collection.

Have a completely separate trait for `Collector`s that can evaluate independently across segments.

**Comment by jason-wolfe** [comment]
Implemented the strawman proposal on this branch: https://github.com/tantivy-search/tantivy/compare/master...jason-wolfe:staged_collector .

**Comment by jason-wolfe** [comment]
Ah, good point! I forgot to mention. Will update the description as well as comment here:

We cannot support a disparately typed `MultiCollector` with the proposed approach.
My hypothesis on this is that people don't actually have disparately / unknown typed collectors, and the main use for `MultiCollector` would be to support conditionally adding Collectors based on runtime logic.
If this is the case, we can add an `impl<T: Collector<Child=S>, S: SegmentCollector> Collector for Option<T>`, where `None` does nothing and `Some(collector)` forwards to `collector`.
With this, if someone wants to use `A`, `B`, sometimes `C`, and always `D`, they could use a `ChainedCollector` of `A`, `B`, `Option<C>`, and `D`.
If I understand correctly, `ChainedCollector` with fully concrete types will have code generated for it with a single dynamic dispatch per document, and the `match c_opt` will be a single, very predictable branch within a given query.

If other use-cases come up we will need to evaluate them case-by-case, I think. Worst case the user can always create a fully usecase-specific one with `Vec<A>`, `Vec<B>`, `Vec<C>` for their concrete types `A`, `B`, `C` if they really need full `MultiCollector` functionality.

@fulmicoton : With that context, what do you think about me adding the impl for `Option<T: Collector>`?

**Comment by fulmicoton** [comment]
That would make it impossible to implement ElasticSearch with tantivy for instance...

Can't we just craft a solution with the same API as the current collector, in which the implementation casts dynamically the child collector to the right types?

**Comment by jason-wolfe** [comment]
I don't understand how that would work. The parent would have a Vec<Box<SegmentCollector>> and use those, but then what? Have an extension trait of `Collector` that all collectors used with MultiCollector must implement with a method that takes an `Any` and casts it to the right type or something?

I may be missing a simpler, obvious solution :)

**Comment by fulmicoton** [comment]
Yes, that's what I was thinking about.
I think with the current API it should work ok.

It closes the door to a better looking API in which:

`Collector::search` and `Collector::merge_children` return a `Result<(Self::Result)>` instead of mutating their state.

**Comment by kcm1700** [comment]
About the time complexity, using linear time selection for each segment has slightly better time complexity in theory.

Linear time selection in each segment works like this. Instead of the heap of size `k`, create an array of capacity `2k`. For each hit, push back in the array. When the count of docs in the array reaches `2k`, perform linear selection to find the top `k` docs. Drop the rest. Continue this. The final result is the top `k` docs in random order.

In the merge phase, use a heap to get docs in sorted order. `O(k log (kS))` heap insertions.

I don't know how it will perform in practice, but I want to test this if topkcollector performs bad for large S.

**Comment by fulmicoton** [comment]
Interesting. I hadn't thought of using an array of limited capacity for that. That even makes it possible to extract barrier score under which a scored doc is guaranteed to not enter the top k.

You might want to avoid appending to you `2k` array when your hit does not reach the barrier. This can be done without a branch.  (saturation requires a branch though)

**Comment by fulmicoton** [comment]
@kcm1700 feel free to open an extra ticket to investigate your idea.( larger `k` do happen when users are asking for page number 10.)

**Comment by jason-wolfe** [comment]
Thanks @fulmicoton for sorting out the `MultiCollector` stuff. That was pretty tough.

Having fully implemented the suggested API changed a all of the built-in collectors, as well as talking with @fulmicoton a bit, I think that some changes should be made.

Add an associated type to `SegmentCollector`, `type CollectionResult: Combinable` representing the result of the computation.
`Combinable` will be a new trait that gives either a `fn merge(&mut self, other: Self)` or a `fn merge(self, other: Self) -> Self`. The key part being that it lets you combine the results from multiple segments.
Add a `fn finalize(self) -> Self::CollectionResult` that turns the `SegmentCollector` into a combinable result type once finished.
I expect that it will be extremely common but not true in 100% of cases to have `type CollectionResult = Self`.
Remove `fn merge_children` from `Collector`.

There are a number of benefits of this design:
Firstly, `merge_children` resulted in `Collector` and `SegmentCollector` duplicating a lot of state between them, so that the `SegmentCollector` state for all of the children could be merged into the parent's state. This is a code smell.
Secondly, the previous design does not cleanly generalize to supporting a distributed, multi-server approach. In the proposed approach, add a `+ Serializable + Deserializable` constraint to the `CollectionResult` and we can combine the results within each server, send them over the network, and then combine the results from all the servers in the exact same way.

Looking for any feedback if anyone has any.

**Comment by fulmicoton** [comment]
Thanks for the write-up. 

> I expect that it will be extremely common but not true in 100% of cases to have type CollectionResult = Self.
I don't think it will be that common, but let's see!

One part that still needs to be discussed is how will we access the result of the different collector in the case of the `ChainCollector` and the `MultiCollector`.

For the `ChainCollector`, we will probably have a clean typed `CollectorResult` and we will just want a nice way to access the different values. Maybe [`frunk`](https://github.com/lloydmeta/frunk) can be a nice source of inspiration :) .

For the `MultiCollector`, there will once again be some downcasting involved. Maybe we can think of a sweet API that keeps  things safe and seemless to the user. `.add_collector()` could return a `Handle<TCollectionResult>`.

The `MultiCollector` could then return a `MultiCollectionResult` object and accessing the result of a specific collector would require to use the previously mentionned `Handle`.

   `let count_collector_result: usize  = handle.extract(&multi_result)`

The handle would simply look like

```rust
struct Handle<TCollectionResult> {
   position: usize
}

impl<TCollectionResult> Handle<TCollectionResult> {
  fn extract(...) {
     ... // some downcasting happening in there.
 }
}
```

**Comment by fulmicoton** [comment]
Part of 0.8
