### ISSUE TITLE
Index API Consistency

### ISSUE THREAD

**Issue by drusellers** [quickwit-oss/tantivy#286]
While working on #279 I noticed a wee bit of inconsistency in the API that I thought would be good to clean up.

## Creation
```
Index::create_in_ram(schema) // uses ram dir -> Index::from_directory
Index::create(path, schema) // uses mmap dir -> Index::from_directory
Index::create_from_tempdir(schema) //uses mmap dir -> Index::from_directory
Index::from_directory(managed_directory, schema) // a little more universal - but creates a new setup
```

- Maybe? make from directory take a directory and wrap it in managed ourselves?
- Does managed need to be exposed outside of the crate?
- `Index::from_directory` -> `Index::create_directory` ?

## Opening
```
Index::open(path) // uses mmap
Index::open_directory(directory) // new one
```

It was additionally noted:

> I agree with the concern. Also I wonder if we could entirely hide the concept of ManagedDirectory from all public API, remove the impl Directory and add the method to ManagedDirectory directly instead.
>
> That would require a bit more thinking though.

**Comment by fulmicoton** [comment]
@drusellers  Can I close this?

**Comment by drusellers** [comment]
Let me take a pass, i think its a quick PR if its not done already.

**Comment by fulmicoton** [comment]
Apparently at least one branch was merged here.

**Comment by fulmicoton** [comment]
Thanks for this!

**Comment by drusellers** [comment]
:+1: now on to the harder regex stuff. ;p
