### ISSUE TITLE
Make sure that we never keep segments with 0 documents

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#288]
Right now deleting all documents in a segment, or merging two segments in which all documents are deleted creates segments with 0 documents.

This is not a bug per-se but it is not the best specification.

**Comment by drusellers** [comment]
What is the recommended way to delete a document. Once I know that I can start to track this one down. I'm looking at `index_writer` currently, but only see `delete_term`. Is there a delete by query type support? or delete by doc id really.

**Comment by drusellers** [comment]
Ok. I'm studying the `segment_updater.rs` file, because that's where I think the logic is. I can see that the `IndexWriter` queues up deletes and that the `SegmentUpdater` appears to be processing them.

**Comment by barrotsteindev** [comment]
Hey,
I'd like to tackle this.
I am fairly new to rust, but I'm eager to learn.
Is there anything in particular I should be looking for,
any direction would help.

**Comment by fulmicoton** [comment]
@barrotsteindev That would be awesome.
Make sure you have unit tests for this. Do not bother deleting any files, tantivy has a garbage collector. If you find a way to discard the segment it will eventually deleted the files associated.

One not necessarily optimal but very simple and clean way to fix this, could be to add a `remove_empty_segment()` private method in the segment manager, and call it within `committed_segment_metas()`.

@drusellers Can you mentor @barrotsteindev on this ticket?

**Comment by barrotsteindev** [comment]
First of all,
thanks for the quick reply.
I am looking forward to working with you.

I started hacking away on a small unit test [here](https://github.com/barrotsteindev/tantivy/commit/a51397bbc21310e50be515a2f051b05757e7aa9fl).

As I was examining segment_updater.rs#perform_merge,
I noticed it requires a new segment to be create prior to merging.
I was thinking, perhaps the responsibility of creating the new segment could be moved to segment_updater.rs#perform_merge?

I guess we could create the segment after calling segment_updater.rs#perform_merge:113
`let merger: IndexMerger = IndexMerger::open(schema, &segments[..])?;`
If IndexMerger had a getter for max_doc, we could determine whether new documents will be written after the merge.
I might be overshooting or overlooking some minor technical details,
as I am new to this project.
WDYT?

**Comment by fulmicoton** [comment]
This path might eventually avoid a couple of file creation, but it may not be as trivial as it looks.

I changed the title and the description of this issue to make its scope a bit larger. Let's try to avoid keeping segments with 0 non-deleted documents.

Let's break this down a bit. We have two kinds of segment with 0 docs. 
a) segment with max_doc=0
b) segment with max_doc=n and deleted_docs = n

b) can happen wihtout any merge. When applying the delete_queue to at segment being about to be serialized b.1,  or by after a commit b.2.
It can also happen after a merge. This happens if a commit happens during the merge, and we have some catch up with the delete queue to do before accepting the resulting merged segment. 
a) Can only happen when merging segments that belong to b) after they got synced on the delete_queue.

By filtering on the `segment_manager` itself, we can remove in one place all of these problems (segment_entry contain max_doc as well as the number of deletes). We can investigate later if we can reduce IO and file creation on the different site where this is a problem.

**Comment by barrotsteindev** [comment]
I just filed a PR, hopefully I was not too far off :)
