### ISSUE TITLE
Allocate docIds in a way that is monotonic with some fast field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#29]
Sorting documents by a given field can open the door to various optimization
- sort by score related metric
- group by/collapse by a sorted field
- locality
- range queries

**Comment by druzn3k** [comment]
I want to work on this (as soon as the other PR is closed, of course), could you give me some pointer for where to start?

**Comment by fulmicoton** [comment]
@druzn3k Oh god. I left you down for 3 month on this issue too. Sorry for that. I think this will be a special case of #479.

**Comment by hwchen** [comment]
@fulmicoton can you explain a little how this would differ from the top docs by field collector?

https://docs.rs/tantivy/0.8.1/tantivy/collector/struct.TopDocsByField.html

**Comment by fulmicoton** [comment]
@hwchen Sorry my previous message was misleading. I removed it.

Right now documents get an internal document id. This document id is currenlty defined by the order in which document are added in the segment.

There are a bunch of optimization that can be done if someone choose a better order for these.

For instance, ordering by decreasing page rank makes it possible to get a nice SERP while scoring only  the first Q docs. 

This is a very interesting feature for many business, but let's not consider it until somebody actually has the need and want to use tantivy.

**Comment by shikhar** [comment]
Is this a dupe of #1014, which got closed with https://github.com/tantivy-search/tantivy/pull/1026? cc @PSeitz

**Comment by fulmicoton** [comment]
Correct . Thank you @shikhar
