### ISSUE TITLE
Add a position length to `Token`

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#291]
It will be useful if we end up merging tokens in a `SynonymTokenFilter` for instance.
The synonym should span over several tokens so that it can still matches a `PhraseQuery`

This functionality will be used in #314 

- [x] Add the property to `Token` 
- [x] Add a new constructor in `PhraseQuery` to accept offset. (this will require updating `PhraseWeight` as well)
- [ ] Fix the QueryParser to pass the `position_length` information and use the above constructor when building a PhraseQuery.

**Comment by fulmicoton** [comment]
Sorry my guidance was sloppy. Your PR looks good. Contrary to what I wrote in the ticket description this does not impact the existing `NgramTokenizer`. (I edited the ticket description accordingly)

So the main client right now is #314. Before merging your change, could you fix PhraseQuery so that it handles `position_length` correctly?

Currently all terms are assumed to have a length of 1, so the constructor just takes a [list of terms](https://github.com/tantivy-search/tantivy/blob/master/src/query/phrase_query/phrase_query.rs#L35).

We need to introduce another constructor `new_with_offsets` which takes a list of terms and their respective position offset: `&[(usize, Term)]` They should be sorted by offset.

In most case, each token should take a length of 1 and the argument query should look straightforward.
`&[(0, term_the), (1, term_three), (2, term_little), (3, term_pigs))]`. 

This will be handful when we face tokens with a token_length larger than 1. For instance, afer introducing `#314`, we can get the exact same result set by running the query as
`&[(0, term_the_three), (2, term_little), (3, term_pigs))]`.


Finally the `QueryParser` need to be fixed in order to use this new constructor. For instance, we will need to read the [token length information from the analyzer]([https://github.com/tantivy-search/tantivy/blob/master/src/query/query_parser/query_parser.rs#L256]) and eventually use the new `new_with_offsets` construction

**Comment by vigneshsarma** [comment]
I have been looking at the code and am a little confused as to how the changes you suggested are supposed to work. To start with, `PhraseQuery` currently has a `Vec<Term>`. Wouldnt this have to be changed to `Vec<(usize, Term)>`, in which case the existing constructor will have to be changed right? Another alternative is to store the offset in `Term`.  Would that work?

I am also unsure of how the two new tasks are related to the original issue. The new tasks seems to be related to querying while the original one seems to be related to Indexing/Indexed data. Am I correct?

**Comment by fulmicoton** [comment]
Yes. You need to add another constructor. The older one calls the new one.

Finally the code in the query parser need to be modified to call the new
constructor.

**Comment by fulmicoton** [comment]
The change concerns analyzers and the nature of the tokenstream.

It impacts both search and indexing.

With this change PhraseQuery are broken.

In the selective ngram ticket when indexing our tokenizer will emit the
following tokens for "the three little pigs".

- "the three"
- "the"
- "three"
- "little"
- "pigs"

This makes it possible for us to handle any PhraseQuery. The tokenizer will
just behave a tad differently.

If someone searches for "three little" we will search for [(0, three
little)]

If someone searches for "the three little pigs" we will benefit for our
extra token by searching.

[(0, "the three"), (2, "little"), (3, "pig")]

**Comment by fulmicoton** [comment]
LGTM for the second checkbox. Can you do the last one or do you want me to take over it?

The idea is to modify the `QueryParser` to call the new constructor here.
https://github.com/tantivy-search/tantivy/blob/master/src/query/query_parser/query_parser.rs#L424

That requires modifying  `LogicalLiteral::Phrase` to have it carry offsets to, and compute the offset here:
https://github.com/tantivy-search/tantivy/blob/master/src/query/query_parser/query_parser.rs#L251
https://github.com/tantivy-search/tantivy/blob/master/src/query/query_parser/query_parser.rs#L177

**Comment by vigneshsarma** [comment]
I will give it a shot

**Comment by fulmicoton** [comment]
Oops actually you might be right. I forgot in tantivy `Token` do not work with a position increment (like Lucene does). Instead they bear an actual position. I think you can work just from this position information. (the position length is still wanted though.)
