### ISSUE TITLE
Implement the `AutomatonWeight`

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#299]
In #297, we made it possible to stream through the terms matching an automaton.

We want an `AutomatonWeight` that will take an automaton, browse through these terms, opens the associated inverted list, and appends the document in a `BitSet` and producsest a `BitSetDocSet` as scorer.

A very similar logic is already implemented in the `RangeWeight`.

The `AutomatonWeight` can then serve as the base for a `FuzzyTermQuery` or a `RegexTermQuery` or a #219

**Comment by drusellers** [comment]
Sweet! I'll dig in and see what questions I have. Thank you.
