### ISSUE TITLE
Better compression solution for multifields index columns.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#313]
Currently multifastfields work using two fastfields. The first one encodes the starting index into the second one, and both are encoded using bitpacking.

The problem is that `BitPacking` is very inefficient at storing these increasing values. 
All values take as many bits at the largest one, that is to say the last one. 

Considering the `&[u8]` fast field for instance, for a segment with `D=10 millions` documents, and an average of `S=100 bytes` per document the last index is 10M * 100 = 1e9, which requires 30 bits to express.

Delta encoding is not really an option here because we want to keep random access.
So what are we left with?

One solution could be to use a simple *frame of reference* (FOR) strategy. Split our documents using a rather large frame size `F=2^b`, and store an array with the first value of each frame.

We could then compress each frame independantly by computing for each value the delta to their respective reference and bitpack it. We may or may not want to also have a different bit packing len per frame.

In our example, the largest delta for a given frame will likely be around `S * 2^b`, so each values will require `log_2(100) + b ≅ b + 7` bits.

The data for the frame of references would then take `D / 2^b * (8 + 8 + 4)` (4 bits for the bit len used within the frame and 8 bytes for the reference offset).

For `b = 7` (frames of 128 elements), the FOR data, we would end up with 80K frames, and this data should fit on `1.6MB`. The value data would end up taking `140MB`.

I am not sure this choice of b is a good one size fits all, but it should be automatic.

**Comment by trinity-1686a** [comment]
is this still relevant with the new columnar format?

**Comment by fulmicoton** [comment]
No thank you for spotting
