### ISSUE TITLE
Implement float field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#327]
The fastfield is fairly obvious.

Please investigate and report the way `FloatPoint` work.

Making it an indexed field on the other hand is not obvious at all, and requires a notion of equality.
Lucene seems to have deprecated its first implementation.

The term dictionary is lexicographically byte ordered, so supporting range queries will require a specific encoding.

**Comment by trinity-1686a** [comment]
Concerning a specific encoding for range queries, this simple enough function provide the properties one would expect, and allow to reuse u64 code the same way i64 does : 
 - for any normal number x and y, x>y ⇔ f(x) > f(y)
 - for any normal number x, f(+∞) > f(x)
 - for any normal number x, f(-∞) < f(x)
 - f(NaN) is outside of f(-∞)..f(+∞) (either above or bellow depending on which NaN, as there are 2^53 of them). I consider ranging from anything to NaN to be absurd, and NaN should be contained in no range.

The only real edge case is +0 vs -0. This consider +0>-0 whereas IEEE 754 says both are equals

```rust
pub fn f(float: f64) -> u64 {
   let bits = float.to_bits();
   if float.is_sign_positive() {
       bits ^ 1<<63
   } else {
       !bits
   }
}
```

**Comment by fulmicoton** [comment]
Yeah but range queries require more than that to work unfortunately.

To have them work out of the box, we need the byte lexicographical order to match the normal order.
For float, a solution might be to use your sign trick and rewrite both the mantissa and the floating part 
to make them big endian.

**Comment by trinity-1686a** [comment]
then, wouldn't adding a call to `.to_be()` be enough?
I tried it on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f5db93fa8da6746e2390834fef1e0837) and it seems to work (tests can't be run on the playground as it require an unavailable crate). To be explicit about comparison endiannes I added a bit of unsafe (transmute), but it's not actually necessary

**Comment by fulmicoton** [comment]
@fdb-hiroshima that's very possible. I think both the exponent and the significand are little endian. If they are in the right order your trick should work. I wish I would reason over the wikipedia spec of floating points, but I do not trust my ability to understand the mapping between bit representations and actual endianess without making a mistake...

But if your test work that's sounds like a good plan!
