### ISSUE TITLE
QueryParser support for unbounded RangeQuery

### ISSUE THREAD

**Issue by jason-wolfe** [quickwit-oss/tantivy#328]
I like this option from [ElasticSearch syntax](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-query-string-query.html#_ranges):

`field:>=5`
`field:>2`
`field:<3`
`field:<=12`

The other supported syntax is `foo:[* TO whatever]` or `foo:[whatever TO *]`

I guess we can support both. Though I'm also happy to just do the more consistent (second) one.

**Comment by fulmicoton** [comment]
That's cool

**Comment by jason-wolfe** [comment]
Any thoughts about the `:>=`... syntax? I have not currently implemented it.

**Comment by fulmicoton** [comment]
That would be sweet to add it I think. The lucene syntax is a bit ugly.

**Comment by fulmicoton** [comment]
I'd like to close this. The work seems almost entirely done.  
@jason-wolfe @drusellers Can one of you check what might be missing and open a PR?

**Comment by jason-wolfe** [comment]
Looks like #329 got merged long ago so the only thing missing is ElasticSearch syntax.
I consider that optional for completing this work, so this can be closed.

**Comment by fulmicoton** [comment]
closing an opening another ticket to avoid confusion
