### ISSUE TITLE
Stemming another languages

### ISSUE THREAD

**Issue by max-frai** [quickwit-oss/tantivy#334]
Hi! I found that there is already out of box fuzzy search, now there is the only need in morphological search to allow tantivy usage as a regular search engine for general purposes.
I found that you are using rust-stemmers library which already supports a lot of languages, but the only one allowed and used is English. What's wrong with another languages and is it possible to support another now?

**Comment by fulmicoton** [comment]
Right now one can use other languages already. There is no associated tokenizer by default.
He just needs to register his analyzer beforehands.

If you have a specific language in mind, feel free to implement one or two default analyzer for it. Sometimes it is not only a matter of staking the right `TokenFilter` on top of the `SimpleTokenizer`.

If you want to contribute that or simply add an `example` showing how people can register their own `Tokenizer` that would be awesome.

**Comment by fulmicoton** [comment]
Actually I misunderstood the question. There is no constructor that makes it possible to reuse the existing Stemmer object.
