### ISSUE TITLE
Incorrect facet count

### ISSUE THREAD

**Issue by kardeiz** [quickwit-oss/tantivy#339]
With tantivy 0.6.1.

I'm looking to replace Elasticsearch with Tantivy in a small application that doesn't need much more than full text search and faceting. 

My use case may be not supported by Tantivy: the docs for `FacetCollector` state that: `This implementation assumes you are working with a number of facets that is much hundreds of time lower than your number of documents`. 

One of my facet fields is a controlled vocabulary/subjects type of field, where there may be as many or more facet terms as there are docs. I believe this is why I am getting incorrect counts from the facet collector. For example, I have terms like `/subjects/Education/Primary`, `/subjects/Education/Secondary`, `/subjects/Work`, etc. My "Education" facet has an incorrect count. However, if I only index subjects that start with `/subjects/Education`, then I do get the correct count (presumably because the number of terms is much reduced).

Is there any workaround or solution for this? I realize that I could create facet fields for each top-level of my subjects (e.g. `subjects_Education`), but that would prevent me from growing my vocabulary dynamically.

**Comment by fulmicoton** [comment]
> My "Education" facet has an incorrect count. However, if I only index subjects that start with /subjects/Education, then I do get the correct count (presumably because the number of terms is much reduced).

No that's unrelated. Tantivy is supposed to give back the right number no matter what. The warning about the number of facets is just about performance. I will try to clarify the comment.

What you experienced might actually not be a bug but expected behavior. The current specification goes as follows : if a document is both in `subjects/Education/Primary`, `/subjects/Education/Secondary`, it will count as one in the `/subjects/Education` facet if the root is `/`. So the count is really a count of unique documents in a given facet.

If the facet root is `/subjects/Education` however, the document will be counted both in the `/subjects/Education/Primary` and `/subjects/Education/Secondary` .

Is this what you observed ? If not, is there a small or large csv file that you could share, as well as the count you would have expected?

**Comment by kardeiz** [comment]
Hi, and thanks for the response!

What you describe is what I expected but not what I observed. I will put together a minimal example and post it here (will probably be tomorrow).

**Comment by fulmicoton** [comment]
Thanks @kardeiz ! that would be awesome. If making the example minimal is too much work, I am ok with a large dataset as well.

**Comment by kardeiz** [comment]
I'm away from my data at the moment, but I'm pretty sure this is the issue I was running into:

```rust
fn example() -> Result<()> {
    let mut schema_builder = SchemaBuilder::new();
    let facet = schema_builder.add_facet_field("facets");
    let id = schema_builder.add_i64_field("id", INT_STORED | INT_INDEXED);
    let schema = schema_builder.build();
    let index = Index::create_in_ram(schema);
    {
        let mut index_writer = index.writer(3_000_000)?;
        let schema = index.schema();
        for i in 0..2_000 {
            let facets = {
                let mut out = Vec::new();
                for c in (0..20).map(|x| (x + 'a' as u8) as char) {
                    out.push(format!("/subjects/A/{}", &c));
                    // out.push(format!("/subjects/B/{}", &c));
                }
                out
            };

            let json = json!({
                "id": i,
                "facets": facets
            });

            let doc = schema.parse_document(&json.to_string())?;
            index_writer.add_document(doc);
        }
        index_writer.commit()?;
    }

    index.load_searchers()?;
    let searcher = index.searcher();

    {
        let mut facet_collector = FacetCollector::for_field(facet);
        facet_collector.add_facet("/subjects");
        searcher.search(&AllQuery, &mut facet_collector).unwrap();
        let counts = facet_collector.harvest();
        let facets: Vec<(&Facet, u64)> = counts
            .get("/subjects")
            .collect();
        
        assert_eq!(facets[0].1, 2000);
    }

    Ok(())
}
```

This passes fine. However, if you uncomment the line that adds the `/subjects/B/...` facets, it fails (left: `40000`, right: `2000`). Unless I am missing something, this should still pass...

**Comment by fulmicoton** [comment]
Perfect ! Thank you @kardeiz !

**Comment by fulmicoton** [comment]
There was a bug. It is now fixed in master.

Before 0.7 is release you can either rely on master, or sort your document facets lexicographically before adding them to your document.

**Comment by kardeiz** [comment]
Awesome, thanks! I can confirm that switching to master resolves my original facet order issue.

**Comment by fulmicoton** [comment]
Great @kardeiz ! Thanks again for your report. 0.7 should be released within next month. In the meanwhile you may want to have your project point to a specific revision like `190e60a` to being annoyed when we touch master. 

If you run a performance comparison, I would be very intersted in the outcome.
