### ISSUE TITLE
Bug in FacetCounts::top_k

### ISSUE THREAD

**Issue by kardeiz** [quickwit-oss/tantivy#355]
There seems to be a problem with how facets are getting sorted.

I've modified one of the tests slightly to make it fail, and have added a naive solution here:

https://github.com/tantivy-search/tantivy/compare/master...kardeiz:top_k_issue?expand=1

I haven't opened a PR since my "solution" is inefficient and slow.

**Comment by fulmicoton** [comment]
Thanks for the report and what an embarassing bug

**Comment by fulmicoton** [comment]
Your solution is probably as efficient as it gets. I pushed a similar fix to master.
I also found another minor bug. Opening a different issue.

**Comment by kardeiz** [comment]
Wonderful, thanks! 52b4575 fixes my issue. Thanks for letting me know about #357.
