### ISSUE TITLE
What is "LZ4 compressed document store"?

### ISSUE THREAD

**Issue by madmaxio** [quickwit-oss/tantivy#366]
It is listed in the features. It is some kind of file storage or an indexed json?

**Comment by fulmicoton** [comment]
That's the equivalent of Lucene Doc Store.

When searching, Tantivy returns a list of matching document ids. These document ids have no meaning by themselves. Tantivy includes a simple row-oriented compact key value store called DocStore that contains a serialized version of a subset of your documents.

If you mark all of your fields as STORED you can retrieve your entire document.

(In larger settings, it is however common to just have search server return some kind of document identifier, and retrieves the document from a different key-value store service)

**Comment by madmaxio** [comment]
Got it, thx.
