### ISSUE TITLE
Add a simple SnippetGenerator 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#368]
(This is also called highlighter in Lucene.)

The idea is, for a given snippet and a given a number of characters limit, to return a text snippet of the search result.
If possible, the keywords should be present in the snippet and highlighted using the `<em>` tag.

The MVP could look like this :

Write a function that takes 
- a tokenstream
- a maximum length budget
- a set of keywords to highlight, with a given importance score (HashMap<String, f32>)

Go through the resulting `TokenStream`, and for each token, check if they are a token, and if so,
keep track of starting and stopping offsets... 

Identify the best fragment of text with a length shorter or equal to the budget, and return it with its score.

The score is defined as the `sum of the score of the keywords present in the document`.
A keyword appearing more than once does NOT get extra points.

A fragment must not cut any word.

(We will work in adding the plumbing to make it user-friendly in another ticket.)

**Comment by vigneshsarma** [comment]
Thanks a lot for that. I was figuring out these interfaces my self, what I would have come up with would have been completely different.

**Comment by fulmicoton** [comment]
I don't have a super strong opinion. Feel free to change this interface.

**Comment by fulmicoton** [comment]
@vigneshsarma  are you doing ok there? do you need help?

**Comment by vigneshsarma** [comment]
I am having a difficult time understanding the Lucene Java code. They are passing around a lot of mutable references and using that mutation to calculate various params. I am not sure what could help me. I think I just have to keep at it. For now, I am trying to run that Java code and run the tests as well.

That might help me understand what is going on.

**Comment by fulmicoton** [comment]
No need to do something as complicated as lucene. Sometying working would
actually be good enough.

**Comment by vigneshsarma** [comment]
Ok in that case, 

### a simpler method would be, 

* Take fragment string as the first stretch of text with max snippet length 
* if it has one of the expected keywords keep it and find the next string
* else find the next string
* at the end of it, the one with the highest score will be returned. 

### Things *not* to be done.
- Overlapping won't be tested. We can do that later.
- We won't be merging fragments for a higher score. 

What do you think?

**Comment by fulmicoton** [comment]
Sure... Let s start by making something that works. We can make improve it
later.

**Comment by fulmicoton** [comment]
@vigneshsarma Merged,l thanks. I added a `SnippetGenerator` to simplify the usage, an example, and some documentation.
