### ISSUE TITLE
Ditch `error_chain` for failure?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#373]
Open question : Should we ditch `error_chain` for `failure`?

I cannot upgrade `error_chain`, because `Error` are not `Sync`  in later versions.

**Comment by drusellers** [comment]
@fulmicoton that seems to be the path the community is going. :+1:

**Comment by drusellers** [comment]
I'm happy to help in the work on that one.

**Comment by fulmicoton** [comment]
@drusellers  that would be awesome!

**Comment by pwoolcoc** [comment]
I'm willing to help too, if needed

**Comment by drusellers** [comment]
@fulmicoton let me see what I can bang on tonight. Dinner has been consumed, cider has been opened. Let's do this. 

![](https://gph.is/YeaoHh)
