### ISSUE TITLE
QueryParser returns an error when the query only contain stop words

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#378]
If the query is empty, we currently return an empty Clause which is equivalent to an empty query.

One would therefore expect havng a single stop word, to have the same behavior.

**Comment by drusellers** [comment]
Indeed it does. What should the experience be for the caller if they supplied such a query? I'm happy to make it a better experience.

**Comment by fulmicoton** [comment]
Yes i spotted that thanks to you example actually :). I think it is fair to consider it a bug.
