### ISSUE TITLE
Multiple schemas per index

### ISSUE THREAD

**Issue by CJP10** [quickwit-oss/tantivy#385]
I'd like to preface this with multiple schemas per index might not be the best approach, regardless here is my use case.

I want to be able to have user attach meta data to their documents and search based on that meta data.

The json the user would send would look similar to this, with one caveat. All the json under the meta field is dynamic, the meta field will always be there but the contents are user defined.

```json
{  
   "title":"This is an awesome title",
   "body":"github issues are fun",
   "meta":{  
      "premium":"false",
      "readers":[  
         "mike",
         "cj",
         "ben"
      ],
      "authors":{  
         "mike_chang":"Main author",
         "john_snow":"Editor"
      }
   }
}
```

My solution was to parse the json into a schema that then parses the document, however that requires an index have multiple schemas and an index per schema model won't be viable.

**Comment by fulmicoton** [comment]
You could (or that could be done in tantivy) flatten the inner document and append the resulting terms to some kind of dynamic field.

We would need one dynamic field per type.
You document would be transformed into

```
{
"title": ...
"body": ...
"dyna_text": [
"meta.premium.false",
"meta.readers.mike",
"meta.readers.cj",
"meta.readers.ben"
...
]
```

Let's examine the pros and cons of the approach.

First you cannot choose a specific tokenizer for one of this dynamic field. The same text processing will apply to all of these.

You cannot perform complex queries about a collection in the meta. For instance , you can ask documents with an author born in the 1920s, and an author named John...What you can query for those to be the same author. (Lucene has nested documents for that.)

Field norms will be out in common. 
So your dynamic field sub field will all get the same weight in scoring.


Size is not a problem. Having long terms like this has no cost in tantivy.

**Comment by CJP10** [comment]
Thanks for the response, very helpful.

After looking at Lucene's nested docs, it seems like the best solution to this problem. Would that be a feature you'd be willing to implement?

**Comment by fulmicoton** [comment]
Some day for sure. But except if you have a super juicy use case that won't happen any time soon.

**Comment by CJP10** [comment]
Here's a more detailed overview of my use case

I work at LogDNA, if it wasn't obvious we are a logging provider.

We use Elasticsearch as our backend for searching, like anyone who has put TBs a day through it, not  a fun thing to maintain.

I think a vast majority of people looking at Tantivy are users of Elasticsearch, I certainly am.
Distributed Tantivy is now a side-project I am working on. I have the means to benchmark it in real world use cases with TBs a day of traffic, I'm hoping to match Elasticsearch performance wise but with a better consensuses model.

One of our big features that customers use all the time is the ability to add metadata and search for it.
We don't really care for scoring, just want a raw return of all docs that match.

Log line doc

```json
{ 
       "line":"This is an awesome log statement", 
       "app":"myapp",
       "level": "INFO",
       "env": "production",
       "meta": {
         "customfield": {
           "nestedfield": "nestedvalue"
         }
       }
     }
```

I actually think your solution might wok quite well for our specific use case and nested docs might not be needed, I can't speak for other people with a similar use case.

**Comment by fulmicoton** [comment]
Note that the nested doc solution has an important cost that you might not want to pay for a log solutions. Just unfolding your terms is a rather standard solution to this problem.

I can help with implementing the dynamic field within tantivy, if you are serious about your use case.
Also, let me know if you need help with the rest of the design.

**Comment by CJP10** [comment]
I think adding the "dynamic field" as part of the document parsing is likely the best solution.

I'd be more than happy to get your input on the design, as of right now I haven't finalised it myself.

I feel this issue can be closed now, again thanks for the help.

**Comment by fulmicoton** [comment]
Cool. Thanks your input.
