### ISSUE TITLE
remove `tiny_segmenter` deps, and the jp tokenizer

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#387]
It's not good enough to keep in tantivy.

**Comment by Atul9** [comment]
@fulmicoton I have opened up a PR for this.
Regarding jp tokenizer, should  I remove this file - 
`https://github.com/tantivy-search/tantivy/blob/master/src/tokenizer/japanese_tokenizer.rs`
& this method --
https://github.com/tantivy-search/tantivy/blob/master/src/tokenizer/mod.rs#L228

**Comment by fulmicoton** [comment]
The compiler should help you identify the stuff you need to clean up. 
You can also ripgrep which file is using too.

I think there is something in the analyzer manager  too.

**Comment by fulmicoton** [comment]
@Atul9 I closed your PR. 

Please do not send a PR that does not compile and does not address the issue.
I assume this is a way to book the "issue" and mark your intent to work on this, but this ends up wasting my time.  Commenting on the issue is sufficient.

**Comment by Atul9** [comment]
@fulmicoton sorry, I didn't have any intention to waste your time. I didn't check the build failure.

**Comment by Atul9** [comment]
Yes, I will

**Comment by fulmicoton** [comment]
@Atul9 do you still want to work on this ticket, or do I assign it to someone else?

**Comment by Atul9** [comment]
@fulmicoton I am not getting time to work on this issue. You can assign it to anyone.

**Comment by fulmicoton** [comment]
@Atul9  Ok no problem!
