### ISSUE TITLE
Rename the current `TopCollector` into `TopScoreCollector`, and introduce a `TopFieldCollector`

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#388]
Currently there is no off the shelf solution to sort by a given field. (e.g. date, price), instead of the BM25 relevancy score.

Following Lucene, the current `TopCollector` collector could be renamed `TopScoreCollector`, and the new collector could be called `TopFieldCollector`. If possible the two somehow share some code in common...

**Comment by pentlander** [comment]
Should this only work for fast fields or any arbitrary stored field? 

As far as I can see, the only way to get non-fast fields from the SegmentReader is through the Document, which would be pretty slow.

**Comment by fulmicoton** [comment]
Only fast field. Your understanding is correct. Stored fields would be very slow.
