### ISSUE TITLE
Implementing highlights

### ISSUE THREAD

**Issue by winding-lines** [quickwit-oss/tantivy#399]
**Is your feature request related to a problem? Please describe.**
When displaying document matches I would like to display a brief section of the field that matched.

**Describe the solution you'd like**
When I iterate through the documents in a Collector it would be helpful if I got some information about the terms that matched and/or the position in the field where that match is located. 

- If the index is already storing positions for the matched terms then I can directly use those
- If I know which terms have matched I can either do a string search in the original document (I have them stored outside the index), or tantivy could provide a search function that would duplicate additional processing that tantivy may be doing now or in the future (stop words, stemming)

**[Optional] describe alternatives you've considered**
For simple searches I could implement the second option myself.

**Comment by fulmicoton** [comment]
Issue #368 is about generating snippet with highlight. 
Would that work for you or do you need highlight on the complete text?

**Comment by winding-lines** [comment]
The approach in issue #368 looks great, thanks!

Marius
---

**Comment by fulmicoton** [comment]
Closing then.
