### ISSUE TITLE
Add a checksum to all data files.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#400]
This can be done in using wrappers over the Write and Read of the ManagedDirectory.

The write would add a footer to written files.

Probably use CRC32c or Adler. Both seem to have good pure rust implementation.

The checksum would not be used on open, but the index would have `validate_checksum()` method that could return an Error pointing to a specific corrupted file.

**Comment by drusellers** [comment]
when you say "wrappers" over the Write and Read of the `ManagedDirectory` do you mean like a new struct that delegates to `ManagedDirectory`? or do they become a part of managed directory? implemented in the `Directory` trait methods of `ManagedDirectory`?

- add `Directory::validate_checksum(&self)`
- add `ManagedDirectory::generate_checksum(data: &[u8])` how we generate the checksum
- add `ManagedDirectory::split_checksum(data: &[u8]) -> (&[u8], &[u8])` so we don't return it on read
- add `ManagedDirectory::validate_checksum(path: &Path)` tells if the path has a valid checksum

`atomic_read` would then become something like ...

```
    fn atomic_read(&self, path: &Path) -> result::Result<Vec<u8>, OpenReadError> {
        let data = self.directory.atomic_read(path)?
        let splits = split_checksum(data);
        Ok(splits.get(0))
    }
```

Does that map to your "wrapper" concept?

**Comment by fulmicoton** [comment]
They would become part of the managed directory probably. 
It would only apply to sequential file, (not the atomic API)

When creating a new sequential file... It would digest all of the bytes as the file is being written and append the checksum at the end of the file on flush/close.

When opening, the checksum would be truncated from the `ReadOnlySource` so that the change would be entirely transparent from the user point of view.

The directory could get a `verify_checksum()`. And checksum could be verified before merging segments.
