### ISSUE TITLE
Case-sensitive only query for UTF text

### ISSUE THREAD

**Issue by kolchanov** [quickwit-oss/tantivy#406]
Hello,
I have a problem with indexing Russian UTF text - it seems that only english words can be queried case-insensitive. There is an example:
extern crate tempdir;

use tempdir::TempDir;

#[macro_use]
extern crate tantivy;
use tantivy::collector::TopCollector;
use tantivy::query::QueryParser;
use tantivy::schema::*;
use tantivy::Index;

fn main() -> tantivy::Result<()> {
 
    let index_path = TempDir::new("tantivy_example_dir")?;
    let mut schema_builder = SchemaBuilder::default();
    schema_builder.add_text_field("title", TEXT | STORED);
    schema_builder.add_text_field("body", TEXT);
    let schema = schema_builder.build();
    let index = Index::create_in_dir(&index_path, schema.clone())?;
    let mut index_writer = index.writer(50_000_000)?;

    let title = schema.get_field("title").unwrap();
    let body = schema.get_field("body").unwrap();

    let mut old_man_doc = Document::default();
    old_man_doc.add_text(title, "The Old Man and the Sea");
    old_man_doc.add_text(
        body,
        "Русский текст",
    );
    index_writer.add_document(old_man_doc);

 
    index_writer.commit()?;
    index.load_searchers()?;
    let searcher = index.searcher();
    let mut query_parser = QueryParser::for_index(&index, vec![title, body]);
    query_parser.set_conjunction_by_default();
    let mut top_collector = TopCollector::with_limit(10);

    let query = query_parser.parse_query("sea русский")?;
    searcher.search(&*query, &mut top_collector)?;
    let doc_addresses = top_collector.docs();

    for doc_address in doc_addresses {
        let retrieved_doc = searcher.doc(&doc_address)?;
        println!("{}", schema.to_json(&retrieved_doc));
    }
    println!("Error! No document found with query 'sea русский'");

    let query = query_parser.parse_query("sea Русский")?;
    searcher.search(&*query, &mut top_collector)?;
    let doc_addresses = top_collector.docs();
    for doc_address in doc_addresses {
        let retrieved_doc = searcher.doc(&doc_address)?;
        println!("{}", schema.to_json(&retrieved_doc));
    }
    println!("Document found with query 'sea Русский'");

    Ok(())
}

**Comment by fulmicoton** [comment]
Ha... Good to know! 

I used "ascii lowercase" for better performance. It seems like it was a bad idea.
https://github.com/tantivy-search/tantivy/blob/master/src/tokenizer/lower_caser.rs#L39

**Comment by fulmicoton** [comment]
Also filled #407 to avoid surprises.

**Comment by fulmicoton** [comment]
Fixed in master, Will be released in 0.7.

Closing.
