### ISSUE TITLE
create_in_dir/open_in_dir split is inconvenient

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#415]
All examples use `create_in_ram`, so based in this I've just naively used `create_in_dir` in my code, and unknowingly created a program that kept throwing away all the data every time it was started.

From the examples I wasn't aware that `open_in_dir` exists, or that `create_in_dir` is always destructive (assuming `create_in_ram` is destructive because of the `ram` part, not the `create` part). I thought it'd work like sqlite, which opens a database if it exists, or creates a new one if it doesn't. 

With `open_in_dir` and `create_in_dir` split, I think I have to have something like:

```rust
if path.join("meta.json").exists() {open_in_dir()} else {create_in_dir()}
```

but I'm not sure if it's OK to check for something like `meta.json` or some other file that's guaranteed to be there. It seems like peeking into implementation detail. 

I think it'd be more convenient it there was a non-destructive idempotent function that either opens an existing or creates a blank one, automatically. It's fine if it'd always require a `Schema`, since that's easy to create and seems to be a cheap operation.

**Comment by fulmicoton** [comment]
> All examples use create_in_ram 

Not the main one, precisely for that reason. We should probably use a temp directory in all examples.

> From the examples I wasn't aware that open_in_dir exists, or that create_in_dir is always destructive (assuming create_in_ram is destructive because of the ram part, not the create part). I thought it'd work like sqlite, which opens a database if it exists, or create a new one if it doesn't.

Yeah I wondered if that would be confusing. We ended up choosing the same semantics as[ rust files](https://doc.rust-lang.org/std/fs/struct.File.html#method.create). That does not make it **right** but at least it was not made randomly.


> I think it'd be more convenient it there was a non-destructive idempotent function 

I am not fond of that solution. I would rather check if there is a `meta.json` file and return an erro by default.

**Comment by kornelski** [comment]
Yup, an error would help.

Because I need to have fields in both cases, I ended up with such code:

```rust
let field1;
…
let fieldn;
if !exists {
   field1 = schema.add_text_field()
   …
   fieldn = schema.add_text_field()
   create()
} else {
   open();
   field1 = schema.get_field();
   …
   fieldn = schema.get_field();
} 
```

It does feel repetitive and laborious.

**Comment by fulmicoton** [comment]
I see. I had forgotten you needed you file handles. 
I guess we could have a `create_or_open` method...

**Comment by fulmicoton** [comment]
Do you want to take the ticket?
