### ISSUE TITLE
Change the semantics associated to opening/creating indexes.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#416]
**Is your feature request related to a problem? Please describe.**

See #415 

**Describe the solution you'd like**

- [ ] Change the semantic of `Index::create_in_dir`. It should return an error if the directory already contains an `Index`. 
- [ ] Add a `Index::open_or_create(dir, schema)` method.

**Comment by drusellers** [comment]
I propose a new function called exists or similar that would have a signature of

`pub fn exists<Dir: Directory>(dir: Dir) -> bool`

This function uses the dir passed in to see if `meta.json` exists or not.

Then create_in_dir can return an error

**Comment by drusellers** [comment]
Working on the `open_or_create` and running into an odd error. 

```
        let index_path = TempDir::new("test_open_create").expect("can create dir");

        // create a directory
        let dir = MmapDirectory::open(index_path).expect("abc");
        assert_eq!(Index::exists(&dir), false);
        Index::create(dir, throw_away_schema()).expect("should be ok");
```

`Index::create` keeps throwing an error - "No such file or directory"

Which seems odd, it should be "making" the file and directories? Right?
