### ISSUE TITLE
NgramTokenizer panics on non-ASCII inputs

### ISSUE THREAD

**Issue by jvcop** [quickwit-oss/tantivy#429]
NgramTokenizer panics when used with non-ASCII inputs. To reproduce, simply change `"hello"` to `"hεllo"` in `tokenizer/mod.rs:250`:

`thread 'tokenizer::test::test_ngram_tokenizer' panicked at 'byte index 2 is not a char boundary; it is inside 'ε' (bytes 1..3) of `hεllo`', libcore/str/mod.rs:2111:5`

Currently, the computation of n-grams is based on incrementing the current position by one, and adding the desired length. Both would need to account for character widths to respect character boundariers.

I can work on a pull request if desired.

Tested on master (e0cdd3114d05c927a349eb07a5daaf17360661ae)

**Comment by drusellers** [comment]
@jvcop ah, thank you for pointing this out. In typical American fashion I didn't even think to test it with characters outside of my small subset of standard letters. 🤦‍♂️ - if you don't mind I'd love to tackle this as a rust learning exercise. :) But I'll ping you when its done for review and testing. Thank you for the test data as well!

**Comment by jvcop** [comment]
Sure, go ahead :) I'm glad I could help!

**Comment by jvcop** [comment]
@drusellers Nice work!

One way to get rid of the clones that I can think of right now involves getting rid of the decoding altogether. `chars` is just a means to an end; we don't actually need the codepoints

**Comment by jvcop** [comment]
Sorry, I accidentally posted in the middle of writing this :man_facepalming:

@drusellers Nice work!

One way of getting rid of the clones: `chars()` is just a means to an end here. The codepoints themselves aren't really needed, just their UTF-8 width. One could use a little helper function `utf8_width(byte: u8) -> usize` a la https://doc.rust-lang.org/src/core/char/methods.rs.html#361, or https://doc.rust-lang.org/src/core/str/mod.rs.html#1569 (lookup table version). This way, you should be able to use the array of bytes again.

In addition to this, I think you can get around recomputing positions by keeping track of the current end offset. E.g., in order to get the span of a 4-gram, use the span of the 3-gram and add the width of the next character to the end offset.

**Comment by jvcop** [comment]
> Interestingly the assembly generated by the length_utf8 code seems branches is not branchless. It is probably the best code for full ASCII, but even then, the second branch seems trivial to remove.

I'm not sure I understand this correctly, but I think the version based on the lookup table can be made branchless: https://rust.godbolt.org/z/59d9xz

It uses unsafe code, but as far as I can see the index access should be safe due to the type of the input. I'm just learning Rust, though, and by no means an expert :)

> If we want to optimize this, it might be good to properly benchmark it on a CJK language.

:thumbsup:

**Comment by fulmicoton** [comment]
yes the table impl is branch less.

Alternatively, I think we can use bsr
https://rust.godbolt.org/z/J9oGjz

**Comment by drusellers** [comment]
Ok, I think I wrapped my head around this, picking it back up to try and put it to bed.

**Comment by drusellers** [comment]
I'm happy to change my code to use the bsr - just let me know. I'm not sure how to add a test for the "grapheme spanning over more than one codepoint"

but if you can get me a unit test, i'll work on getting the son-of-a-gun to pass. :)

**Comment by fulmicoton** [comment]
You can forget the grapheme right now. It does not really matter for this
feature.

Le jeu. 25 oct. 2018 à 10:10 AM, Dru Sellers <notifications@github.com> a
écrit :
