### ISSUE TITLE
Implement deletes

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#43]
Until now tantivy only handled adding document. This issue is about adding delete. Provided a unique id term exists in the schema, update can then be done on the application side by expanding it into a delete and an add.

Since adding a document will not be the only operation anymore, "docstamp" needs to be renamed "opstamp"
For each segment, deletes are represented as a tombstone .del file that stores the bitset of documents that are deleted.

For this first iteration, only terms can be deleted. When a term is added for deletion, it is 
appended to the delete queue without being processed.

# Committed segments

Upon commit, all previously committed segment have deletes up to date up to the last commit opstamp.
Their `.del` file therefore needs to be updated up to the new commit opstamp.

# Uncommitted segments

These uncommitted segments come with a transient information which is the opstamp up to which deletes have been processed, which is not necessarily the last commit opstamp.

(All of this info being transient is ok as uncommitted segments are by nature transient. If the indexing process crashes and restart, indexing must resume from the last commit opstamp, and there is no way to use the uncommitted segments.)

When a segment being written gets closed, the deletes up to the last opstamp are read to build a bitset of the deleted documents, create a mapping of the compacted doc ids, and the finalized and flushed segment already takes in account the delete. 

Because deletes should only apply to documents that where added before the delete, a transient mapping document -> docstamp. The function is monotonic so identifying the document that should be affected by a delete is a matter of binary searching the delete opstamp in this mapping, identifying the smallest doc id with a greater docstamp, reading the inverted list from the segment writer and marking as deleted all the doc ids greater or equal to this limit docstamp.

The delete opstamp at this point is the last opstamp of the segment.

# Merging segments

When merging uncommitted segments, all of the segments tombstone bitset are updated to a common opstamp. (When merging committed segments, they are already at the same docstamp so this is not required).
Similarly to what is done with writing segments, we create a map of old docid -> new docid and phyiscally remove deleted docids.
After the merged segment is flushed, we check if its delete opstamp is up to date with the committed delete opstamp. If not, we compute and create the tombstone file accordingly.

# Dumping delete terms from Memory

The delete queue is a linear queue in which we can easily iterate over sections defined using timestamps.
The timing at which the queue can be purge is non trivial as the last consumer of it can be the commit or a currently running merge.

Client of the delete queue can suscribe to the queue and express that they will need to consume
it from a given starting point in the future.

For the first version, there will be no mechanism to purge the delete queue before commit, when the queue is getting too big.

**Comment by jamwt** [comment]
Super excited about this! We're using tantivy in a new search product at Dropbox, and the ability to delete/update documents is the key missing piece for us.

**Comment by fulmicoton** [comment]
Awesome ! I'm really glad to hear that!

It's not a huge amount of work, but I only work on tantivy around 8 to 10 hours a week. At my current pace, you will probably have to wait a month or so before `tantivy 0.3`. I'll try to find more time to work on that and release earlier.

**Comment by fulmicoton** [comment]
@jamwt Also, I'd love to hear about your use case if this is not too sensitive information.
