### ISSUE TITLE
how do do fuzzy and re searches in tantivy ?

### ISSUE THREAD

**Issue by noelzubin** [quickwit-oss/tantivy#435]
im doing something like this in my code 
``` rust
let qp = QueryParser::for_index(&index, vec![name, tags]);
let query = qp.parse_query(query).unwrap();
let mut top_collector = TopCollector::with_limit(10);
searcher.search(&*query, &mut top_collector).unwrap();
```
where query is strings like `hel* hell? hell[oO]`
but they doesn't return values like hello. 
queries with `+`; eg: `+hello` works though

**Comment by noelzubin** [comment]
ok i found the docs for query parser. Does this mean tantivy doesn't support fuzzy searches or re's ?
[query parser docs](https://tantivy-search.github.io/tantivy/tantivy/query/struct.QueryParser.html#method.parse_query)

**Comment by phyxdown** [comment]
https://github.com/toshi-search/Toshi/blob/master/src/query/fuzzy.rs
maybe it helps...
