### ISSUE TITLE
QueryParser should have Clone

### ISSUE THREAD

**Issue by juchiast** [quickwit-oss/tantivy#441]
**Is your feature request related to a problem? Please describe.**
So I'm use Tantivy in a Lua binding (via rlua), and it required me that QueryParse implements Clone. Looking at the fields of QueryParser, I think it's ok to have Clone. What do you think?

**Comment by fulmicoton** [comment]
Sure. Can you send a PR?

**Comment by juchiast** [comment]
Added.

I'm using a workaround for this issue (wrapping it inside an Arc). So you can publish new version when convenient.
