### ISSUE TITLE
What is good background reading material to get started?

### ISSUE THREAD

**Issue by ashish01** [quickwit-oss/tantivy#443]
I learn best by implementing small versions of the thing I am trying to learn. What is the smallest possible working implementation of tantivy? Is there some papers or book which is a good starting point?

Thanks.

**Comment by fulmicoton** [comment]
> What is the smallest possible working implementation of tantivy?

I will assume you mean a minimal piece of code using tantivy. If so, 
https://fulmicoton.com/tantivy-examples/simple_search.html
is a good starting point...

There are no papers nor books about tantivy.

**Comment by ashish01** [comment]
Thanks for the response.

I saw the example and its explains well how to use tantivy. My question was around how to implement something like a small version of tantivy, from scratch. So any papers, books etc used as a reference to implement tantivy will be good.

**Comment by fulmicoton** [comment]
Ah I see. 

So tantivy is a library to build search engine based on an inverted index. This is by far the most popular design for search engine, but everybody has some variations around it. Anyway, tantivy's design is pretty classical, so you can probably have a look at:
- [Stanford's book on information retrieval](https://nlp.stanford.edu/IR-book/). I think it is free online and they have an online course as well.
- [Managing Gigabytes](https://www.amazon.com/Managing-Gigabytes-Compressing-Multimedia-Information/dp/1558605703). The title is misleading... but it's about how to build a search engine.
