### ISSUE TITLE
Improv Doc for BooleanQuery.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#446]
Quoting @fdb-hiroshima

> The only issue I had with it was about BooleanQuery, I had a hard time understanding how to build theme. I was looking for some kind of function, and took a lot of time to figure out it implement From. Maybe it could just simply be mentioned in the documentation of BooleanQuery::new_multiterms_query, "to create a BooleanQuery from Box<Query> use From<Vec<(Occur, Box)>> instead" or something like that

Maybe having a `new(...)` constructor actually would not hurt, actually.

**Comment by julienfastre** [comment]
I am currently using a BooleanQuery which compiles and works. Is this issue still relevant ? I am not english speaker, but I think that I can write some code and examples that most of the readers will understand...

**Comment by fulmicoton** [comment]
Absolutely...

A rustdoc example would be awesome.

Emphasize that the `BooleanQuery` makes it possible to build any boolean query.

Explain what while queries (`term_a +term_b`). (ie. term_b is MUST, but term_a is SHOULD) 
is logically equivalent to simply `term_b`, `term_a` contributes to the score.
