### ISSUE TITLE
Externally referenceable ID

### ISSUE THREAD

**Issue by constantOut** [quickwit-oss/tantivy#452]
I am not sure if that is even a word in English, but what I mean is that Lucene Doc IDs are for internal use only and will be gone once segment is merged with another one.
So is it the same with Tantivity ?

**Comment by fulmicoton** [comment]
Same with tantivy (not tantivity) . If you need an id you need to create an indexable field for your doc. Note that lucene has an optimization for this kind of field while tantivy doesn't .

**Comment by fulmicoton** [comment]
Same with tantivy (not tantivity) . If you need an id you need to create an indexable field for your doc. Note that lucene has an optimization for this kind of field while tantivy doesn't .
