### ISSUE TITLE
LogMergePolicy

### ISSUE THREAD

**Issue by currymj** [quickwit-oss/tantivy#46]
Implement a merge policy inspired by [LogMergePolicy](https://lucene.apache.org/core/4_0_0/core/org/apache/lucene/index/LogMergePolicy.html) from Lucene.

Segment size will be determined by the number of documents.

Unless I am mistaken, this merge policy should not need to store any state.

**Comment by fulmicoton** [comment]
Merged your branch after internalizing the parameters in the struct, adding setters for them.

Tested it over wikipedia... It worked out fine.
