### ISSUE TITLE
Automatically `.load_searchers()` when `meta.json` is updated.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#475]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**[Optional] describe alternatives you've considered**

**Comment by trinity-1686a** [comment]
Wasn't this issue resolved by the creation of `ReloadPolicy::OnCommit`?

**Comment by fulmicoton** [comment]
Correct.
