### ISSUE TITLE
Create an helper to tweak the scoring function of a query

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#479]
No draft of a solution yet. 

------- 
This ticket is about defining the API that would make different kind of score tweaking easy to implement,
within or outside of tantivy's scope. 
Here is the list use cases:

- boosting part of a query *MUST HAVE*
```rust
query_a.boost(10) OR query_b
```

- sorting by a fast field *MUST HAVE*
```
query_a.sort_by(some_fast_field);
```

- letting the developer define how to balance BM25 and some othersimple  fast field (e.g: number of stars, review score, historical CTR, etc.). *MUST HAVE*
That's a use case for [crates.rs](https://gitlab.com/crates.rs/search_index/blob/master/src/lib_search_index.rs) for instance

- letting the developer score the docs using a ML model loaded for a `&[u8]` payload.
NICE TO HAVE SOME DAY. Very close to the previous one. *MUST HAVE*

- tweak the scoring function dynamically using a formula. That's very handy for rapid development
NICE TO HAVE. Probably should be an independant crate. *MUST HAVE*

**Comment by barrotsteindev** [comment]
As I'm fairly new to Rust, I've been wondering how one might tackle this one?

I have come up with two strategies in my head:

- Add a public function, set_scorer?
- Add a QueryBuilder with an option to use ::from_builder. the builder will allow you to set different attribute of the query, and finally after calling the build method, the new query will be created.
Of course, there will be an option to create a new query without using the ::from_query method, manually setting each attribute of the new query being built.

WDYT?
Would you go about this a different way?

**Comment by fulmicoton** [comment]
This is not mature at all at the moment.

**Comment by osyoyu** [comment]
Maybe decaying (https://www.elastic.co/guide/en/elasticsearch/guide/current/decay-functions.html) also falls into scope of this issue?
