### ISSUE TITLE
Add groups of operations

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#492]
**Is your feature request related to a problem? Please describe.**
People may want to group operations atomically.
One example from @elbow-jason is maintaining a unique index. 
Updating a doc consists of a `delete + insert`. In a scenario where, for some reason, the `IndexWriter` is shared between thread with a `Arc<RwLock>`, an update happening on two different thread could end up executed as `delete delete insert insert`. The final state being two docs with the same primary id.

Another use case would be to enforce a set of documents to belong to the same segment in order to enable some collector optimization. (For instance, docs with a parent/child relationship)

**Describe the solution you'd like**

Add a `UserOperation` enum in `src/indexer/operation.rs` that would contain both Add and Delete without any opstamp.

Add a method named `IndexWrite.run(&[Operation])` to run a list of operations in a grouped fashion.
These operations must get contiguous opstamp. (So the stamper must be modified to make it possible to allocate a range of ids).

The deletes are queued normally, but the adds need to happen on the same segment for the second use case. Right now the work is dispatched to the `SegmentWriter` using a channel of AddOperation.
The item should become `Vec<AddOperation>`. 

`IndexWriter.add_document` and `IndexWriter.delete_term` remain unchanged from the user point of view. They should probably rely on the `.run(&[singleton])`  internally however.

**Comment by elbow-jason** [comment]
Closing as this was added in #493
