### ISSUE TITLE
Backport build for non x86_64 to 0.8

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/tantivy#496]
**Is your feature request related to a problem? Please describe.**
0.8.1 is currently broken on non x86_64 due to missing import for `AtomicUsize` in [`src/indexer/stamper.rs`](https://github.com/tantivy-search/tantivy/blob/0.8.1/src/indexer/stamper.rs#L39)

**Describe the solution you'd like**
I'd like the fix (74f70a5c2ccb229142b7416fe33d5cba246042c6 I believe) to get back-ported as a 0.8.X, without having to wait for an 0.9 to come out

**Comment by fulmicoton** [comment]
That does seem to be the problem indeed.
Fix is on the way. 

Waiting for android CI to finish to publish.

**Comment by fulmicoton** [comment]
Published as 0.8.2 . @fdb-hiroshima can you confirm that your problem is fixed.

**Comment by mcrosson** [comment]
I can confirm this fixes @fdb-hiroshima 's report. I'm working with them to build arm images of some rust apps and Tantivy 0.8.2 solves the build failures we were seeing.

**Comment by trinity-1686a** [comment]
Thanks, that solved the problem (tested on arm)

**Comment by fulmicoton** [comment]
Awesome thanks!

**Comment by fulmicoton** [comment]
@mcrosson Please any bug you encounter too! If you can share what apps you work on I am interested :)

**Comment by mcrosson** [comment]
Im not working on any specific rust apps actually. Im one of the founders of https://lollipopcloud.solutions . We are focused on providing docs, docker containers and more for others who would like to self host but don't want to sort out the finer details. At the moment we are building plume and bitwarden_rs which is how I came across the bug.

**Comment by fulmicoton** [comment]
Cool! Thanks for the info!
