### ISSUE TITLE
Support for elastic search syntax for unbounded RangeQuery

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#498]
**Is your feature request related to a problem? Please describe.**
See #328 
QUoting 

> I like this option from [ElasticSearch syntax]
> (https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-query-string-query.html#_ranges):
> 
> `field:>=5`
> `field:>2`
> `field:<3`
> `field:<=12`

Currently we  support `foo:[* TO whatever]` or `foo:[whatever TO *]`

**Comment by dearsxx0918** [comment]
Do we support this feature now?

**Comment by fulmicoton** [comment]
No. but we support the `foo:[whatever TO *]` syntax. The ticket description is up to date.

**Comment by petr-tik** [comment]
@dearsxx0918 I am working on the PR for this, which I hope to finalise and ship for the next release. 

I would appreciate your feedback on the unit tests in my PR, in case you have use cases that I am currently not testing.
