### ISSUE TITLE
Add a method to clear the index

### ISSUE THREAD

**Issue by torkleyy** [quickwit-oss/tantivy#510]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to rebuild the index.

**Describe the solution you'd like**

It would be convenient to just call `index.clear()` and re-submit all the documents.

**Describe alternatives you've considered**

Alternatively, one could just drop all the `tantivy` resources and delete the directory.

**Comment by fulmicoton** [comment]
The method should be on the `IndexWriter`. It simply requires to remove all segment from the index and ideally trigger the file GC.

**Comment by kkonevets** [comment]
What is a permanent workaround for now?
Should I call `delete_term` for each document and then call `garbage_collect_files`?

**Comment by kkonevets** [comment]
This works just fine for me, but have to put some docs in RAM though, sure not a perfect solution
I declare writer as `Arc<Mutex<IndexWriter>>` to make it work from multiple threads

```rust
let query = match query_parser.parse_query("*") {
    Ok(v) => v,
    Err(e) => return Err(SearchEngineError::from(e)),
};

// iterate in chunks of 10_000 each over all docs and delete them
loop {
    let searcher = reader.searcher();

    let top_docs = match searcher.search(&query, &TopDocs::with_limit(10_000)) {
        Ok(v) => v,
        Err(e) => return Err(SearchEngineError::from(e)),
    };

    if top_docs.len() == 0 {
        break;
    }

    let mut writer = writer.lock().unwrap();

    for (_, doc_address) in top_docs {
        let doc = searcher.doc(doc_address)?;
        let field_value = doc.get_first(field).unwrap().i64_value();
        let field_term = Term::from_field_i64(field, field_value);

        writer.delete_term(field_term);
    }

    writer.commit()?;
    state.reader.reload()?;
}

// finally collect garbage
let mut writer = writer.lock().unwrap();
writer.garbage_collect_files()?;

```

**Comment by fulmicoton** [comment]
@kkonevets 

This is far from the most effiicent way to do this. The good news is that a fix is on the way as you already know.
