### ISSUE TITLE
Add Date Field Support for Range Queries

### ISSUE THREAD

**Issue by barrotsteindev** [quickwit-oss/tantivy#516]
Once Date Fields are merged in to master #487,
support for range queries on Date fields should be added.

**Comment by ahemon** [comment]
Hello @barrotsteindev,
I see that in this [file](https://github.com/tantivy-search/tantivy/blob/master/src/fastfield/multivalued/mod.rs) date range query in commented out and marked as 

> TODO: support Date range queries

Is this code stable ? Is there a plan to merge it ? This feature would be really useful ?

Thanks
