### ISSUE TITLE
Latest release uses downcast-rs that is incompatible with nightly Rust

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#518]
This issue doesn't affect Rust stable (yet?), and doesn't affect Tantivy on master (using downcast 1.0), but the combination of new Rust + latest tantivy 0.8 from crates.io gives:

> error[E0034]: multiple applicable items in scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/downcast-0.9.2/src/lib.rs:120:38
    |
120 |     fn is_type(&self) -> bool { self.type_id() == TypeId::of::<T>() }
    |                                      ^^^^^^^ multiple `type_id` found
    |

Could you release Tantivy update to crates.io or backport the downcast-rs upgrade to 0.8?

**Comment by fulmicoton** [comment]
can you give your specific nightly version? I'm having trouble to reproduce

**Comment by fulmicoton** [comment]
Related issue in rust-lang ; https://github.com/rust-lang/rust/issues/58922

**Comment by fulmicoton** [comment]
Ah... You must have seen that in 0.8.2. I was trying to reproduce on master.

We are dropping `downcast`  in 0.9 so everything should be ok after the release that happens today.
Ppl experience this bug should update to 0.9, it addresses a lot of major issues.

**Comment by kornelski** [comment]
Yes, I'm using 0.8, which is the latest version released to crates.io.

**Comment by fulmicoton** [comment]
Sorry 0.8.2 has a lot of important issues. I won't yank it to avoid breaking other's ppl world, but I  strongly advise to upgrade to 0.9.
