### ISSUE TITLE
Upgrading docs?

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#520]
My project using 0.8 doesn't compile with 0.9. The changelog only mentions `INT_STORED` -> `STORED` change, but not others.

Could you document changes? In the form of "if you were using X, use Y now"

It'd also be great if you kept old functions, but with `#[deprecated(note="use the other method")]`

**Comment by fulmicoton** [comment]
Yeah I'll try to be more user frinedly on updates from now on.

I just added update instructions in the [CHANGELOG](https://github.com/tantivy-search/tantivy/blob/master/CHANGELOG.md).

If I understand correctly you index on a computer and rsync the index to your server.
In your case, you probably want to use the manual `ReloadPolicy`, as by default tantivy will try to reload the index as soon as the meta.json file is updated by rsync.

**Comment by kornelski** [comment]
Thank you. That's very helpful.
