### ISSUE TITLE
Unknown error while starting watching directory

### ISSUE THREAD

**Issue by elegaanz** [quickwit-oss/tantivy#522]
**Describe the bug**
- When running the tests of https://github.com/Plume-org/Plume, a panic occurs here: https://github.com/Plume-org/Plume/blob/master/plume-models/src/search/searcher.rs#L122 when calling `Index::open`
- The panic is `thread 'main' panicked at 'Unknown error while starting watching directory "/tmp/plume-test"'`

**Which version of tantivy are you using?**

0.9.1

**To Reproduce**

I don't think this bug is deterministic, as it only happen on my computer… I will be happy to provide any additional context that can help to debug this, but I don't know what information is needed.

Thank you!

**Comment by fulmicoton** [comment]
Thanks for the bug report.

A couple of questions here.

What is your OS?

> I don't think this bug is deterministic, as it only happen on my computer

Does it happen at every run on your computer, or only sometimes? If sometimes, do you have a rough idea of how often?

I see the test runs in `/tmp/plume-test`. Can you double check the FS you use for /tmp? (probably tmpfs but please check.)

**Comment by elegaanz** [comment]
I'm running elementary OS 5 (kernel versions is 4.15, and it is based on Ubuntu 18.04), and it happens every time. I didn't happened before, and I think it is because we recently updated tantivy to 0.9. `/tmp` is on a ext4 FS, and it happens in every other directory I tried.

**Comment by elegaanz** [comment]
I just tried again, and it seems to work now. I don't really understand; I just rebooted, but I already tried to reboot yesterday, without success.

I'll close this issue for now, and re-open if needed.

Thank you for your help anyway.

**Comment by fulmicoton** [comment]
@BaptisteGelez   You certainly did not invent the error. There is probably a problem here. If the problem is indeed related to the state of your system, the error message should have given you more information.

(Reopening the ticket.)

**Comment by elegaanz** [comment]
I think I found what the error was: it is just that the maximum number of files that could be watched was reached. This command fixed the issue:

```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

I think we can close this issue for good this time. :grin: Sorry for the false warning.
