### ISSUE TITLE
Potential memory corruption in exponentially unrolled linked list

### ISSUE THREAD

**Issue by ashfordneil** [quickwit-oss/tantivy#526]
**Describe the bug**
- What did you do?
I'm using tantivy to index the C source of OpenBSD. I wrote a [custom tokenizer](https://github.com/ashfordneil/looker/blob/master/src/lexer.rs#L86) to break up C code syntactically. With the default tokenizer it works fine.
- What happened?
All indexing threads panic, after 30-40 seconds of indexing (longer in debug mode). Backtraces show that the panic happens [here](https://github.com/tantivy-search/tantivy/blob/master/src/postings/stacker/expull.rs#L169) - I added some debug code and it looks like its happening the first time through the loop. The `page` section of the addr seems to be invalid (`index out of bounds: the len is 7 but the index is 514`).
- What was expected?
Tantivy not to panic (buggy tokenizer or no).

**Which version of tantivy are you using?**
0.9.1 and then Master (5559e61)

**To Reproduce**
Was caused by running [this tool](https://github.com/ashfordneil/looker) on the OpenBSD codebase.

**Comment by fulmicoton** [comment]
@ashfordneil Thanks for the report. 

I was able to reproduce and spot the problem.

Terms are limited to `u16::max_value() = 65_536 bytes`.
You can solve your problem by plugging the RemoveLongFilter to your tokenizer.
I'll see what should be done so that the problem does not hit other users in the future.

```rust
use tantivy::tokenizer::{Tokenizer, RemoveLongFilter};
index.tokenizers().register("c", CTokenize.filter(RemoveLongFilter::limit(100)));
```

**Comment by fulmicoton** [comment]
Cool program

```rust
 looker git:(master) ✗ ./target/release/looker search contents hello
/home/paul/git/openbsd/usr.sbin/ospfd/hello.c
/* hello header */
	hello.mask = iface->mask.s_addr;
	hello.hello_interval = htons(iface->hello_interval);
	hello
/home/paul/git/openbsd/usr.sbin/ospf6d/hello.c
hello.opts = htonl(hello.opts);

	hello.hello_interval = htons(iface->hello_interval);
	hello
/home/paul/git/openbsd/regress/lib/libc/open_memstream/open_memstreamtest.c
"failed, buffer non zero (offset %d). (14)", i);
			failures++;
			break;
		}

	if (memcmp(buf + OFFSET, hello, sizeof(hello
```

**Comment by fulmicoton** [comment]
@ashfordneil  Did you manage to work around the problem? I tested the `RemoveLongFilter` approach, and indexed freebsd source code in 1mn15 on my laptop.

**Comment by fulmicoton** [comment]
I assume this is this piece of code.
> https://github.com/ashfordneil/looker/blob/master/src/lexer.rs#L136-L138

`1 << 16` itself  is not accepted, so your fix will still bug if you meet a token with exactly the size `1 << 16`. The largest accepted value is `1 << 16 - 1`.


That being said, I recommend you set a lower value than this for the largest token.
In my experience, long tokens are always binary data that people will never be able to search.

Restricting the token length to let's say 500 characters will most likely not have any impact on your users.

**Comment by fulmicoton** [comment]
In 0.10 token exceeding the accepted length will be discarded.

**Comment by petr-tik** [comment]
Do you think it might be helpful to log on warning or info levels to tell the user that some tokens were skipped? 
AFAIK, the fix prevents panics, but the failure to tokenize is silent to the user.

**Comment by fulmicoton** [comment]
@petr-tik It certainly does not hurt to add a log in debug mode at least.

**Comment by fulmicoton** [comment]
@petr-tik Added an `info!` log.
