### ISSUE TITLE
Tokenizer and accentued language

### ISSUE THREAD

**Issue by julienfastre** [quickwit-oss/tantivy#528]
**Is your feature request related to a problem? Please describe.**

I am dealing with tantivy and an accentued language (i.e. french). I would like to provide searching without taking accent into account (searching with forgetting an accent should match the world indexed with an accent).

It is a very common mistake, in french, to forget accent when typing a word.

**Describe the solution you'd like**

I think it would useful to provide a filter "tantivy::tokenizer::UnaccentFilter" which return the token without any accent:

```rust
use tantivy::tokenizer::*;

let tokenizer = NGramTokenizer
    .filter(LowerCaser)
    .filter(UnaccentFilter);
```
The `UnaccentFilter` will do some job like this:

```rust
étude => etude
accentué => accentue
âäàéè => aaaee
// etc.
```

**Comment by julienfastre** [comment]
I am currently implenting such filter in my project. I can try to implement this if this feature is accepted.

**Comment by fulmicoton** [comment]
@drusellers  already opened a PR to handle this.

**Comment by julienfastre** [comment]
Good news. I did a research on issues to avoid duplicates, but not in PR. 

I would be happy to give help if needed.

**Comment by fulmicoton** [comment]
Can you review the code? https://github.com/tantivy-search/tantivy/pull/525

**Comment by julienfastre** [comment]
I am very new to Rust, and I do not feel comfident (it is my first experience with rust but I enjoy It!). 

May I add some tests to the PR to check the code ?

What @drusellers thinks about that ? May I help for something ?

**Comment by drusellers** [comment]
I would love any tests you might have.

**Comment by drusellers** [comment]
@julienfastre I added the 

```
accentué => accentue
âäàéè => aaaee
```

to my unit tests. Are there any other edge cases you can think of?

See unit tests here: https://github.com/tantivy-search/tantivy/blob/dds/ascii-folding/src/tokenizer/ascii_folding_filter.rs#L1569

**Comment by julienfastre** [comment]
Hi @drusellers. I was thinking of reproducing the same tests of the Lucene implementation, here: https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/test/org/apache/lucene/analysis/miscellaneous/TestASCIIFoldingFilter.java

At least, the function:

- testLatin1Accents ;
- testUnmodifiedLetters ;
- testEmptyTerm (seems not to be covered in the actual tests) ;
- and maybe testAllFoldings ?

I can spent one or two hour on this during this week and make a PR on your own repo.

**Comment by drusellers** [comment]
That would be great! :)

**Comment by julienfastre** [comment]
@drusellers I create a first bunch of tests. 

It seems that one test fails. I do not know if this is an expected behaviour (the test is wrong) or if it does show a problem in the ascii folding.

```
failures:
---- tokenizer::ascii_folding_filter::tests::test_unmodified_letters stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `["END"]`,
 right: `["§", "¦", "¤", "END"]`', src\tokenizer\ascii_folding_filter.rs:1649:9
failures:
    tokenizer::ascii_folding_filter::tests::test_unmodified_letters
test result: FAILED. 317 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out
```

Inspired from: https://github.com/apache/lucene-solr/blob/80d3ac8709c6d93c4e4634dc7c10ef667a029cb1/lucene/analysis/common/src/test/org/apache/lucene/analysis/miscellaneous/TestASCIIFoldingFilter.java#L135

**Comment by julienfastre** [comment]
I apologize: the problem come from the Tokenizer: the function in `folding_helper` uses `crate::tokenizer::SimpleTokenizer`, which removes ponctuation letters. Using `crate::tokenizer::RawTokenizer` solves the problem.

**Comment by fulmicoton** [comment]
The related branches have been merged
