### ISSUE TITLE
is tantivy production ready?

### ISSUE THREAD

**Issue by tinycedar** [quickwit-oss/tantivy#530]
Can I use tantivy in production environment ?

**Comment by fulmicoton** [comment]
That is an excellent question that does not have a single good answer.

Do I want people to use tantivy in production? Yes. Absolutely... 
Some company are already using it in production...

Do I advise you to use it in production?  Well... under some restriction.
I would prefer to discuss your use case beforehands.

Facetting is not really production ready for instance.

**Comment by tinycedar** [comment]
Thanks for your reply. I am thinking can we maintain a page containing companies using it in production? Newcomers would probably be confident using it.

**Comment by fulmicoton** [comment]
That will be a verrrrry short list :). I only know that one business is using it in prod. I don't even know the name of the business. I learnt about it because someone kindly put a comment on reddit.
One government website seem to be using it in France to, but it is small.
Crates.rs is using it too.


2 large companies and one medium are lightly considering it for their search.

**Comment by max-frai** [comment]
We use it in production for a few projects with millions of visitors per month.
I don't see the reasons why you can't use it already. Everything works perfectly and fast.
Before this, we worked with sphixsearch and it was not a pleasant experience.

**Comment by fulmicoton** [comment]
Thanks for chiming in @max-frai !
After searching a little on google and github, I found 3 other project that are in production.

**Comment by fulmicoton** [comment]
@max-frai is it ok to put  book-audio.com as a user in the README?

**Comment by max-frai** [comment]
@fulmicoton no, it's a personal project which still uses sphinx and php, but I'm porting it to rust+tantivy now :)
Unfortunately, I can't show up the projects I told in public :(

**Comment by fulmicoton** [comment]
@max-frai ok! Let us know if this changes in the future.

**Comment by max-frai** [comment]
@fulmicoton I remembered. You can notice project Atlasweekend (http://atlasweekend.com). It's a big European music festival.
I wrote about it here last year: https://www.reddit.com/r/rust/comments/8xdsx5/rust_actixweb_in_the_on_of_the_biggest_music/
This summer it is still actual, any search in festival administration tools is made by rust and tantivy.
