### ISSUE TITLE
What is the right way to query a bytes field of a document?

### ISSUE THREAD

**Issue by teovoinea** [quickwit-oss/tantivy#540]
I am storing file information and my schema is the following:

```rust
let mut schema_builder = Schema::builder();

schema_builder.add_text_field("title", TEXT | STORED);

schema_builder.add_bytes_field("hash");

schema_builder.add_facet_field("location");

schema_builder.add_text_field("body", TEXT);

schema_builder.build()
```

I would like to create a query to see if a document with some `current_hash` exists. I wanted to create a query similar to this:

```rust
let query = TermQuery::new(
            Term::from_field_bytes(hash, current_hash),
            IndexRecordOption::Basic,
);
```

However the `from_field_bytes` function is private, which suggests I'm on the wrong track.

What's the right way to go here?

**Comment by fulmicoton** [comment]
bytes field are not searchable. They are only here to be used as fast field.
I added some more doc explaining that in the master. 

Coming back to your problem.
If your hash is 64bits, of course you can use `u64`.
If your hash is `128bits` or `256bits`,  I recommend you index its representation in base64.
Debugging will probably be easier too.

Make sure to use the `raw_tokenizer`. The easiest way to do that is by using the `STRING` shortcut.
That way, your hash will be indexed as is, and will not be tokenized, lowercased, etc. 


The way to configure it is :

`schema_builder.add_text("hash", STRING)`
or  
`schema_builder.add_text("hash", STRING | STORED)`

Depending on whether you want to be able to retrieve the hash given the doc address.

If you also need the fast field for some reason, you will have to store it in a separate field as string fast fields are not supported yet.

**Comment by teovoinea** [comment]
Thanks! That helped me fix my issue :)
