### ISSUE TITLE
Improve search performance via for_each() specialization

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#545]
See branch perf/experimental-union-for_each.
At least 10% to 15% perf improvement.

**Comment by shikhar** [comment]
This is done right?

https://github.com/quickwit-oss/tantivy/blob/13a4473faaddfb97b5797454149f689064ce78e8/src/query/weight.rs#L69-L100

**Comment by fulmicoton** [comment]
Yes. Thanks!
