### ISSUE TITLE
Specify field importance via weight

### ISSUE THREAD

**Issue by kkonevets** [quickwit-oss/tantivy#547]
**Is your feature request related to a problem? Please describe.**

Sometimes it is desirable to give more importance to one field over another. For example,  query matching title of a document is more important than query matching body of a document.

**Describe the solution you'd like**

It would be nice to make queries like `title:(milk shake)^3 || body:(milk shake)`
This means that `title` field is 3 times more important than `body` field. This query syntax was taken from Solr.

**Comment by kornelski** [comment]
If you add field weights, please also give it a programmatic API. I'd like to set weights of fields regardless of what query user makes (not necessarily override user-provided weight, but definitely provide defaults for all fields)

**Comment by petr-tik** [comment]
I'm starting exploring this and wanted to double check a couple of things. 

## query boosting?
that we only need field boosting, not query boosting. Reusing the example above, does anyone need the ability to write:

"title:(oreo milk shake)^3 || title:(milk shake)". 

Obviously, they are different and require different implementations, hence I'm asking upfront. 

## negative/fractional boosts
Is it useful and valid to de-prioritise certain fields with a negative or fractional weight?

## composition of boost factors
How should boost factors compose? eg. If you have a field that got a boost of 5 at schema build-time and an individual query comes in like "(field: less important phrase)^0.2" - this should be back at 1 - default boost factor or am I missing anything? 

# interface

Currently I'm thinking about adding a boost method to the Field trait, which will allow both:
Schema::builder().add_u64_field().boost_by(3)
title:(milk shake)^3 - where the query parser will call boost_by with 3 parsed from the query.

**Comment by kornelski** [comment]
I use weights in 0..=1 range, so fractional weights are useful. If it only accepts integers I'd probably use something like `boost_by(10000 * frac)`, and that would be fine as long as boosting all fields by numbers much larger than 3 doesn't cause any weirdly skewed results or overflows.

**Comment by kornelski** [comment]
I don't have immediate use for boosts in the query, but I wonder if it was useful for processing of synonyms, e.g. if I preprocessed "oreo milk shake" query to something like:

"title:(oreo milk shake)^3 || title:(cookie milk drink)"

but that's a half-baked idea. It can probably be flipped around to boosting preprocessed fields instead:

"title:(oreo milk shake) || title_lower_boost:(cookie milk drink)"

**Comment by audunhalland** [comment]
I'm also very interested in this feature. In my project we have a DIY query parser, so we instantiate `TermQuery` directly. I'm envisioning some kind of boost/weight float parameter to the `TermQuery` constructor.

Is this issue actively being worked on, @petr-tik ? I have time to contribute if that's any help.

**Comment by fulmicoton** [comment]
@kornelski it will accept a float.
