### ISSUE TITLE
Bypass WORM arcitechture

### ISSUE THREAD

**Issue by kkonevets** [quickwit-oss/tantivy#549]
My use case: 
I write a search engine as a service. I need to update a document on the fly when user modifies it. And the document should become searchable instantly.

My solution: I know Tantivy uses "write once read many" concept and there could be only one writer at once. I guess I can spawn a separate thread with index writer in it and process those docs that need be updated. Though it will block other read threads while committing. 

Ideally what I need is the ability to write to index from independent threads each having own writer.

Is my solution the only one and will it actually work?

**Comment by fulmicoton** [comment]
WORM is entirely orthogonal to your problem.

Your problem is shared by a few other users so let me open a different ticket and try to rephrase it.
