### ISSUE TITLE
More documentation and more examples

### ISSUE THREAD

**Issue by umitgunduz** [quickwit-oss/tantivy#556]
hi, we would like to share more documentation and more examples and wiki page to be richer. Especially having a rest api documentation for all features would be very useful for us to learn and use.

**Comment by drusellers** [comment]
FWIW: Tantivy is a library that other code calls, and doesn't have a web/http "interface" so we wouldn't have "REST" api. The documentation is located here: https://docs.rs/tantivy/0.9.1/tantivy/

Does that help?

**Comment by umitgunduz** [comment]
Thanks @drusellers. I will review the documentation in more detail.

**Comment by fulmicoton** [comment]
@umitgunduz I recommend checking out the `examples/` directory too.

An independent active project called [toshi](https://github.com/toshi-search/toshi) aims at offering a REST Api on top of tantivy.

**Comment by umitgunduz** [comment]
Thanks @fulmicoton
