### ISSUE TITLE
Index::open_in_dir adds \ for some reason on MacOs

### ISSUE THREAD

**Issue by madmaxio** [quickwit-oss/tantivy#562]
Index::open_in_dir adds \ for some reason on MacOs in the end of my passed path. So I can't open any index.

**Comment by petr-tik** [comment]
Hey - thanks for opening the ticket.

Can you please share a code snippet and example of how you pass path to open_in_dir, so we can create a test case?

I have added a snippet below, but my work machine is a Linux, so I cannot test locally

**Comment by madmaxio** [comment]
Looks like this

```
use std::path::Path;
use tantivy::{self, Index};

let index_path = "MyIndex";
let index = Index::open_in_dir(Path::new(index_path))?;
```

**Comment by petr-tik** [comment]
What error does it return?

**Comment by madmaxio** [comment]
`PathDoesNotExist(\n        \"MyIndex\",\n`

**Comment by buster** [comment]
I think the backslash is from escaping the double quote. Maybe you start the binary in the wrong directory?

**Comment by madmaxio** [comment]
Oh, indeed backslash was from escaping, was my issue with the correct path. Sorry for confusion.
.

**Comment by fulmicoton** [comment]
@petr-tik @buster  Thanks for taking over this!
