### ISSUE TITLE
Rewrite QueryParser with an intermediary AST

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#57]

**Comment by naturallymitchell** [comment]
Perhaps [jmespath.rs](https://github.com/mtdowling/jmespath.rs) could provide some useful code.  I just found that crate while searching for a database engine that supports a query language.  I planned to create an issue to request more [database functions](https://github.com/mtdowling/jmespath.rs/blob/master/src/functions.rs#L115) and then I found this issue.  Hope it's the right one.

**Comment by fulmicoton** [comment]
@mitchtbaum Thanks for the information. I could not find documentation about the query language itself, so I have trouble judging whether it can be used to express a filter over a collection of json documents.

**Comment by naturallymitchell** [comment]
Over on the [JMESPath](http://jmespath.org/) site, I see good docs for general  [JMESPath Examples](http://jmespath.org/examples.html) and a [JMESPath Tutorial section on Filter Projections](http://jmespath.org/tutorial.html#filter-projections).

**Comment by fulmicoton** [comment]
Thanks! I'll study this.

**Comment by fulmicoton** [comment]
It sounds very very interesting. This ticket is more about a broad user facing query language, but I can see how JMESPath could be very useful in tantivy or tantivy-cli
