### ISSUE TITLE
Intermittent `PermissionDenied` on commit (Windows, NTFS)

### ISSUE THREAD

**Issue by devnought** [quickwit-oss/tantivy#587]
**Describe the bug**
After calling `index_writer.commit()`, I am treated with a access denied error.
```
IOError(IOError { path: Some("93c23b419dcd46228c0c5e8d5bccf4c4.term"), err: Os { code: 5, kind: PermissionDenied, message: "Access is denied." } })
```
On one Windows machine I can reproduce this reliably with the `basic_search` example. On another Windows machine, it is rather infrequent and never appears with `basic_search`.

**Which version of tantivy are you using?**
0.9.1

**To Reproduce**

On one Windows machine, run the `basic_search` example.

On another, I can only reproduce it infrequently with an application I'm currently developing. Adding documents is modeled after what is in `basic_search`, however I'm adding millions of documents from a `SQLite` database and calling `commit()` once that is complete.

**Comment by fulmicoton** [comment]
I don't have much knowledge of Windows, nor access to a windows machine. Can someone have a look at that one?

For the machine where it replicates consistently, can you confirm you have ownership of the directory you are using for the index?

**Comment by devnought** [comment]
@fulmicoton I can take a look at the machine where I can replicate it consistently tomorrow for you.

I can confirm that I have ownership of the directory I am using for the index. At first I left it as-is writing the index out to a temp directory, but in an effort to try and get it working I changed it to static directory that has correct ownership and write permissions.

In each case, files are written out to the directory. A snapshot from running `basic_search` on the consistent machine:

```
.managed.json
.tantivy-writer.lock
3c029a808ddb4452bd19113fcf95563c.fast
3c029a808ddb4452bd19113fcf95563c.fieldnorm
3c029a808ddb4452bd19113fcf95563c.idx
3c029a808ddb4452bd19113fcf95563c.pos
3c029a808ddb4452bd19113fcf95563c.posidx
3c029a808ddb4452bd19113fcf95563c.store
3c029a808ddb4452bd19113fcf95563c.term
4d2edfdaba5e4bf1935f4f9efba14fc6.store
meta.json
```

**Comment by devnought** [comment]
I have had only a bit of time to investigate thus far.

In `directory/mmap_directory.rs` I've found that `meta_file.write(|f| f.write_all(data));` in the function `atomic_write` is failing:
```
Internal(
    Os {
        code: 5,
        kind: PermissionDenied,
        message: "Access is denied.",
    },
)
```

This is as far as I've got and wanted to report my findings thus far.

**Comment by fulmicoton** [comment]
We rely on `atomicwrites` to perform these writes. Could you check that you can write, (and overwrite) a file with that crate in the same directory as the bug you observed?

If there is an equivalent of strace on windows, can you copy paste the log of the different syscalls?

**Comment by devnought** [comment]
I will look into an equivalent of `strace` for you.

I have managed to create a minimal application that can reproduce the error most of the time on the machine that only experienced it intermittently:

```
use atomicwrites::{AllowOverwrite, AtomicFile};
use std::io::Write;

fn main() {
    let file = AtomicFile::new("./test.bin", AllowOverwrite);
    let data = [0u8; 256];

    for val in 0..10_000 {
        file.write(|f| f.write_all(&data)).unwrap_or_else(|e| {
            println!("Failed on iteration {}", val);
            println!("{:?}", e);
            std::process::exit(1);
        })
    }
}
```

I did find a workaround for the reported issue. If there is an error, I retry `index_writer.commit()`. This solves things for now as far as I can tell, but by no means fixes the root cause :)

I will gather more data for you.

**EDIT**
I said I can reproduce the issue most of the time, however after running additional tests the problem went away for no apparent reason. After a reboot I managed to see the issue again for a time before it went away once more. I have a suspicion it's my antivirus holding a read lock.

**Comment by lnicola** [comment]
Nb: you can use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to trace disk accesses. ETW should also work, but it's more complex to set up.

I don't know what `AtomicFile` does, but permission errors like these are sometimes caused when trying to delete an open file. There were some race conditions of that kind in Tantivy a long time ago. :-).

**Comment by fulmicoton** [comment]
Closing in the meanwhile. Please reopen if it resurfaces without the antivirus.

**Comment by boan-anbo** [comment]
Just to add that I also encountered this issue on Windows when adding more than ten thousand documents:
```
Failed to commit index: OpenWriteError(IoError { io_error: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }, filepath: "b72a582f87db4793a18a7fafe78b7eb2.store" })
```
solved it with a retry (it usually meets the OpenWriterError only once). Seems like a minor, possibly platform issue. Just wanted to add another sample.

**Comment by fulmicoton** [comment]
@boan-anbo  Like @lnicola I suspect an antivirus getting in the way.

**Comment by AliFlux** [comment]
Any update on this? This randomly occurs on windows when committing a lot of documents

**Comment by fulmicoton** [comment]
Any antivirus running?

**Comment by galop1n** [comment]
I am also observing the random IO failure will initializing a new index with lot of documents, commiting every 100 or so rather than 1000 exacerbate the problem. dropping the writer and recreating it workaround the problem.

Yes there is an antivirus and it is bitlocker encrypted drive @fulmicoton not something I can remove even for a test.
