### ISSUE TITLE
Add a macro to define document simply.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#6]
This would be handy for unit tests for instance.

Maybe something like :

`doc!(
  field1=>"toto",
  field2=>5,
)`

Value implements `From<String>` and `From<u32>` so that should be feasible.

**Comment by White-Oak** [comment]
On a side note: should `document.add` return a `Result`, returning an error, when there is already a field with such a field accessor in `Document`?

**Comment by fulmicoton** [comment]
No.

Fields are not unique.
