### ISSUE TITLE
Feature request: Glob search?

### ISSUE THREAD

**Issue by bedax** [quickwit-oss/tantivy#608]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to search where I know the result should start with, end with or contain a specific term, and the term should not be treated fuzzily. For example: file names matching `*.txt`

**Describe the solution you'd like**
I know there is the RegexQuery, and this is excellent to have, but sometimes regex is overkill. When exposing this search functionality to users, it would be nice if they could give globs.

**Comment by fulmicoton** [comment]
This is out of scope for this library. As you stated it yourself, it is redundant with `RegexQuery`.

Client program needing this functionality will have to implement it on their own. It is trivial using `RegexQuery`. If there is a large need for this, a third-party crate can be created.
