### ISSUE TITLE
Registering a BoxedTokenizer with a TokenizerManager

### ISSUE THREAD

**Issue by brainlock** [quickwit-oss/tantivy#629]
First of all, since this is my first interaction, _huge thanks_ for Tantivy! It's an awesome library, I'm really enjoying working with it.

**Is your feature request related to a problem? Please describe.**
I have some particularly expensive (to instantiate) Tokenizer, and I'm working with many different `Index`es. In order to amortize the cost of instantiating my Tokenizer, I'm trying keep a global cache of Tokenizer instances. As a cache, I'm just reusing a `TokenizerManager`, since it already takes care of all the boxing into trait objects.

The problem arises when I want to take an instance out of my cache and add it to the Index-specific `TokenizerManager`. The type of the `register` method is

```rust
pub fn register<A>(&self, tokenizer_name: &str, tokenizer: A)
    where
        A: 'static + Send + Sync + for<'a> Tokenizer<'a>,
```

and I have no way to get back the concrete tokenizer out of the BoxedTokenizer. 

**Describe the solution you'd like**

What do you think of a new method for TokenizerManager with this type signature?

```rust
pub fn register_boxed(&self, tokenizer_name: &str, boxed_tokenizer: Box<dyn BoxedTokenizer>)
```

Since `TokenizerManager::get` returns a `Box<dyn BoxedTokenizer>`, with the new `register_boxed()` I could directly register tokenizers from one TokenizerManager into another.
 
If you think this is a good addition, I can make a PR.

**Comment by fulmicoton** [comment]
Thanks for the kind word!

I tried to do a bit of refactoring to handle this in a more cleaner way. Can you have a look at 
this PR and test if this solves your problem?
https://github.com/tantivy-search/tantivy/pull/631

**Comment by brainlock** [comment]
Fantastic, thank you. Yes, #631 fixes my problem :)
