### ISSUE TITLE
RegexQuery performance

### ISSUE THREAD

**Issue by brainlock** [quickwit-oss/tantivy#639]
Hi,

I'm trying to implement prefix matching. My idea was to use a RegexQuery for
this: given a user input of "foo", build an automaton that matches "foo.+" and
use that to search the fst.

(Aside: is there a way already to do this in tantivy and I've missed it?)

While implementing this, I stumbled upon a limitation of the current
RegexQuery: the RegexQuery struct owns a String with the given regex pattern,
and builds an automaton whenever it's needed in the `specialized_weight` method.

This is a problem as building the automaton is an expensive operation, and I have
to search for the same prefix over N fields.

What I did to address on a branch of mine:

- change RegexQuery to own a fully built Regex instead of a string pattern

- change Regex and the inner DFA to derive `Clone`, as the `specialized_weight`
  method needs to return an owned Regex. This is assuming that a) making Regex
  and DFA derive Clone is OK, and b) that cloning a Regex is cheap compared to
  recompiling from a pattern

What do you think of this? Are my assumptions correct?

If there isn't a simpler way to do prefix matching that I have completely
missed, and if you agree on the approach, I'd be happy to make PRs to
tantivy-fst and to tantivy for this.

**Comment by fulmicoton** [comment]
Everything you said is correct. No other way to compute a prefix query today.
and it would be better to compile the Regex once at the `Query` level.

Rather than `Clone` you could wrap the `Dfa` into a `Arc` and clone that. You can then have
`struct DfaRef(&'a Dfa)` implement the Automaton trait.

Looking forward to your PR :) @brainlock

**Comment by brainlock** [comment]
> Rather than Clone you could wrap the Dfa into a Arc and clone that

Good point yes, I see the value in not changing the fst crate too much.

> The part where I am not sure here, is whether the extra indirection will confuse the compiler into writing inefficient code.

With the disclaimer that I am by no means an expert in this, when I look at the generated ASM for https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f19e6c2522b7465a3a4a7429bcd4c3ec

it looks like the extra levels of indirection are indeed optimized out (when compiling in Release mode). An interesting bit is that the optimization seems to happen already in the rust compiler, while I would have thought that this would be left to LLVM (i.e.: the LLVM IR is already showing no trace of the useless bits of indirection in Release mode).

So it seems like we should be able to add the wrapper (with `#[inline]` as this has to cross the crate boundary) with a reasonable expectation of the resulting code being efficient.

Anyway, it for sure beats having to rebuild the automaton every time :-)

I just submitted #640, is that what you had in mind?

**Comment by fulmicoton** [comment]
> With the disclaimer that I am by no means an expert in this, when I look at the generated ASM for 

That's a false equivalency. The important difference with the `Arc` is that you need to follow a pointer.
I modified my comment afterwards. 

Either can you try to have an `Arc` on the Query (no need to wrap it), and pass the reference of the automaton in the `AutomatonWeight` ?

It  seems we already have `impl<'a, T: Automaton> Automaton for &'a T`.

**Comment by brainlock** [comment]
Thanks for the suggestion! I just pushed a few commits to the PR, could you have a look? I managed to reference the `Regex` directly in the `AutomatonWeight`, but to do so I had to relax a few lifetime bounds that required `'static`.

In particular, I changed the `weight` method of the `Query` trait to:
```rust
 fn weight<'a, 'b>(&'a self, searcher: &'b Searcher, scoring_enabled: bool) -> Result<Box<dyn Weight + 'a>>;
```

as (TIL 😃) by default `Box<dyn T>` has a `'static` lifetime bound. Now I tied it to the lifetime of the Query instead.

My reasoning was (correct me if I'm wrong), this should not be a problem for other users of the library, as any implementation of `Query` was required to produce a `'static` Weight, while now the bound is just `'a`.

(the code could probably be cleaned up a bit to avoid repeating `Box<dyn Weight + 'a>` all over the place, I'll look into that if you think this approach can work)

**Comment by fulmicoton** [comment]
Oops. I think we want to keep the static lifetime in weight. Can you just
pass a clone of the Arc and deref it in the call to .scorer.

Sorry my indications are super vague and inaccurate.

If you don't have time, I'll fix your PR
tomorrow

Le mer. 21 août 2019 à 21:28, Alberto Piai <notifications@github.com> a
écrit :
