### ISSUE TITLE
Duplicate methods in IndexRecordOption?

### ISSUE THREAD

**Issue by imor** [quickwit-oss/tantivy#649]
I was just browsing tantivy's source and found that method `IndexRecordOption::is_termfreq_enabled` has the exact same behaviour as `IndexRecordOption::has_freq`. Same is true for the pair `IndexRecordOption::is_position_enabled` and `IndexRecordOption::has_positions`. Also, `IndexRecordOption::has_freq` is not being used aywhere. Any reason for these duplicate methods?

**Comment by petr-tik** [comment]
Well noticed
