### ISSUE TITLE
Redesign the core/executor

### ISSUE THREAD

**Issue by petr-tik** [quickwit-oss/tantivy#652]
As mentioned in https://github.com/tantivy-search/tantivy/issues/638#issuecomment-528652433, our core/executor relies on the [scoped_pool](https://github.com/reem/rust-scoped-pool/) crate, which looks abandoned over the last 2 years. 

The Executor struct relies on a ThreadPool from scoped_pool but the comments mention Rayon's ThreadPool. 

Using development activity as an indicator, Rayon looks like a better long-term dependency to use when building a core executor than scoped_pool. 

Rayon provides [a scope method](https://doc.servo.org/rayon/struct.ThreadPool.html#method.scope) to create a scope inside a ThreadPool. However, it requires the FnOnce to exhibit the Send trait. 

This discussion [outlines pros and cons](https://github.com/rayon-rs/rayon/issues/562) of this approach and how other people suggest working around it. 

If rayon doesn't work, we can roll our own on top of Crossbeam

**Comment by fulmicoton** [comment]
I'm generally ok with this as long as it works! :)
