### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#656]
As reported by email.

Quoting

the thread is not stoped  when Index dropped .because watcher_wrapper_clone.inner._watcher is not dropped  so  code can't run Err(_e) break;

![2F0CCD18@8B556C17 5349835D](https://user-images.githubusercontent.com/1021506/65383252-a4495380-dd4d-11e9-84b7-120b98de510f.jpg)

**Comment by petr-tik** [comment]
Did they give a test case to reproduce or is it findable in our unit tests? 

I've run the following to use the leak sanitizer in LLVM, but to be honest, I don't really know where to go from here.

```bash
$ RUSTC_WRAPPER= RUSTFLAGS="-Z sanitizer=leak" cargo +nightly test --target x86_64-unknown-linux-gnu mmap_directory
   Compiling tantivy v0.11.0 (/home/petr_tik/Coding/tantivy)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 08s
     Running target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b

running 6 tests
test directory::mmap_directory::tests::test_open_non_existant_path ... ok
test directory::mmap_directory::tests::test_watch_wrapper ... ok
test directory::mmap_directory::tests::test_open_empty ... ok
test directory::mmap_directory::tests::test_cache ... ok
test directory::tests::test_mmap_directory ... ok
test directory::mmap_directory::tests::test_mmap_released ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 341 filtered out


=================================================================
==21426==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 144 byte(s) in 2 object(s) allocated from:
    #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
    #1 0x55a3a95048c4  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x2e18c4)
    #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)

Indirect leak of 104 byte(s) in 2 object(s) allocated from:
    #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
    #1 0x55a3a968542f  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x46242f)
    #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
    #1 0x55a3a96c6658  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4a3658)
    #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)

SUMMARY: LeakSanitizer: 304 byte(s) leaked in 5 allocation(s).
```

**Comment by fulmicoton** [comment]
I think I can take that one...

**Comment by qiongtubao** [comment]
> 他们是否给出了要复制的测试用例，或者在我们的单元测试中可以找到？
> 
> 我已经运行了以下命令，以在LLVM中使用泄漏清理器，但是老实说，我真的不知道从这里去哪里。
> 
> ```shell
> $ RUSTC_WRAPPER = RUSTFLAGS = “ -Z sanitizer = leak ”货物+每晚测试 --target x86_64-unknown-linux-gnu mmap_directory
>    编译tantivy v0.11.0（/ home / petr_tik / Coding / tantivy）
>     完成dev的[未优化+ debuginfo软]目标（一个或多个）在 3米08S
>      运行target / x86_64-unknown-linux-gnu / debug / deps / tantivy-d173cbeea1b61f7b
> 
> 运行6项测试
> 测试目录:: mmap_directory :: tests :: test_open_non_existant_path ... ok
>  测试目录:: mmap_directory :: tests :: test_watch_wrapper ... ok
>  测试目录:: mmap_directory :: tests :: test_open_empty ... ok
>  测试目录:: mmap_directory :: tests :: test_cache ... ok
>  测试目录:: tests :: test_mmap_directory ... ok
>  测试目录:: mmap_directory :: tests :: test_mmap_released ... ok
> 
> 测试结果：可以。6通过; 0失败; 0被忽略; 0测量; 341过滤掉
> 
> 
> ================================================== ===============
> == 21426 ==错误：LeakSanitizer：检测到内存泄漏
> 
> 144字节（一个或多个）的间接泄漏在从分配了2个（多个）对象：
>      ＃ 0 0x55a3a96ee195（/家/ petr_tik /编码/快跑/目标/ x86_64的未知-Linux的GNU /调试/ DEPS /快跑-d173cbeea1b61f7b + 0x4cb195）
>     ＃ 1 0x55a3a95048c4（/ home / petr_tik / Coding / tantivy / target / x86_64-unknown-linux-gnu / debug / deps / tantivy-d173cbeea1b61f7b + 0x2e18c4）
>     ＃ 2 0x55a3aa7c8cb7（/// home / petr_t64未知-Linux的GNU /调试/ DEPS /快跑-d173cbeea1b61f7b + 0x15a5cb7）
> 
> 104字节（一个或多个）的间接泄漏在从分配了2个（多个）对象：
>      ＃ 0 0x55a3a96ee195（/家/ petr_tik /编码/快跑/目标/ x86_64的未知-Linux的GNU /调试/ DEPS /快跑-d173cbeea1b61f7b + 0x4cb195）
>     ＃ 1 0x55a3a968542f（/ home / petr_tik / Coding / tantivy / target / x86_64-unknown-linux-gnu / debug / deps / tantivy-d173cbeea1b61f7b + 0x46242f）
>     ＃ 2 0x55a3aa7c8cb7（/ home / petr_tik / Coding / 86未知-Linux的GNU /调试/ DEPS /快跑-d173cbeea1b61f7b + 0x15a5cb7）
> 从 1个对象分配
> 的56个字节的间接泄漏来自：
>      ＃ 0 0x55a3a96ee195（/ home / petr_tik / Coding / tantivy / target / x86_64-unknown-linux-gnu / debug / deps / tantivy-d173cbeea1b61f7b + 0x4cb195）
>     ＃ 1 0x55a3a96c6658（/ home / petr_tik /编码/ tantivy / target / x86_64-unknown-linux-gnu / debug / deps / tantivy-d173cbeea1b61f7b + 0x4a3658）
>     ＃ 2 0x55a3aa7c8cb7（/ home / petr_tik64未知-Linux的GNU /调试/ DEPS /快跑-d173cbeea1b61f7b + 0x15a5cb7）
> 
> 简介：LeakSanitizer：5个分配中泄漏了 304个字节。
> ```

I sent two demos to you. Will you receive it?

**Comment by qiongtubao** [comment]
> Did they give a test case to reproduce or is it findable in our unit tests?
> 
> I've run the following to use the leak sanitizer in LLVM, but to be honest, I don't really know where to go from here.
> 
> ```shell
> $ RUSTC_WRAPPER= RUSTFLAGS="-Z sanitizer=leak" cargo +nightly test --target x86_64-unknown-linux-gnu mmap_directory
>    Compiling tantivy v0.11.0 (/home/petr_tik/Coding/tantivy)
>     Finished dev [unoptimized + debuginfo] target(s) in 3m 08s
>      Running target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b
> 
> running 6 tests
> test directory::mmap_directory::tests::test_open_non_existant_path ... ok
> test directory::mmap_directory::tests::test_watch_wrapper ... ok
> test directory::mmap_directory::tests::test_open_empty ... ok
> test directory::mmap_directory::tests::test_cache ... ok
> test directory::tests::test_mmap_directory ... ok
> test directory::mmap_directory::tests::test_mmap_released ... ok
> 
> test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 341 filtered out
> 
> 
> =================================================================
> ==21426==ERROR: LeakSanitizer: detected memory leaks
> 
> Indirect leak of 144 byte(s) in 2 object(s) allocated from:
>     #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
>     #1 0x55a3a95048c4  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x2e18c4)
>     #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)
> 
> Indirect leak of 104 byte(s) in 2 object(s) allocated from:
>     #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
>     #1 0x55a3a968542f  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x46242f)
>     #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)
> 
> Indirect leak of 56 byte(s) in 1 object(s) allocated from:
>     #0 0x55a3a96ee195  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4cb195)
>     #1 0x55a3a96c6658  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x4a3658)
>     #2 0x55a3aa7c8cb7  (/home/petr_tik/Coding/tantivy/target/x86_64-unknown-linux-gnu/debug/deps/tantivy-d173cbeea1b61f7b+0x15a5cb7)
> 
> SUMMARY: LeakSanitizer: 304 byte(s) leaked in 5 allocation(s).
> ```

I sent two demos to you by email. Will you receive it?

**Comment by fulmicoton** [comment]
@qiongtubao I did not open your demos but the original report was already pretty clear. I will address it as a hotfix or in the worst case in the next release

**Comment by qiongtubao** [comment]
@fulmicoton I am not sure if you understand the problem

**Comment by qiongtubao** [comment]
@fulmicoton  when is the next release? Because I am more eager to use

**Comment by fulmicoton** [comment]
> @fulmicoton I am not sure if you understand the problem

Can you code review the fix once I have something ready? 
Probably this week.

**Comment by fulmicoton** [comment]
> @fulmicoton when is the next release? Because I am more eager to use

I don't expect to release 0.11 too soon, but I can release a hotfix on 0.10.x if you want

**Comment by qiongtubao** [comment]
> > @fulmicoton I am not sure if you understand the problem
> 
> Can you code review the fix once I have something ready?
> Probably this week.

ok, i can

**Comment by qiongtubao** [comment]
> > @fulmicoton when is the next release? Because I am more eager to use
> 
> I don't expect to release 0.11 too soon, but I can release a hotfix on 0.10.x if you want

ok  i want it on 0.10.x

**Comment by fulmicoton** [comment]
If you have a specific emergency or important use case, please detail them here using google translate.

**Comment by fulmicoton** [comment]
@qiongtubao can you have a look at https://github.com/tantivy-search/tantivy/pull/657 ?

Note the Zsanitizer stuff does not seem solved. This is something we might need to investigate separately.

**Comment by qiongtubao** [comment]
@fulmicoton  I have seen the hotfix-656, It is the result I want ,thanks

**Comment by fulmicoton** [comment]
hotfixed in #656 and merged in master
