### ISSUE TITLE
Improve indexing memory usage

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#66]
Currently indexing memory usage is far from optimal.
- The postings are not compressed
- The hashtable is rudimentary.

Block encoding does not play well with the exponential unrolled linked list unfortunately.
We may want to switch to vint encoding everywhere.

**Comment by petr-tik** [comment]
from reading the codebase, it looks like vint has been implemented in src/common/vint.rs

Do you want to update the issue to reflect new todo items or close it completely?

**Comment by petr-tik** [comment]
@fulmicoton what do you think? Is this issue good to close?

**Comment by fulmicoton** [comment]
No. The hashtable has been part, but the vint part has not.

`vint` are used in many places. This issue is specifically to encode posting lists in the `SegmentWriter`. Right now these are not compressed at all.
