### ISSUE TITLE
directory::tests::test_mmap_directory' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by dazzag24** [quickwit-oss/tantivy#660]
Run tests with  ./run-tests.sh results in failure

```
failures:

---- directory::tests::test_mmap_directory stdout ----
thread 'directory::tests::test_mmap_directory' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/directory/tests.rs:136:9


failures:
    directory::tests::test_mmap_directory

test result: FAILED. 346 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Which version of tantivy are you using?**
If "master",  ideally give the specific sha1 revision.
cde9b78

rustc --version
rustc 1.38.0 (625451e37 2019-09-23)

**To Reproduce**

clone then build then ./run-tests.sh

**Comment by fulmicoton** [comment]
This test is quite flaky by nature unfortunately. I raised the limit of the `watch` duratio.
