### ISSUE TITLE
memory usage too high

### ISSUE THREAD

**Issue by dearsxx0918** [quickwit-oss/tantivy#666]
i'm using this crate to create my own application now.
I added 1_500_000 items to the Index continuously， the tantivy occupied more than 300MB RAM memory.
And when I shutdown the application and re-run it(this time without add document), it's only occupied lower than 40MB RAM memory, what's the problem here?
I use valgrind to profiling it, it told me it's the tantivy issue not other code.

Can someone help me to fix this?

**Comment by fulmicoton** [comment]
How do you measure memory?

The index writer itself has internal buffers.
As long as you do not drop it, these buffers are not released.

**Comment by fulmicoton** [comment]
80% this is a misunderstanding.  

I'll close this in 2 weeks if there aren't more details from @dearsxx0918

**Comment by dearsxx0918** [comment]
> How do you measure memory?
> 
> The index writer itself has internal buffers.
> As long as you do not drop it, these buffers are not released.

Hi fulmicoton,
    You mean that the internal buffers won't free as long as the writer lives?
    So if I release the writer when I do commit, it will low the memory usage?
    I will try it and come back soon.
    Thanks for you quickly response.

**Comment by fulmicoton** [comment]
@dearsxx0918 

> You mean that the internal buffers won't free as long as the writer lives?
> So if I release the writer when I do commit, it will low the memory usage?

Yes. It is not instantaneous because the buffers are dropped as indexing thread terminates, but it should happen very fast (< 1s).

You can commit several times using the same index writer, and the same buffer are reused when you do that. As long as your IndexWriter object is alive, these buffer will live.
Note that you are in charge of deciding the size of these buffers. You passed it as an argument when you created the `index_writer`. If the value you passed is somewhat close to `300_000_000` this should be a good clue that this is your problem.

**Comment by dearsxx0918** [comment]
The passed value is 200_000_000. 
I tested again, seems if do not do commit, the memory usage grows slowly.
And seems that the memory grows faster when the frequency of commit becomes bigger.
By the way, how long it takes tantivy to flush the data to the disk if I do not commit manually?
If I cannot resolve the memory issue, I will remove the commit code.
Thanks for your reply, tantivy is a good search engine, thanks for the develop team!

**Comment by fulmicoton** [comment]
> By the way, how long it takes tantivy to flush the data to the disk if I do not commit manually?

It does not work that way. You are required to commit to make your changes effective.
Batch your changes however.  If you are trying to index a fixed set of document, you can commit only at the very end.

**Comment by fulmicoton** [comment]
(I cannot help with your other questions because you haven't answered my question about how you measure memory usage...)

**Comment by fulmicoton** [comment]
Closing this because this is most likely not an actual issue but you can bring the discussion to gitter if you want!
https://gitter.im/tantivy-search/tantivy

**Comment by dearsxx0918** [comment]
OK, thanks.
