### ISSUE TITLE
Unstable ordering of TopCollector results with the same score

### ISSUE THREAD

**Issue by brainlock** [quickwit-oss/tantivy#671]
Hi!

We're using a `TopCollector` to fetch results sorted by score, and also to implement pagination in a simple way. Given an `offset` and a `limit` by the client code, we always fetch the top `offset+limit` results, then return the last `limit` ones. For example, on page 1 we fetch the top 10 documents and return them, on page 2 we fetch the top 20 documents and return the last 10 of those, etc. This is good enough for us as we don't have many pages of results in practice.

First question: is this a completely nonsensical way to do pagination? Is there an obviously better way that I've overlooked? If so, please do tell me and ignore the rest of this issue :)

Provided that this is a legitimate usage of `TopCollector`, we ran into an edge case that could potentially break pagination.

The problem is that the BinaryHeap that backs TopCollector doesn't guarantee any ordering when returning its sorted contents (`into_sorted_vec()`), for items whose ordering evaluates to Equal.

This could cause some items to never be included in a search result, if they are fetched after the max capacity is reached when querying for page 1 (for example TopCollector(10)), and if they are sorted in a position < 10 when querying for page 2 (TopCollector(20)).

In the end it really boils down to the following test not passing:

```rust

    #[test]
    fn test_top_collector_stable_ordering_for_equal_feature() {
        let mut top_collector_limit_2 = TopSegmentCollector::new(0, 2);
        top_collector_limit_2.collect(4, 3.14);
        top_collector_limit_2.collect(5, 3.14);
        top_collector_limit_2.collect(6, 3.14);

        let mut top_collector_limit_3 = TopSegmentCollector::new(0, 3);
        top_collector_limit_3.collect(4, 3.14);
        top_collector_limit_3.collect(5, 3.14);
        top_collector_limit_3.collect(6, 3.14);

        assert_eq!(
            top_collector_limit_2.harvest(),
            top_collector_limit_3.harvest()[..2].to_vec(),
        );
    }
```

In order to be able to use TopCollector to do pagination in this way, I think we need the results to be stable when items have Ordering::Equal (the specific order of course doesn't matter, it just needs to be the same when querying with different limits).

Any suggestion?

Thank you!

Alberto

----------------

# Solution 

The binary heap as used today by construction picks the first doc encountered in case of a tie.
This behavior is a side-effect of the code, and is consistent at the leaf level and when merging the different leaf so-called "fruits".

Even with a multithreading executor, fruits are merged in the same order as their respective segments, so as long as the `Searcher` is unchanged you should get consistent results.

The problem appears actually in the `harvest` code.
I suggest we simply get all of the unsorted elements out of the heap and put them into a Vec.
Then, we sort them there comparing both the score AND the DocAddress. In case of a tie, we pick the lowest `DocAddress` to stay consistent with the rest of the collector.

- [ ] Fix the harvest function to take the `DocAddress` in account in the sort.
- [ ] Document the collector to explain this policy in case of a tie.
- [ ] Add Unit tests

**Comment by brainlock** [comment]
Still under the assumption that this usage of TopCollector is legitimate, one way of fixing this without having to swap BinaryHeap with something else that tries to guarantee insertion order, would be to track the insertion order explicitly and also sort by that.

Hacky patch which makes the above test pass:

```diff
diff --git a/src/collector/top_collector.rs b/src/collector/top_collector.rs
index 9a9d2dca0..b20b1052f 100644
--- a/src/collector/top_collector.rs
+++ b/src/collector/top_collector.rs
@@ -19,6 +19,7 @@ use std::collections::BinaryHeap;
 struct ComparableDoc<T, D> {
     feature: T,
     doc: D,
+    i: usize,
 }

 impl<T: PartialOrd, D> PartialOrd for ComparableDoc<T, D> {
@@ -30,10 +31,19 @@ impl<T: PartialOrd, D> PartialOrd for ComparableDoc<T, D> {
 impl<T: PartialOrd, D> Ord for ComparableDoc<T, D> {
     #[inline]
     fn cmp(&self, other: &Self) -> Ordering {
-        other
+        let feat = other
             .feature
             .partial_cmp(&self.feature)
-            .unwrap_or_else(|| Ordering::Equal)
+            .unwrap_or_else(|| Ordering::Equal);
+
+        match feat {
+            Ordering::Equal => other
+                .i
+                .partial_cmp(&self.i)
+                .unwrap_or_else(|| Ordering::Equal)
+                .reverse(),
+            _ => feat,
+        }
     }
 }

@@ -82,11 +92,20 @@ where
         let mut top_collector = BinaryHeap::new();
         for child_fruit in children {
             for (feature, doc) in child_fruit {
+                let len = top_collector.len();
                 if top_collector.len() < self.limit {
-                    top_collector.push(ComparableDoc { feature, doc });
+                    top_collector.push(ComparableDoc {
+                        feature,
+                        doc,
+                        i: len,
+                    });
                 } else if let Some(mut head) = top_collector.peek_mut() {
                     if head.feature < feature {
-                        *head = ComparableDoc { feature, doc };
+                        *head = ComparableDoc {
+                            feature,
+                            doc,
+                            i: len,
+                        };
                     }
                 }
             }
@@ -170,7 +189,11 @@ impl<T: PartialOrd + Clone> TopSegmentCollector<T> {
         } else {
             // we have not reached capacity yet, so we can just push the
             // element.
-            self.heap.push(ComparableDoc { feature, doc });
+            self.heap.push(ComparableDoc {
+                feature,
+                doc,
+                i: self.heap.len(),
+            });
         }
     }
 }
```

I don't like that this is making everyone pay an extra cost, though. Apart from the pagination use case, the ordering of items with Ordering::Equal is completely irrelevant.

So I would rather implement a separate collector for this.

**Comment by fulmicoton** [comment]
Your analysis is entirely correct. TopCollector is the right way to do pagination and the current implicit sort is not stable (because the number of elements we put in the `BinaryHeap` might change) so I tagged the issue as `bug`. Thanks for the report

I however do not actually understand your solution. I edited the ticket with a simple, CPU inexpensive solution.

Do you want to pick this ticket?

**Comment by brainlock** [comment]
Ah, I see, thanks for the nice solution :)

> picks the first doc encountered in case of a tie.

If I understand this correctly, the docs are added in ascending DocAddress order?

> Do you want to pick this ticket?

Yes, I can work on this

**Comment by fulmicoton** [comment]
> If I understand this correctly, the docs are added in ascending DocAddress order?

This is correct yes.

**Comment by gembin** [comment]
Regarding the pagination, is it possible to skip returning the docs for the previous page?
For example, let's say limit=10,  skip the first 10 docs on page 2, and only returns from 11th-20th docs.

**Comment by brainlock** [comment]
Hi @gembin, 

since the TopDocs collector returns an iterator over DocAddresses, you can skip-limit that iterator to only fetch the documents for the specific page, for example with code like 

```rust
for address in doc_addresses.into_iter().skip(offset).take(limit) {
    let doc = searcher.doc(address)?;
    ...
}
```
(assuming you're in a function that returns a Result, and can thus use `?` to propagate the error)

I hope this helps. In general, could you avoid using closed issues to ask questions? A better place for this would be [the gitter chat](https://gitter.im/tantivy-search/tantivy). Thanks!

**Comment by gembin** [comment]
Thanks a lot! That's what I did. Just wondering if there any better way to do.
Sorry for using the closed issue.
