### ISSUE TITLE
Support async query

### ISSUE THREAD

**Issue by dearsxx0918** [quickwit-oss/tantivy#678]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I use tantivy  to query something and make the result as a Stream then return to the caller.
It's also has some memory issue on devices with limited memory, the searcher used now will allocate a big vector if the search result is large(say in my project, will get 5_000_000 items sometime). If we use a bounded channel and wait the client to consume the sent items, we will improve the memory usage and also improve the system efficiency.

**Describe the solution you'd like**
I think we may have some search function like:
```
pub fn search<C: Collector>(&self, query: dyn Query, collector: &C>) -> impl Stream<Item=C::Fruit, Error=TantivyError>;
```

**[Optional] describe alternatives you've considered**
This would be help for web service since we can push something to front-end through http2 as a stream, so web users won't feel any delay.
And for other terminal users, this would helpful for them to improve time delay.

I think it's a good feature as rust is powerful in async programming than other languages.

**Comment by real-felix** [comment]
Hi, is there any news about that? I'm considering using tantivy in a web server, and I'm not sure about how to do that with a synchronous database.

**Comment by fulmicoton** [comment]
@dearsxx0918 apologies! Your issue was reported a long time ago yet I only recently spotted it.

It is possible to stream the documents matching a search query and push them to a flume channel to get the same functionality.
(The API offered in the ticket does not really makes sense however)

**Comment by fulmicoton** [comment]
@Boiethios I am not sure I understand the problem? If you use tokio for instance, performing your search in a spawn_blocking task should be correct.

**Comment by real-felix** [comment]
> @Boiethios I am not sure I understand the problem? If you use tokio for instance, performing your search in a spawn_blocking task should be correct.

When thousands of requests are done at the same time, maybe it could slow the server down.

I don't know which percent it is, but I guess that some time is spent in IO when reading/writing in the DB files. That can be done truly asynchronously.

**Comment by fulmicoton** [comment]
> When thousands of requests are done at the same time, maybe it could slow the server down.

On most use case, tantivy is cpu bounded.
If you have this kind of traffic, you should make sure you have enough RAM that the disk is very rarely hit.
