### ISSUE TITLE
Fail to compile on windows

### ISSUE THREAD

**Issue by vchugreev** [quickwit-oss/tantivy#69]
D:\Projects>git clone git@github.com:tantivy-search/tantivy.git
Cloning into 'tantivy'...
Enter passphrase for key '/c/Users/chvl/.ssh/id_rsa':
remote: Counting objects: 14425, done.
remote: Compressing objects: 100% (4206/4206), done.
remote: Total 14425 (delta 3984), reused 186 (delta 186), pack-reused 10013
Receiving objects: 100% (14425/14425), 6.10 MiB | 245.00 KiB/s, done.
Resolving deltas: 100% (12093/12093), done.
Checking connectivity... done.

D:\Projects>cd tantivy

D:\Projects\tantivy>git submodule init
Submodule 'cpp/simdcomp' (git@github.com:lemire/simdcomp.git) registered for path 'cpp/simdcomp'

D:\Projects\tantivy>git submodule update
Cloning into 'cpp/simdcomp'...
Enter passphrase for key '/c/Users/chvl/.ssh/id_rsa':
remote: Counting objects: 788, done.
remote: Total 788 (delta 0), reused 0 (delta 0), pack-reused 788
Receiving objects: 100% (788/788), 423.23 KiB | 163.00 KiB/s, done.
Resolving deltas: 100% (501/501), done.
Checking connectivity... done.
Submodule path 'cpp/simdcomp': checked out '0dca28668f1fb6d343dc3c62fa7750a00f1d7201'

D:\Projects\tantivy>cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling winapi v0.2.8
   Compiling regex-syntax v0.3.9
   Compiling byteorder v0.5.3
   Compiling itertools v0.4.19
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling ascii v0.7.1
   Compiling lazy_static v0.1.16
   Compiling libc v0.2.19
   Compiling combine v2.0.0
   Compiling rand v0.3.15
   Compiling chan v0.1.18
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.3
   Compiling rustc-serialize v0.3.22
   Compiling getopts v0.2.14
   Compiling num-traits v0.1.36
   Compiling log v0.3.6
   Compiling pulldown-cmark v0.0.3
   Compiling num-integer v0.1.32
   Compiling num-iter v0.1.32
   Compiling byteorder v0.4.2
   Compiling semver v0.1.20
   Compiling tempdir v0.3.5
   Compiling rustc_version v0.1.7
   Compiling skeptic v0.6.1
   Compiling tempfile v2.1.4
   Compiling num_cpus v0.2.13
   Compiling utf8-ranges v0.1.3
   Compiling crossbeam v0.2.10
   Compiling gcc v0.3.41
   Compiling num-bigint v0.1.35
   Compiling uuid v0.1.18
   Compiling num-complex v0.1.35
   Compiling num-rational v0.1.35
   Compiling lz4 v1.20.0
   Compiling tantivy v0.2.0 (file:///D:/Projects/tantivy)
   Compiling num v0.1.36
   Compiling lz4-sys v1.0.1+1.7.3
   Compiling serde v0.6.15
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `tantivy v0.2.0 (file:///D:/Projects/tantivy)`
process didn't exit successfully: `D:\Projects\tantivy\target\debug\build\tantivy-dae7d4256bf9a2c4\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to make simdcomp: Не удается найти указанный файл. (os error 2)', build.rs:11
note: Run with `RUST_BACKTRACE=1` for a backtrace.

***

D:\Projects\tantivy>cargo -V
cargo 0.15.0-nightly (298a012 2016-12-20)

D:\Projects\tantivy>rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)

Help me please

**Comment by fulmicoton** [comment]
You apparently have trouble compiling the external module in charge of simd integer compression.
I assumes this is because you do not have gcc on your system.

The good news is that before trying to install gcc, you can test tantivy without simd compression by compiling using the following command.

     cargo build --no-default-features

**Comment by vchugreev** [comment]
D:\Projects\tantivy>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-6.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 6.2.0 (Rev2, Built by MSYS2 project)

**Comment by vchugreev** [comment]
D:\Projects\tantivy>cargo build --no-default-features
   Compiling tantivy v0.2.0 (file:///D:/Projects/tantivy)
   Compiling lz4-sys v1.0.1+1.7.3
   Compiling kernel32-sys v0.2.2
   Compiling bincode v0.4.1
   Compiling time v0.1.35
   Compiling fs2 v0.2.5
   Compiling lz4 v1.20.0
   Compiling atomicwrites v0.0.14
   Compiling memmap v0.4.0
   Compiling tempfile v2.1.4
   Compiling memmap v0.2.3
   Compiling thread-id v2.0.0
   Compiling fst v0.1.35
   Compiling thread_local v0.2.7
   Compiling regex v0.1.80
error[E0554]: #[feature] may not be used on the stable release channel
 --> src\lib.rs:5:1
  |
5 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> src\lib.rs:6:1
  |
6 | #![feature(optin_builtin_traits)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> src\lib.rs:7:1
  |
7 | #![feature(conservative_impl_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> src\lib.rs:11:1
   |
11 | #![feature(conservative_impl_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `tantivy`.

**Comment by fulmicoton** [comment]
You need rustc nightly to compile tantivy.

    rustup install nightly

**Comment by vchugreev** [comment]
I'm sorry, I did not pay attention to:

> Tantivy requires Rust Nightly...

Thanks for the help! I will try.

**Comment by vchugreev** [comment]
Happened:
cargo build --no-default-features
(cargo build not passed)

I put Nightly Rust 64-bit installer for Windows, there is a link to it:
https://doc.rust-lang.org/book/nightly-rust.html

P.S. Compiled by Rust nightly 1.16 (GNU 64-bit) Shell

**Comment by vchugreev** [comment]
**fulmicoton** 
Hopefully then it will be able to compile a stable version?! Now all this is not very convenient.

**Comment by fulmicoton** [comment]
I didn't quite understand. Have you managed to compile tantivy? If not could you send me the error message you got?

Tantivy will eventually compile on stable rust yet. It is however low priority for the moment.

**Comment by vchugreev** [comment]
> Have you managed to compile tantivy?

Yes => cargo build --no-default-features
No => cargo build 

D:\Projects\tantivy>cargo build
   Compiling num-traits v0.1.36
   Compiling lazy_static v0.1.16
   Compiling winapi v0.2.8
   Compiling byteorder v0.4.2
   Compiling semver v0.1.20
   Compiling winapi-build v0.1.1
   Compiling rustc_version v0.1.7
   Compiling num-integer v0.1.32
   Compiling log v0.3.6
   Compiling num-iter v0.1.32
   Compiling libc v0.2.19
   Compiling rustc-serialize v0.3.22
   Compiling num_cpus v0.2.13
   Compiling memchr v0.1.11
   Compiling kernel32-sys v0.2.2
   Compiling rand v0.3.15
   Compiling gcc v0.3.41
   Compiling chan v0.1.18
   Compiling lz4-sys v1.0.1+1.7.3
   Compiling regex-syntax v0.3.9
   Compiling ascii v0.7.1
   Compiling aho-corasick v0.5.3
   Compiling getopts v0.2.14
   Compiling itertools v0.4.19
   Compiling byteorder v0.5.3
   Compiling combine v2.0.0
   Compiling pulldown-cmark v0.0.3
   Compiling num-complex v0.1.35
   Compiling utf8-ranges v0.1.3
   Compiling num-bigint v0.1.35
   Compiling uuid v0.1.18
   Compiling tempdir v0.3.5
   Compiling tantivy v0.2.0 (file:///D:/Projects/tantivy)
   Compiling skeptic v0.6.1
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `tantivy v0.2.0 (file:///D:/Projects/tantivy)`
process didn't exit successfully: `D:\Projects\tantivy\target\debug\build\tantivy-de2099cd7c3a27b2\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to make simdcomp: Не удается найти указанный файл. (os error 2)', build.rs:11
note: Run with `RUST_BACKTRACE=1` for a backtrace.

> Tantivy will eventually compile on stable rust yet. It is however low priority for the moment.

It's a pity. How to work with the library? This is a rhetorical question :). I understand that it is still in the process of development (version 0.2.0 as it hints at this). In any case - it's a great project! 

P.S. Sorry for bad english, it's not my native language.

**Comment by fulmicoton** [comment]
People usually use rustup to manage their rust toolchain.

Tantivy is still very very young. You should really not use it unless you have a very specific use case that prevents you from using lucene.

**Comment by vchugreev** [comment]
I'm still a beginner, I find it difficult to switch from nightly to stable. But I will gradually research the infrastructure. 
Rust - a classy language, after all my torment with CMake (in C ++), cargo - just a fairy tale!
I wish you success and thank you!

**Comment by fulmicoton** [comment]
You should really checkout rustup. It will make your life very easy. 
https://github.com/rust-lang-nursery/rustup.rs#working-with-rust-on-windows

I totally understand what you are saying about CMake :)

**Comment by vchugreev** [comment]
This problem persists for tantivy-cli: https://github.com/tantivy-search/tantivy-cli/issues/9
P.S. Thanks for the information about rustup!
