### ISSUE TITLE
Is there any doc about the file format?

### ISSUE THREAD

**Issue by marsqing** [quickwit-oss/tantivy#690]
Tantivy is great. We're developing a ES-like(much simpler and specific to our needs) system based on tantivy. Currently, we're doing some optimization and we need some info about the format of various tantivy files like .idx and .term. Is there any doc available or should we read some source code? Thanks!

**Comment by fulmicoton** [comment]
I'm glad you like tantivy!

I'm afraid there are no proper documentation of the .idx and the .term format.
If you go through the trouble of reverse engineering it, I would really appreciate if you could share the documentation.

Did you need to expose some new API?

**Comment by fulmicoton** [comment]
@marsqing Also please let us know if your project progresses, your findings and share if you end up having something in production!

**Comment by shikhar** [comment]
Closing in favour of #981
