### ISSUE TITLE
Out of bounds slice access

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#692]
I've seen this a couple of times:

```
thread 'segment_updater0' panicked at 'slice index starts at 18446744073633252107 but ends at 27', src/libcore/slice/mod.rs:2591:5
stack backtrace:
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2591
  15: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2766
  16: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2568
  17: tantivy::directory::footer::Footer::from_bytes
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/directory/footer.rs:79
  18: tantivy::directory::footer::Footer::extract_footer
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/directory/footer.rs:85
  19: <tantivy::directory::managed_directory::ManagedDirectory as tantivy::directory::directory::Directory>::open_read
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/directory/managed_directory.rs:250
  20: tantivy::core::segment::Segment::open_read
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/core/segment.rs:80
  21: tantivy::core::segment_reader::SegmentReader::open
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/core/segment_reader.rs:149
  22: tantivy::indexer::index_writer::advance_deletes
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/indexer/index_writer.rs:142
  23: tantivy::indexer::segment_updater::SegmentUpdater::purge_deletes
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/indexer/segment_updater.rs:233
  24: tantivy::indexer::segment_updater::SegmentUpdater::commit::{{closure}}
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/indexer/segment_updater.rs:298
  25: tantivy::indexer::segment_updater::SegmentUpdater::run_async::{{closure}}
             at /root/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/6a8a855/src/indexer/segment_updater.rs:199
  26: futures::future::lazy::Lazy<F,R>::get
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/lazy.rs:64
  27: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/lazy.rs:82
  28: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/catch_unwind.rs:49
  29: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/catch_unwind.rs:32 
```

It doesn't always happen. Maybe 1 per 1000 docs indexed.

**Which version of tantivy are you using?**

79f64ac2f40dd7ad42ae8906c0e20901208c0aae

**To Reproduce**

My indexing code is here:

https://gitlab.com/crates.rs/crates.rs/blob/master/search_index/src/lib_search_index.rs#L172

**Comment by petr-tik** [comment]
Hey, great to know that lib.rs uses the master branch of tantivy.

> With great power comes great responsibility. 

I am going to try remote debugging from your stacktrace, so I might assume something bad.  

Looking at your code, it looks like you first call delete_term before adding a document again. 

delete_term requires a `commit()` to persist the result of your delete_term call.
https://tantivy-search.github.io/tantivy/tantivy/struct.IndexWriter.html#method.delete_term

Can you try add a commit call right after the delete_term call. Commit returns a result, which you should handle, but you can unwrap it or if let match into logs. 

```rust
  let pkey = Term::from_field_text(self.index.origin_pkey, &origin);
  self.writer.delete_term(pkey);
  self.writer.commit().unwrap();
```

**Comment by fulmicoton** [comment]
@petr-tik The pattern used by @kornelski is correct and it is the recommended way to update a doc.

**Comment by petr-tik** [comment]
I am reading the stacktrace more carefully now and it doesn't look that the code is at in his method is that relevant. Thanks for noticing that too.

AFAICT, we are erroneously slicing with a huge `.start` attribute. The value "18446744073633252107" suggests it might be garbage data that somehow ended up as a start parameter

**Comment by fulmicoton** [comment]
@kornelski master introduced a change in the index format. Can you confirm that you are working with an index that has NOT been built with an older version of tantivy?

**Comment by petr-tik** [comment]
Looking at other crates in the workspace, the reindex crate uses the add method from 
https://gitlab.com/crates.rs/crates.rs/blob/master/search_index/src/lib_search_index.rs#L172

to reindex crates in the method below

https://gitlab.com/crates.rs/crates.rs/blob/master/reindex/src/bin/reindex_crates.rs#L144

**Comment by kornelski** [comment]
Thank you for checking this. My index *was* from an older version of Tantivy.

I've started a new index from scratch, and it seems to work now.

**Comment by fulmicoton** [comment]
FYI the introduction of footer is precisely so you don't have to fight a cryptic message when that happens.
