### ISSUE TITLE
Embed version in the index, reject incompatible versions

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#695]
It seems that using a too-old version of the index can cause breakage (#692). 

It would be nice if Tantivy tagged the index with the version it's been created with, and refused to load or update an incompatible index.

**Comment by fulmicoton** [comment]
That's the point of the introduction of footer... the feature that caused the breakage in #692. It should gieve you a nice error message in the future..

**Comment by petr-tik** [comment]
@kornelski the reason for closing your ticket is it's a duplicate of #662 that I started working on today.

**Comment by kornelski** [comment]
Great, thanks :D

**Comment by petr-tik** [comment]
Forgot to ask - please don't delete the directory with the old index that was causing the original crash. 

It would be great to have some real world examples of indexes that we know would benefit from this change. Thanks

**Comment by kornelski** [comment]
If you want to inspect the wreck, here it is: https://lib.rs/data/tantivy2.tar.xz

**Comment by fulmicoton** [comment]
@petr-tik the current crashing index is not entirely relevant here.

It is very easy to build one. Also the footer will mostly be helpful for later compatibility issues.

There is a non null chance that we cannot detect the problem with an existing index... And we will not be able to get the actual version of the index even if we are good enough to return an error it will not include a great error message.

**Comment by petr-tik** [comment]
Do you recommend not including the index version found in the footer at all? 

I thought it would be most help for debugging to have index_version_supported_by_library and index_version_on_disk
