### ISSUE TITLE
tantivy needs too many threads when indexing

### ISSUE THREAD

**Issue by vsop-479** [quickwit-oss/tantivy#705]
Tantivy needs a thread pool to handle documents which  added by user's add_document thread for each index writer ( not user's add_document thread direactly like lucene) .

I think it will needs a lot of threads when indexing multiple indices, which will cause high load averge.

**Comment by fulmicoton** [comment]
This is a non-trivial change. (As opposed to introducing an external thread pool for search for instance). Can you share your use case?

Especially the number of indices you have.
