### ISSUE TITLE
Add a maximum segment size for merge policies, Deletes

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#706]
This ticket is about fixing the heuristic of the `LogMergePolicy`.
There is actually two different problems in this ticket.

# Problem 1

The relative benefit of merging segments diminishes as the segment gets bigger and bigger.
We should add a configurable `max_segment_size` expressed in number of documents to limit the size of two segments that can be considered for merge.

# Problem 2

The current merge policy only takes in account the size (in number of documents) to merge two segments. We do not take in account the number of deleted documents.

This can lead to the following problem. A very large segment is created, and the index consists in 
this large segment and a lot of small segments.

Until the small segments get merged up to the point when `min_merge_size` large segment are created, the large segment never gets merged.
This can take a very long time (e.g. months). In the meanwhile, deletes also happen and this mammoth segment may actually contain a very large ratio of deletes.

The heuristic should be changed to take in account the ratio of deleted file to avoid this problem.

**Comment by petr-tik** [comment]
Seems like a combination of 
https://github.com/tantivy-search/tantivy/issues/115
and
https://github.com/tantivy-search/tantivy/issues/615

so probably best tag them

**Comment by fulmicoton** [comment]
Oh thanks @petr-tik ! I tried to find #615 and did not manage to get it!
