### ISSUE TITLE
Unit Test Failing directory::tests

### ISSUE THREAD

**Issue by stormasm** [quickwit-oss/tantivy#708]
Here is the sha:
https://github.com/tantivy-search/tantivy/commit/1868fc1e2cfadfa52bd5c10ef0b1ff46310104c4

failures:

---- directory::tests::test_ram_directory stdout ----
thread 'directory::tests::test_ram_directory' panicked at 'assertion failed: lock_a_res.is_err()', src/directory/tests.rs:191:9

---- directory::tests::test_mmap_directory stdout ----
thread 'directory::tests::test_mmap_directory' panicked at 'assertion failed: lock_a_res.is_err()', src/directory/tests.rs:191:9

failures:
    directory::tests::test_mmap_directory
    directory::tests::test_ram_directory

test result: FAILED. 354 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out

**Comment by fulmicoton** [comment]
Thanks for the report. 

There was a race condition in the unit test. I think I have a fix in PR #709.

**Comment by stormasm** [comment]
Thanks for fixing it so quickly,...

I checked out your branch and ran the tests 
and they now all pass....

**Comment by fulmicoton** [comment]
@stormasm Awesome ! Thanks for checking.

**Comment by stormasm** [comment]
no problem !
Thank you....
