### ISSUE TITLE
Add CI for windows using appveyor.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#71]
Add CI for windows using appveyor.

May want to check out https://github.com/japaric/trust/ to do that in a nicer way

**Comment by KodrAus** [comment]
I'm looking to get into contributing to `tantivy`, and wanted to check out `trust` too so would be happy to pick this one up if you don't have a tight deadline :)

**Comment by fulmicoton** [comment]
@KodrAus That would be very helpful!

**Comment by KodrAus** [comment]
So I've started taking a look at this and looks like Windows builds fine with GNU and MSVC toolchains so long as we're not trying to build `simdcomp`, I haven't been able to get that to compile on Windows yet, which isn't a big surprise, it doesn't look like it's really supported. Maybe my mingw-foo is just weak, but it'll be pretty easy to build an AppVeyor build script that excludes it.

I'm still checking out `trust`, so far it looks like the main benefit is automatic packaging of binary releases for major platforms, which might not be a thing unless you plan to release binaries in the future. It looks like it makes building for non-x86 architectures easier too though, but that also rules out `simdcomp`.

Have you had any success building `tantivy` with SIMD for Windows @fulmicoton? I'll go ahead and write an AppVeyor script that excludes SIMD and think more about how it might be supported.

**Comment by fulmicoton** [comment]
As discussed on gitter, I think it is probably safer to just not support windows.

**Comment by KodrAus** [comment]
We should probably note this in the readme, since it does actually build on Windows. It just kind of doesn't work.

**Comment by fulmicoton** [comment]
Absolutely. I will do that today... Or if you send me a pull request ill be happy to merge it.

**Comment by fulmicoton** [comment]
Just added that in README.md

**Comment by KodrAus** [comment]
Cool, so I guess this issue isn't relevant anymore? I opened a specific issue in `tantivy-cli` for integrating `trust` there.

**Comment by fulmicoton** [comment]
We'll eventually want to support windows in a very distant future. In the meanwhile, closing this as won't fix.
@KodrAus  thanks for investigating, and creating the other issue.

**Comment by fulmicoton** [comment]
Was fixed by @KodrAus  in #108
