### ISSUE TITLE
Purge_deletes in commit took too long when there are a lot of segments in the index path

### ISSUE THREAD

**Issue by vsop-479** [quickwit-oss/tantivy#710]
There are about 1700 segments in my index path.
Purge_deletes in commit(segment_updater.purge_deletes) took too long every time.
It took about 1 hour in the first time(program restart). After that, it took about 10s and became longer every time(4 minute after hours).
Maybe the purge_deletes operation can be optimized.

**Comment by fulmicoton** [comment]
The main problem is the fact you ended up with 1700 segments to begin with.

I'm working on adding backpressure to make indexing slower when merge threads cannot keep up

**Comment by fulmicoton** [comment]
Can you share code that would mimick your use case so that I can ensure tantivy behaves correcltly on it?

**Comment by vsop-479** [comment]
I made some modification on tantivy to control the number of merging threads:
Skip the segment with too many documents when computing merge candidates.
Retrun in consider merger options when the number of merging threads bigger than 5.

I limit the merging thread without making indexing slower, so it ended up with too many segments.

If an index still has a lot of segments after merging(skip big segment), will purge_deletes operation take a long time after restart?

**Comment by fulmicoton** [comment]
If I recall correctly `purge_deletes` only happens on commit. It is independent from merges isn't it?

Having a lot of segments will make it very slow yes. Having a lot of segments will make searching in general very slow.

**Comment by vsop-479** [comment]
@fulmicoton 
I think advance_deletes(method in index_writer.rs) should return directly when the segment entry's delete cursor is none,  just like apply_deletes(method in index_writer.rs) does.

**Comment by fulmicoton** [comment]
Yes that should be ok.
