### ISSUE TITLE
It's extremely hard to search CJK text because of how tokenization is handled for queries

### ISSUE THREAD

**Issue by jrothenberg** [quickwit-oss/tantivy#718]
QueryParser seems to tokenize queries as English before it gets to the stage where the tokenizers for individual fields are considered, so even if you have a field using another tokenizer, QueryParser basically won't work at all for CJK text.

To get searching a field indexed with TinySegmenterTokenizer working properly, I had to manually tokenize the text and loop over the TokenStream to build a BooleanQuery.

**Comment by fulmicoton** [comment]
That's most likely a bug. The tokenizer is supposed to be applied on the text that is emitted by the query parser.

**Comment by jrothenberg** [comment]
I'm not sure I'm understanding the QueryParser code, so maybe I misunderstood what is going on, but I'll see if I can make a minimal example program.

**Comment by fulmicoton** [comment]
I think you misunderstood my comment. That's most probably a bug on tantivy side.

**Comment by jrothenberg** [comment]
Sorry, please ignore this for now. I don't think the problem is what I thought it is and I'm not completely sure whether it's actually a bug or not.

**Comment by jrothenberg** [comment]
Ah, I think I understand the problem I was having now. To be certain, am I correct in understanding that QueryParser will use PhraseQuery by default if a single term contains multiple tokens and PhraseQuery will require the exact sequence of tokens to match?

I think the problem I'm having is just that since the places where TinySegmenterTokenizer breaks tokens are somewhat arbitrary, if I search for something that starts or ends in the middle of what TinySegmenterTokenizer considered to be a token in the original document, the document won't match with a PhraseQuery even if my search was an actual substring of the document.

I think kuromoji (which lucene/elastic search use for Japanese) addresses this by "decompounding" as described here https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-kuromoji-tokenizer.html where it breaks down words in multiple ways, but that probably makes things much more complicated.

**Comment by fulmicoton** [comment]
> I correct in understanding that QueryParser will use PhraseQuery by default if a single term contains multiple tokens 

If it does this this is a bug.

> I think the problem I'm having is just that since the places where TinySegmenterTokenizer breaks tokens are somewhat arbitrary, if I search for something that starts or ends in the middle of what TinySegmenterTokenizer considered to be a token in the original document, the document won't match with a PhraseQuery even if my search was an actual substring of the document.
> 
> I think kuromoji (which lucene/elastic search use for Japanese) addresses this by "decompounding" as described here https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-kuromoji-tokenizer.html where it breaks down words in multiple ways, but that probably makes things much more complicated.

Can you a concrete example with your query, what's in your doc, what TinySegmenter gives you, and whether you expected your doc to match or not. (I can speak a bit of Japanese)

**Comment by jrothenberg** [comment]
Here's one example: It seems like if I store a document with the text "2003年の議員引退後も憲法改正" in a field indexed with TinySegmenterTokenizer and I search for "引退後" I don't get the document back.

It's probably not a bug in tantivy at all but just a result of TinySegmenterTokenizer not being reliable about how it tokenizes words, though.

**Comment by fulmicoton** [comment]
If it works like the JS tiny segment yes that's the problem.

http://chasen.org/~taku/software/TinySegmenter/
引退後 alone is a single token
in 2003年の議員引退後も憲法改正 it is split into 2 | 0 | 0 | 3 | 年 | の | 議員 | 引退 | 後 | も | 憲法 | 改正

**Comment by fulmicoton** [comment]
Someone made a port of sudachi in rust recently.
I also have a port of kuromoji if your use case is important.

Finally you can use an external tokenizer and use a pretokenized text.

**Comment by jrothenberg** [comment]
Thanks. I'm pretokenizing text with kuromoji-rs now and it looks like it's working sufficiently well for my purposes.
