### ISSUE TITLE
Add Lucene++ to the benchmark page

### ISSUE THREAD

**Issue by amustafa** [quickwit-oss/tantivy#728]
[Lucene++](https://github.com/luceneplusplus/LucenePlusPlus) is a C++ port of Lucene. It would be interesting to see how that library's performance along the benchmarks compares to Tantivy as well.

**Comment by fulmicoton** [comment]
The search benchmark is a different repo. 
https://github.com/tantivy-search/search-benchmark-game

If you want to work on this, please open a new ticket in this repo and I'll be waiting for your pull request :)
