### ISSUE TITLE
Regression on 0.11 - Missing updated documents (deleted + re-added)

### ISSUE THREAD

**Issue by appaquet** [quickwit-oss/tantivy#729]
I'm encountering a regression from 0.10 to 0.11. When overwriting documents by using `delete_term` and then `add_document`, Tantivy seems to trigger a garbage collection at some points that renders some documents from a first batch to be deleted and not re-indexed.

Here's a gist that is working on 0.10, but not working 0.11: https://gist.github.com/appaquet/a0645e9e43b49291bc69c448b7d5b9ed

As you can see, it seems to only trigger the issue when having a first batch of insert and then updating documents 1 by 1 with a commit on every update. At some point around the 5th update, the index only returns part of the expected results.

**Comment by fulmicoton** [comment]
I was able to reproduce. Thank you very much for the great report. I will fix that as soon as possible

**Comment by fulmicoton** [comment]
Fixed and released in 0.11.1. Yanking 0.11.0

**Comment by appaquet** [comment]
0.11.1 fixed the issue on my side too. Thanks !
