### ISSUE TITLE
Can't impl Directory outsite the crate

### ISSUE THREAD

**Issue by darkskygit** [quickwit-oss/tantivy#731]
**Describe the bug**
Directory neet impl watch()
but return value WatchHandle cannot alloc outsite the crate
because the structure parameters are private and there is no new() function

**Which version of tantivy are you using?**
0.11.1

**Comment by fulmicoton** [comment]
Thanks for the report. I think it is fair to call that a bug, and it will be addressed this week in v0.11.2.

**Comment by fulmicoton** [comment]
published in 0.11.2
