### ISSUE TITLE
Range queries

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#74]
Spawned from the discussion in #42 

We want to have range queries. This will probably require indexing a document with a value `v: u64`, we probably want to have the document suscribe to many different postings list that
expresses different prefixes of v.

The list of such prefixes can be either (like in Solr so I assume this is the same in Lucene) be based on a base decomposition of the int, which requires a base/precision configuration from the user.

Another way might be to index most of the prefixes where there is a branch in the fst construction. This would probably require modifying the fst crate to expose this information.

**Comment by manuel-woelker** [comment]
Here is another interesting post from Lucene:
https://www.elastic.co/blog/lucene-points-6.0

Lucene now uses KD-Trees for numeric values. So such a tree is traversed rather than an FST. This seems to allow a more compact index representation as well as better query performance.

**Comment by fulmicoton** [comment]
I really need to study this a bit more...

**Comment by naturallymitchell** [comment]
See also [JMESPath's Index Expressions](http://jmespath.org/specification.html#index-expressions), available in [jmespath.rs](https://github.com/mtdowling/jmespath.rs).

**Comment by fulmicoton** [comment]
A simple range query has been merge in master
