### ISSUE TITLE
Cannot cross compile for ARMv5TE

### ISSUE THREAD

**Issue by davide-romanini** [quickwit-oss/tantivy#743]
I'm trying to compile the basic tantivy example for armv5te arch, and found the following error:

```
 $ CC=arm-linux-gnueabi-gcc-7 cargo build --target=armv5te-unknown-linux-musleabi
...
   Compiling tantivy v0.11.3
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> /home/davide/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.11.3/src/indexer/stamper.rs:3:25
  |
3 | use std::sync::atomic::{AtomicU64, Ordering};
  |                         ^^^^^^^^^
  |                         |
  |                         no `AtomicU64` in `sync::atomic`
  |                         help: a similar name exists in the module: `AtomicU32`
```

According to [this](https://doc.rust-lang.org/std/sync/atomic/#portability), atomics should work on linux armv5te builds (using kernel helpers), but apparently only AtomicU32 is available.

This issue actually prevents me to use tantivy on my armv5te based NAS.
Maybe stamper could be implemented in a more portable way, leveraging the max atomic size of the target platform: this will obviously limit its capabilities, but it should be fine to run.

**Comment by fulmicoton** [comment]
Can you confirm you are using a recent version of rustc?

**Comment by fulmicoton** [comment]
I'm ok with adding a mutex based fixture using conditional compilation.

Can you implement such a solution , test that solves your problem and report here?

**Comment by davide-romanini** [comment]
I created a PR. Solves at least for me, but needs improvements, I'm a total rust beginner :-)

**Comment by petr-tik** [comment]
Looks like we can close this
