### ISSUE TITLE
Dependency Versions

### ISSUE THREAD

**Issue by Ameobea** [quickwit-oss/tantivy#75]
I've noticed that many of the dependencies included for this project are using very outdated versions (`memmap` using version 0.2 when 0.5.0 is available, `uuid` using 0.1 when 0.4 is available, `lz4` using 1.13 when 1.18.131 is available, etc.).  Is there any reason for this, or has it just not been updated for a long time?

There are likely bugfixes, performance boosts, and feature additions that have been added that it may be good for tantivy to take advantage of.  If bumping those deps to the latest version is something you'd be OK with, I'd be happy to submit a PR to make it happen!

**Comment by fulmicoton** [comment]
Sure go ahead.

**Comment by Ameobea** [comment]
Implemented in e0ba699c1622246e6d44268a500577179e90772a

**Comment by fulmicoton** [comment]
Had to bring memmap back to 0.4.0 for compatibility with fst.
