### ISSUE TITLE
Invalid footer causes allocation of 10304235947423694895 bytes

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#758]
I've probably corrupted my tantivy index. The problem is, something in tantivy apparently reads the invalid data and interprets it as a size of 0x8F0000000000002F bytes, which kills Rust due to OOM.

If I panic in the allocator, it points to this:

 17:        0x10ef6aede - alloc::vec::from_elem::h11fa0e24feb5a043
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:1694
  18:        0x10e066cf0 - tantivy::directory::footer::Footer::is_compatible::hcb98368b58f134ff
  19:        0x10e066027 - <tantivy::directory::footer::Footer as tantivy::common::serialize::BinarySerializable>::serialize::{{closure}}::hc468bd8bbbf2ea7e
  20:        0x10e0666b7 - tantivy::directory::footer::Footer::extract_footer::h705724ca7e50111b
  21:        0x10e01d475 - tantivy::directory::managed_directory::ManagedDirectory::register_file_as_managed::he8a7a421685c9b74
  22:        0x10e02760f - tantivy::core::segment::create_segment::haab4a621d2ecc0f3
  23:        0x10e09831e - tantivy::core::segment_reader::SegmentReader::open::hab6eeecf581548a5
                               at .cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/92dac7a/src/core/segment_reader.rs:149

I'm using opt-level=1, so the backtrace may not be entirely precise. It's from tantivy 92dac7af5c2283dd3e033ea2b352cd3312a39e84.

I think it'd help if Footer deserialization checked if lengths look sensible.

**Comment by petr-tik** [comment]
Hey, this one is on me, as I made a PR with is_compatible. 

Can you please provide a copy of the index for me to repro? Feel free to send it in a private message on gitter

**Comment by fulmicoton** [comment]
The bug is here. It should be fairly easy to reproduce by modifying a valid index.

https://github.com/tantivy-search/tantivy/blob/431c187a604f9c33e6d92a4a7f58cd588a27cb8d/src/directory/footer.rs#L152

https://github.com/tantivy-search/tantivy/blob/master/src/directory/footer.rs#L80

We probably want to sanitize these size. If they are higher than the length of the file or 16KB, return an error.
