### ISSUE TITLE
Does tantivy support Phonetic Matching or any plan to support it

### ISSUE THREAD

**Issue by serak** [quickwit-oss/tantivy#770]
i Apache lucene even does not have this feature but. if tantivy supported this of the box it would be optimal and would be beyond what the lucene could do
in a bank we use lucene to find duplicate customer by name and fuzzy query does not help here 
https://lucene.apache.org/solr/guide/6_6/phonetic-matching.html

**Comment by fulmicoton** [comment]
>  Apache lucene even does not have this feature but.

That is a very strange statement, if you add a link to solr's dcumentation. Solr is built on top of Lucene.

Tantivy supports implementing your own `TokenFilter`. Soundex and metaphone have rust implementations. You could just simply plug them to tantivy.

**Comment by fulmicoton** [comment]
Closing.
