### ISSUE TITLE
Making `TopCollector::limit` optional

### ISSUE THREAD

**Issue by kardeiz** [quickwit-oss/tantivy#776]
Would you be open to a PR that made `TopCollector::limit` optional? I have a use case where the expected number of hits can vary by an order of magnitude. When I use the `TopDocs` collector, I either have to wildly over-allocate, or risk clipping my results set.

I would propose making `limit` an `Option<usize>`. I don't think any of the public API would need to change: `TopDocs::with_limit` would still take a `usize`, we would just add a `TopDocs::new` and `TopDocs::with_size_hint` (to efficiently pre-allocate without dropping results).

Most of the changes would be in `collector/top_collector.rs` but there would be some minimal changes to `collector/top_score_collector.rs` and `collector/custom_score_top_collector.rs`. A few tests may require minimal changes, and I would be happy to add some tests for the new limitless variant.

I could implement a custom collector locally to do this, but it would require duplicating much of the code in `collector/top_collector.rs`.

**Comment by fulmicoton** [comment]
Just to be clear, you have a use case in which you need the sorted list of all of your matchings documents? Can you describe it?

> I could implement a custom collector locally to do this, but it would require duplicating much of the code in collector/top_collector.rs.

Not exactly. If this is really your use case, you'd be better off just appending all docs to a Vec during collection, and sorting all of the docs on the `harvest` call.

**Comment by kardeiz** [comment]
Hi @fulmicoton, thanks for the response.

I'm working on a `sled`-based datastore, where `tantivy` provides the query interface to the store. I would like to provide a method like `store.search("my query")` that would return all documents scored (without having to specify a `limit`). I'm using a `u64` fast field to store the id/key for the `sled` db.

**Comment by fulmicoton** [comment]
Is scoring a thing in your use case?

If not I recommend using the iterator like interface. 
It looks like something like this

```rust
let weight = query.weight(searcher, false)?;
let segment_readers = searcher.segment_readers();
for reader in segment_readers {
    let mut scorer = weight.scorer(segment_readers)?;
    while scorer.advance() {
        let doc = scorer.doc();
        //... do what you need
    }
}
```

**Comment by kardeiz** [comment]
Yes, I would like to include the score&mdash;

**Comment by fulmicoton** [comment]
The use case is still unclear to me and I don't think such a collector has its place in tantivy.

Please implement your own collector in your project. Let us know if you need help for that.

**Comment by fulmicoton** [comment]
Closing.

If you are confident  your use case is legit, please reopen.. but take the time to effectively explain what you are trying to do. Right now I am suspicious this thread is a good example of the "XY" problem.

**Comment by kardeiz** [comment]
I guess I'm still confused why *not* to have an unlimited scored docs collector. It seems analogous to Rust `std` offering a `Vec` type rather than just variously sized `Array` types. And Lucene for example does not require specifying a `limit` in retrieving docs.

I'm happy to leave this issue closed, though, and thank you so much for your time, the iterator-like example, and `tantivy` itself!

It was also pretty trivial to implement my own `Collector`, which I am pasting below in case anyone has a similar need. Thanks!

```rust
#[derive(Default)]
pub struct ScoredDocs { size_hint: Option<usize> }

pub struct ScoredDocsSegmentCollector {
    segment_local_id: tantivy::SegmentLocalId,
    buffer: Vec<(tantivy::Score, tantivy::DocAddress)>,
}

impl tantivy::collector::Collector for ScoredDocs {
    type Fruit = Vec<(tantivy::Score, tantivy::DocAddress)>;
    type Child = ScoredDocsSegmentCollector;

    fn for_segment(
        &self, 
        segment_local_id: tantivy::SegmentLocalId, 
        _: &tantivy::SegmentReader
    ) -> tantivy::Result<Self::Child> {
        Ok(ScoredDocsSegmentCollector { 
            segment_local_id, 
            buffer: self.size_hint.map(|size| Vec::with_capacity(size) ).unwrap_or_else(Vec::new)
        })
    }

    fn requires_scoring(&self) -> bool {
        true
    }

    fn merge_fruits(
        &self, 
        segment_fruits: Vec<Self::Fruit>
    ) -> tantivy::Result<Self::Fruit> {
        let mut out = segment_fruits.into_iter().flat_map(|x| x).collect::<Vec<_>>();
        out.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(b.1.cmp(&a.1)));
        Ok(out)
    }
}

impl tantivy::collector::SegmentCollector for ScoredDocsSegmentCollector {
    type Fruit = Vec<(tantivy::Score, tantivy::DocAddress)>;
    
    fn collect(&mut self, doc: tantivy::DocId, score: tantivy::Score) {
        self.buffer.push((score, tantivy::DocAddress(self.segment_local_id, doc)));
    }
    
    fn harvest(self) -> Self::Fruit {
        self.buffer
    }
}
```

**Comment by fulmicoton** [comment]
@kardeiz I don't think analogy are useful to judge whether something is useful in library or not.
I just need confirmation that there are users who need this.

Once again your reply does not help and screams [XY problem](http://xyproblem.info/).
You are not explaining what you are actually trying to do and why, you just repeat you need a top collector with no limit...

At this point, I cannot judge whether this is really what you need it or not.


>  And Lucene for example does not require specifying a limit in retrieving docs.

I am not sure what that means. The API of the TopScoreDocsCollector does not seem to allow as far as I can see.
https://lucene.apache.org/core/7_3_1/core/org/apache/lucene/search/TopScoreDocCollector.html
