### ISSUE TITLE
Reloading without creating searchers creates leaky behaviour.

### ISSUE THREAD

**Issue by poljar** [quickwit-oss/tantivy#777]
**Describe the bug**
Triggering a reload causes Tantivy to call the `publish_new_generation()` [method](https://github.com/tantivy-search/tantivy/blob/master/src/reader/pool.rs#L70). This method populates the queue of the pool with N new `GenerationItem` objects.

The queue of the `Pool` gets only cleared of stale `GenerationItem` objects once a `Searcher` is requested. This leads to increased memory consumption if a `Reader` is alive, a `Writer` is actively committing, the `OnCommit` `ReloadPolicy` is used, and no `Searcher` is currently being requested.

While we could get rid of this leaky behavior by not keeping a reader alive, manually reloading or periodically fetching a `Searcher`, it would be nice if we could drop the unneeded `GenerationItem` objects immediately when new ones are created. If this isn't possible keep only the last N generations in the queue.

**Which version of tantivy are you using?**
Tantivy 0.11.3 as well as master at abef5c4e741c0dbb8afce9b07e95ca54d78e3afa behave in this way.

**To Reproduce**

The behavior can be reproduced with the following code snippet.
```rust
use tantivy::{Index, IndexReader, IndexWriter};
use tantivy::schema::{Schema, TEXT, STORED, Field};
use tantivy::doc;
use std::thread::sleep;
use std::time::Duration;

fn build_index() -> (Index, IndexReader, IndexWriter, Field) {
    let mut schema_builder = Schema::builder();
    let title = schema_builder.add_text_field("title", TEXT | STORED);
    let schema = schema_builder.build();
    let index = Index::create_in_ram(schema);
    let writer = index.writer(50_000_000).unwrap();
    let reader = index.reader().unwrap();

    (index, reader, writer, title)
}

fn main() {
    let (_, reader, mut writer, title) = build_index();

    for i in 0..300 {
        if i % 100 == 0 {
            writer.commit().unwrap();
        }
        writer.add_document(doc!(title => format!("Test {}", i)));
    }

    for _ in 0..100 {
        reader.reload().unwrap();
        sleep(Duration::from_millis(100));
    }

    reader.searcher();

    for _ in 0..100 {
        reader.reload().unwrap();
        sleep(Duration::from_millis(100));
    }
}
```

Running the snippet through `heaptrack` gives us the following picture.
![image](https://user-images.githubusercontent.com/552026/74343389-458f7f80-4dab-11ea-88ed-9e35bc46012e.png)

After roughly one second we are done adding documents and enter our first reload loop. We can see that memory consumption steadily rises without adding any new documents. 10 seconds later we create a searcher the memory consumption rapidly drops. We enter our second reload loop and memory consumption again steadily rises.

**Comment by fulmicoton** [comment]
@poljar Can you check if #779 solves your problem?

**Comment by poljar** [comment]
Can confirm, the reproducer snippet now seems to be happy, Riot as well.

New heaptrack picture for proof is bellow.
![image](https://user-images.githubusercontent.com/552026/74608921-89ed8900-50e5-11ea-949e-a4357bd8aa51.png)

**Comment by poljar** [comment]
Any chance of seeing a bugfix release including the fix?

**Comment by fulmicoton** [comment]
Yes! I'll publish a hotfix or make a new release this week

**Comment by poljar** [comment]
Thanks for the quick fix and the coming release.
