### ISSUE TITLE
Add a filtering collector

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#794]
In some case it can be handy to have a filtering collector. 
The filtering collector should wrap another collector, and a predicate (typically over fast fields)
Document are collected into the wrapped collector iff the document's  match the predicate.

API should be discussed in the comments below.

**Comment by shikhar** [comment]
Dupe of https://github.com/quickwit-oss/tantivy/issues/892

https://docs.rs/tantivy/0.16.1/tantivy/collector/struct.FilterCollector.html
