### ISSUE TITLE
Make `Field::from_field_id` a `const fn`

### ISSUE THREAD

**Issue by fisherdarling** [quickwit-oss/tantivy#821]
**Is your feature request related to a problem? Please describe.**
It would be nice to create constants for the Fields that I need. For example, `const TITLE: Field = Field::from_field_id(0);`

**Describe the solution you'd like**
I believe simply putting `const` in front of `Field::from_field_id` would do the trick.

I'd be happy to make the change in a PR, just want to make sure y'all would be fine with it. We could also make `field_id` `const` as well.

**Comment by fulmicoton** [comment]
Feel free to send a PR.
