### ISSUE TITLE
Better support for bytes field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#832]
See #830 for motivation.

Currently only fast bytes field are only supported, but there is a case for INDEXED bytes field (MongoDB ObjectID was mentionned on gitter for instance), and stored field.

**Comment by sgrust01** [comment]
@fulmicoton thanks for queuing this up.
Cheers,
SG.

**Comment by shikhar** [comment]
I think this is done? https://github.com/tantivy-search/tantivy/blob/c82cee66de01036c351efd4949d20bc40c6e6e41/src/schema/bytes_options.rs#L8-L10

**Comment by fulmicoton** [comment]
@shikhar  thanks for the triaging. Closing.
