### ISSUE TITLE
delete_term not removing document

### ISSUE THREAD

**Issue by rthomas** [quickwit-oss/tantivy#835]
**Describe the bug**
I had recently migrated a project to tantivy and noticed my index was not having items removed from it when using IndexWriter::delete_term - I was able to reproduce this by modifying the IndexWriter example (below). I'm unsure if I'm just using this incorrectly.

**Which version of tantivy are you using?**
0.12.0

**To Reproduce**

```
    #[test]
    fn test_tantivy() {
        use tantivy::collector::TopDocs;
        use tantivy::query::QueryParser;
        use tantivy::schema::*;
        use tantivy::{doc, Index};

        let mut schema_builder = Schema::builder();
        let title = schema_builder.add_text_field("title", TEXT | STORED);
        let schema = schema_builder.build();

        let index = Index::create_in_ram(schema.clone());

        let title_str = "The modern Promotheus";
        let query_str = "Promotheus";

        let mut index_writer = index.writer_with_num_threads(1, 50_000_000).unwrap();
        index_writer.add_document(doc!(title => title_str));
        index_writer.commit().unwrap();

        let searcher = index.reader().unwrap().searcher();
        let query_parser = QueryParser::for_index(&index, vec![title]);
        let query_promo = query_parser.parse_query(query_str).unwrap();
        let top_docs_promo = searcher
            .search(&query_promo, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo.len(), 1);

        let term = Term::from_field_text(title, title_str);
        index_writer.delete_term(term);
        index_writer.commit().unwrap();

        let query_promo2 = query_parser.parse_query(query_str).unwrap();
        let top_docs_promo2 = searcher
            .search(&query_promo2, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo2.len(), 0);
    }
```

**Comment by fulmicoton** [comment]
You reused the same searcher. You need to reload the index reader and acquire a new searcher.

A searcher 's purpose is to capture a version of the index and keep it for the extent of one or more queries.

**Comment by rthomas** [comment]
Thanks for getting back so quickly, I've modified this with a new searcher and the test is still failing.

I ran into this in an rpc handler where I was creating a new searcher for each request.

```rust
    #[test]
    fn test_tantivy() {
        use tantivy::collector::TopDocs;
        use tantivy::query::QueryParser;
        use tantivy::schema::*;
        use tantivy::{doc, Index};

        let mut schema_builder = Schema::builder();
        let title = schema_builder.add_text_field("title", TEXT | STORED);
        let schema = schema_builder.build();

        let index = Index::create_in_ram(schema.clone());

        let title_str = "The modern Promotheus";
        let query_str = "Promotheus";

        let mut index_writer = index.writer_with_num_threads(1, 50_000_000).unwrap();
        index_writer.add_document(doc!(title => title_str));
        index_writer.commit().unwrap();

        let searcher = index.reader().unwrap().searcher();
        let query_parser = QueryParser::for_index(&index, vec![title]);
        let query_promo = query_parser.parse_query(query_str).unwrap();
        let top_docs_promo = searcher
            .search(&query_promo, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo.len(), 1);

        let term = Term::from_field_text(title, title_str);
        index_writer.delete_term(term);
        index_writer.commit().unwrap();

        let searcher2 = index.reader().unwrap().searcher();
        let query_promo2 = query_parser.parse_query(query_str).unwrap();
        let top_docs_promo2 = searcher2
            .search(&query_promo2, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo2.len(), 0);
    }
```

**Comment by fulmicoton** [comment]
You also need to reload the reader.

Le sam. 30 mai 2020 à 11:55, Ryan Thomas <notifications@github.com> a
écrit :

**Comment by rthomas** [comment]
Thanks for all the help here - however reloading the reader still seems to fail for me - this is what I did:

```rust
let reader = index.reader().unwrap();
reader.reload().unwrap();
let searcher2 = reader.searcher();
```

Should the Index::reader() function provide a current reader for the given Index?

**Comment by rthomas** [comment]
Hmmm is seems like the docs suggest that I shouldn't need to call reload:

> If you set up the OnCommit ReloadPolicy (which is the default) every commit should be rapidly reflected on your IndexReader and you should not need to call reload() at all.

**Comment by fulmicoton** [comment]
@rthomas, sorry I replied a bit fast as i was on my phone. 

Here is a little bit more of detail.
Reload is not required in your case because you rebuilt a reader in the second query.
A fresh reader always points on the last version of the index.

The documentation you refer to is not helping in your case. OnCommit autoreloads the index "rapidly". Rapidly typically means within 100ms... But it is done asynchronously! You should not expect it to help you in that kind of test case. Even worse, it introduces a race condition... So rapidly means rapidly, but not synchronously.

But let's come back to the problem you are experiencing.

Delete makes it possible to delete documents including a specific term.
Here you fed the title as a term... But the title is not a term, it is an untokenized string.

You need to supply a term like it appears in the output of the tokenizer you configured.
You used the default tokenizer. It only chops your string into tokens and lowercase it so,
so deleting "promotheus" works (note the lowercasing).

I suspect this is frustrating, 
How are you supposed to make it work at this point?

Well in most case, you do NOT want to delete using a tokenized field.
You want to introduce somekind of field that you will effectively use like a primary id.

In your schema,

```
        let title = schema_builder.add_text_field("title", TEXT | STORED);
```

becomes 

```
        let idfield = schema_builder.add_text_field("myid", STRING | STORED);
```

If you want to use the title as this primary id (most likely a terrible idea),  you will have to have 
two fields called title, and replicate it in the documents you feed.

**Comment by rthomas** [comment]
Thanks for the detailed response @fulmicoton - this particular example I just lifted from the IndexWriter documentation - in my case I am dealing with file paths (and that is what I was attempting to delete by).

I was also unaware of the difference between TEXT and STRING which I think will help in my case.

When you say that using the title as a primary id is a terrible idea, why is that? Is this a performance issue, or a collision issue (or both)? For file paths would something like the inode id be a better choice than the canonical path, do you think?

**Comment by fulmicoton** [comment]
Homonyms. There are many collision for titles of books.

No need to worry too much about performnace.
For files, canonical path should be ok.

**Comment by fulmicoton** [comment]
Extra information about performance:

Right now, the key are encoded in an FST.This is more or less like a trie.
You don't pay 100 times for 100 string that share the same prefixes, so don't worry about that.

Still, tantivy could be better at handling that kind of primary key, by doing something similar to the bursting codec in lucene, and by adding bloom filter on top of segments.
It will happen in due time... In the meanwhile I think you should be ok with the performance.

**Comment by rthomas** [comment]
For my use case performance is not yet a concern.

I've made the changes in my test, fixing the query to be on the title, and the title to be type STRING and this gets the test to passing for me. Thanks very much for the help!

For posterity I'll put my working test below.

```rust
#[test]
    fn test_tantivy() {
        use tantivy::collector::TopDocs;
        use tantivy::query::QueryParser;
        use tantivy::schema::*;
        use tantivy::{doc, Index};

        let mut schema_builder = Schema::builder();
        let title = schema_builder.add_text_field("doc_id", STRING | STORED);
        let schema = schema_builder.build();

        let index = Index::create_in_ram(schema.clone());

        let title_str = "/foo/bar/baz";

        let mut index_writer = index.writer_with_num_threads(1, 50_000_000).unwrap();
        index_writer.add_document(doc!(title => title_str));
        index_writer.commit().unwrap();

        let searcher = index.reader().unwrap().searcher();
        let query_parser = QueryParser::for_index(&index, vec![title]);
        let query_promo = query_parser.parse_query(title_str).unwrap();
        let top_docs_promo = searcher
            .search(&query_promo, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo.len(), 1);

        let term = Term::from_field_text(title, title_str);
        index_writer.delete_term(term);
        index_writer.commit().unwrap();

        let reader = index.reader().unwrap();
        reader.reload().unwrap();
        let searcher2 = reader.searcher();
        let query_promo2 = query_parser.parse_query(title_str).unwrap();
        let top_docs_promo2 = searcher2
            .search(&query_promo2, &TopDocs::with_limit(1))
            .unwrap();

        assert_eq!(top_docs_promo2.len(), 0);
    }
```
