### ISSUE TITLE
How to sort more than two fields

### ISSUE THREAD

**Issue by ansjsun** [quickwit-oss/tantivy#842]
How to sort more than two fields

example

order by  age,  idcard, name .......

**Comment by fulmicoton** [comment]
Check out the example in TopDocs's custom_score

https://docs.rs/tantivy/0.12.0/tantivy/collector/struct.TopDocs.html#method.custom_score

**Comment by ansjsun** [comment]
@fulmicoton  This does not fully fulfill that requirement

I mean. Sort by Field1. If field1 is the same, sort by Field2. Also supports the natural order of strings.

I see that custom_Score can only construct a number from multiple fields for sorting. Many times this field is hard to construct. Did I get it wrong？

**Comment by fulmicoton** [comment]
@ansjun 

If I understand your question, yes you are wrong. Can you please read the example as suggested?
It precisely shows how to apply lexicographical order on a pair of fields.
