### ISSUE TITLE
Handle fuzzy search

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#85]
Handle matching with a given levenshtein distance of at most k.
k should be a function of the length of the query though.

It might be nice to contribute to the fst crate with the original implementation of levenshtein automaton.

**Comment by drusellers** [comment]
https://github.com/BurntSushi/fst/blob/master/fst-levenshtein/src/lib.rs has the fst code.

@fulmicoton would this be a collector?

**Comment by fulmicoton** [comment]
No, probably a query...

We want something that intersects the term dictionary with the levenshtein automaton like what you see in BurntSushi code.

Maybe we should just pre-compute the full docset of documents that match the fuzzy query, and then have the scorer iterate over those, I am unsure.

**Comment by rhanka** [comment]
Is this feature officially out of scope ?

**Comment by fulmicoton** [comment]
No. It is not out of scope. It will happen eventually.

If you want fuzzy search on one term, the FuzzyTermQuery does it.
The levenshtein automata stuff has been implemented, and is compatible with the fst crate.

**Comment by shikhar** [comment]
Dupe or at least related: #563
