### ISSUE TITLE
Block WAND on TermQuery

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#869]
Block WAND for disjunctions was introduced on tantivy 0.13.

Unfortunately it is not used on TermQuery at the moment.
The search benchmark shows how Lucene is outperforming PISA and tantivy on  TermQueries for this reason.

A trivial implementation is available in https://github.com/tantivy-search/tantivy/compare/master...blockwand-for-termquery
It has not been properly tested, and maybe there are nicer implementations.

**Comment by ppodolsky** [comment]
@fulmicoton BTW, probably you've seen it, but it could be interesting for others: https://issues.apache.org/jira/browse/LUCENE-8197
This is how pagerank weightening can be incorporated into a scoring function without losing the ability to optimize top-K querying.

**Comment by fulmicoton** [comment]
@ppodolsky No I actually missed it. I used to look at the lucene ML but I stopped, so thanks for sharing!

**Comment by fulmicoton** [comment]
Fixed by @fmassot in https://github.com/quickwit-oss/tantivy/commit/04627546731dbc5c057b769cb06ce044bf33399d
