### ISSUE TITLE
Updates and Deletes

### ISSUE THREAD

**Issue by sgrust01** [quickwit-oss/tantivy#871]
Hi - Not sure if there is an nice way to update and/or delete historical data from an index.

Cheers,
SG

**Comment by ppodolsky** [comment]
This line is taken out of context, but I hope it's rather obvious what to do or what to google:)
```
index_writer.delete_term(Term::from_field_i64(id_field, doc_id));
```

**Comment by sgrust01** [comment]
@ppodolsky Thanks for your reply. I did take a look prior to posting, but was too lazy to experiment :smile_cat: 

```
Delete all documents containing a given term.

Delete operation only affects documents that were added in previous commits, and documents that were added previously in the same commit.

Like adds, the deletion itself will be visible only after calling commit().
```

BTW - I was looking for selective delete across multiple commits. 

Cheers,
:beer:

**Comment by fulmicoton** [comment]
@ppodolsky  suggestion is correct.

It is across multiple commits. Your delete apply to all documents that were added before you send the delete...

**Comment by sgrust01** [comment]
@fulmicoton @ppodolsky Thanks.. will take a look.
