### ISSUE TITLE
TopDocs support order_by for Date fast fields

### ISSUE THREAD

**Issue by erichutchins** [quickwit-oss/tantivy#882]
**Is your feature request related to a problem? Please describe.**
I have a schema that defines a date fast field and I’d like to use it with TopDocs to order the results chronologically.

```rust
let mut schema_builder = Schema::builder();
let date_field = schema_builder.add_date_field(“date”, INDEXED | FAST);

...

let top_docs_by_rating = TopDocs::with_limit(10).order_by_u64_field(date_field);
```

This will error and say “Field requested date_field is not a i64/u64 fast field.”

**Describe the solution you'd like**
If possible, could a `order_by_fast_field` generalize any fast field into a u64 representation?

**[Optional] describe alternatives you've considered**
`u64_lenient` looks like a possible solution, but it’s private to the crate

**Comment by fulmicoton** [comment]
That requires a little bit more work (just cleaning and rustdoc really) but a solution is on the way.
