### ISSUE TITLE
Design of the Tantivy .store/Document/Schema

### ISSUE THREAD

**Issue by ppodolsky** [quickwit-oss/tantivy#887]
@fulmicoton it's me again :-)
I've dived into `schema` module sources and would like to ask you about binary layout of stored documents.

Tantivy binary serialization of documents is between schemaful and schemaless approach, I have no idea how to name it:) Also, I have no clues why this semi-approach has been selected. 

Documents are serialized together with their field numbers and field types. It allowes to deserialize document into array of field_values without using schema. But, as far as I see, any futher action with a deserialized document requires its schema. If you want to jsonize document, you need the schema to extract field names. If you want to reindex document, you need the schema to get indexing options. May it worth to totally remove type hints from serialized document, leave varint-encoded data and take types from the schema too?

I bet I missed something and types in binary layout are needed for something. Could you enlighten me here?

I have this question because I'm experimenting with switching this binary format with either Protobuf or Capnproto format and measuring performance/storage consumption for point access and full-scan traversing of `store` files. Both formats require schema at parsing time and isolating of Tantivy document serialization code can not be easily done with the current design of Tantivy `store`/`schema`.

**Comment by fulmicoton** [comment]
Sorry for the late answer. I am in holiday at the moment. Let me answer you
next Monday!

Le ven. 25 sept. 2020 à 05:25, Pasha Podolsky <notifications@github.com> a
écrit :

**Comment by ppodolsky** [comment]
Sure! Wish you a good holiday:)

**Comment by fulmicoton** [comment]
```
Documents are serialized together with their field numbers and field types. It allowes to deserialize document into array of field_values without using schema. But, as far as I see, any futher action with a deserialized document requires its schema. If you want to jsonize document, you need the schema to extract field names. If you want to reindex document, you need the schema to get indexing options. May it worth to totally remove type hints from serialized document, leave varint-encoded data and take types from the schema too?

I bet I missed something and types in binary layout are needed for something. Could you enlighten me here?
```

The encoded thing is a straightforward serialization of the `Document` object. The extra information that needs to be embedded (the field types) is fairly tiny and I don't think it is too impactful on the resulting store size.
The benefit is that it is simple.

```
I have this question because I'm experimenting with switching this binary format with either Protobuf or Capnproto format and measuring performance/storage consumption for point access and full-scan traversing of store files. Both formats require schema at parsing time and isolating of Tantivy document serialization code can not be easily done with the current design of Tantivy store/schema.
```

I am not sure of your point here : I am not familiar of a lib (or a strong benefit) to encode protobuf with a dynamic schema.
Well I guess we could use variable int encoding for a bunch of stuff. It might help but it will come at the cost of some complexity.

I don't think the serialization of the document store matters much...
Apart from backward/forward compatibility with schema change. This is something that requires quite a bit of reflexion. Protobuf and Avro are possible source of inspiration.

**Comment by ppodolsky** [comment]
> The encoded thing is a straightforward serialization of the Document object. The extra information that needs to be embedded (the field types) is fairly tiny and I don't think it is too impactful on the resulting store size.

I got you point. Nevertheless, I faced conditions where it could be impactful to a small extent. I'm trying to store all fields I would like to return to user in Tantivy. I'm doing it to avoid the extra hop to the full-featured database. There are about 15-20 fields half of which are just numbers and text fields could be rather small. So these extra bytes take their cents on disk.

> I am not sure of your point here : I am not familiar of a lib (or a strong benefit) to encode protobuf with a dynamic schema.

Yeah, this is an issue I bumped into after digging and rewriting some code in Tantivy:) I've taken https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-codegen-pure/src/bin/parse-and-typecheck.rs and have derived Schema object from a provided .proto file. Then I've coded Document serialization into protobuf, it could be done without schema, it is similar to your varlen encoding. But decoding protobuf back cannot be done without schema. It is because encoding loses data about type (protobuf precise type stored as narrower wire type).

Probably I should just end my coding venture and look at the real beneftis I've got with this protobuf encoding. May be this 1-3% of saved disk space is of no worth.

**Comment by fulmicoton** [comment]
So right now the field is serialized using 4 bytes. 
The values are also encoded without variable int encoding. We can also fix that easily.
Removing that 1 tag byte used to identify the field type using the schema, is however, overkill I believe.

(and doing magic to rely on protobuf specialization is too)

**Comment by fulmicoton** [comment]
Opened a different issue to drive the effort. You can pick it if you want. #903 @ppodolsky
