### ISSUE TITLE
Investigate strange performance regression in postings iteration with Rust 1.17 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#89]
(Check branch `issue/test_block_iter` to reproduce)

`postings::tests::bench_segment_postings_nosum_normal`

is way faster is block below is uncommented  or when running Rust 1.15 for some reason.

**Comment by joehillen** [comment]
Could it be a case of this? https://medium.com/@robertgrosse/how-copying-an-int-made-my-code-11-times-faster-f76c66312e0f

**Comment by fulmicoton** [comment]
Unfortunately no.

**Comment by fulmicoton** [comment]
in master without the uncommented code. `test postings::tests::bench_segment_postings_nosum_normal  ... bench:     400,801 ns/iter (+/- 557,480)`

**Comment by fulmicoton** [comment]
in test/iter without the commented code
`test postings::tests::bench_segment_postings_nosum_normal  ... bench:     425,842 ns/iter (+/- 87,008)`

with the uncommented code.
`test postings::tests::bench_segment_postings_nosum_blockwise ... bench:      39,711 ns/iter (+/- 19,789)`

`test postings::tests::bench_segment_postings_nosum_normal    ... bench:     137,221 ns/iter (+/- 55,665)`

**Comment by lnicola** [comment]
I can't reproduce this:

```
test postings::tests::bench_segment_postings_nosum_normal  ... bench:     596,581 ns/iter (+/- 4,660)
```

after uncommenting `bench_segment_postings_sum_blockwise`:

```
test postings::tests::bench_segment_postings_nosum_normal  ... bench:     597,031 ns/iter (+/- 36,018)
test postings::tests::bench_segment_postings_sum_blockwise ... bench:     197,016 ns/iter (+/- 8,110)
```

**Comment by lnicola** [comment]
I see it on Windows. Inlining makes it a bit hard to tell what's up.

**Comment by lnicola** [comment]
Marking `SegmentPostingsBlockCursor::advance` as `#[inline(never)]` fixes this.

The compiler probably notices that the function is called only once, so it decides to inline it. I'm not sure why this has such a large effect, but that function doesn't strike me as a good inlining candidate.
