### ISSUE TITLE
Add a FilterCollector wrapper

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#892]
A `FilterCollector` could take a field (configured as a fast field), a predicate function over that field value, and another collector.

The filtercollector would then push docs to the underlying collector iff the fastvalue associated with the field matches the predicate.

**Comment by fulmicoton** [comment]
@barrotsteindev would you be interested in picking this ticket?

**Comment by barrotsteindev** [comment]
@fulmicoton Yes please

**Comment by barrotsteindev** [comment]
Should we close this issue? @fulmicoton
