### ISSUE TITLE
Possible index corruption under load

### ISSUE THREAD

**Issue by ppodolsky** [quickwit-oss/tantivy#897]
**Describe the bug**
It will be a bad bug report as I do not know how to reproduce it in a robust way.
I have a Tantivy installation storing fresh documents from web. Old documents (older than 2 month) are deleted every hour. There are about 30 million documents at every moment in the index and about 50-60k are deleted and inserted every hour. There are no updates, just removing old ones and inserting new ones.

It's been working for weeks or even months. There were several hard server halts during the period.

Now I've started to notice that some of queries return back documents which do not contain any word from query at all. More accurately, search returns irrelevant documents even for 1 word query.

It looks that posting lists or fast fields might be corrupted.

At the first time I thought it could be a problem at my side, for example document has been fully updated on the Web and I had missed this update and hadn't reflected it in the index. But the increased number of these discrepancies makes me looking for other reasons too.

My schema is following: 

```rust
    fn create_schema() -> Schema {
        let mut schema_builder = Schema::builder();
        schema_builder.add_text_field(
            "body",
            TextOptions::default().set_indexing_options(
                TextFieldIndexing::default()
                    .set_tokenizer("classic")
                    .set_index_option(IndexRecordOption::WithFreqsAndPositions),
            ),
        );
        schema_builder.add_i64_field("source_id", FAST | INDEXED | STORED);
        schema_builder.add_i64_field("id", FAST | INDEXED | STORED);
        schema_builder.add_i64_field("lang", FAST | INDEXED | STORED);
        schema_builder.add_text_field(
            "title",
            TextOptions::default().set_indexing_options(
                TextFieldIndexing::default()
                    .set_tokenizer("classic")
                    .set_index_option(IndexRecordOption::WithFreqsAndPositions),
            ),
        );
        schema_builder.add_i64_field("type", FAST | INDEXED | STORED);
        schema_builder.add_i64_field("unixtime", FAST | INDEXED | STORED);
        schema_builder.build()
    }
```

Searching routine:
```rust
async fn invoke_searcher(
        &self,
        query: &str,
        limit: usize,
        offset: usize,
        user: &User,
    ) -> Result<Vec<(i64, Score)>, Error> {
        let cloned_query = query.to_string();
        let searcher = self.get_searcher();
        let schema = self.schema.clone();
        let query_parser = self.query_parser.clone();

        ...

        let search_result = tokio::task::spawn_blocking(move || {
            let parsed_query = query_parser.parse_query(&cloned_query)?;
            let search_result = searcher.search(&parsed_query, &collector)?;
            Ok(search_result
                .iter()
                .filter_map(|el| {
                    searcher
                        .doc(el.1)
                        .map(|f| {
                            (
                                f.get_first(schema.get_field("id").unwrap())
                                    .unwrap()
                                    .i64_value(),
                                el.0,
                            )
                        })
                        .ok()
                })
                .collect::<Vec<(i64, Score)>>())
        })
        .await?;
        search_result
    }
```

MergePolicy is a default one (logarithmic). I do search by `body` field, then extract `id` field and go to upstream database with it.

I've done extra checks before filing this issue to reduce the possibility of being mistaken by myself. Chances are still exist but rather low.

I'm thinking what it can be, probably you could guide me to collect or debug the required data to understand the issue.

**Which version of tantivy are you using?**
0.13

**Comment by fulmicoton** [comment]
Thanks for reporting. It will be very difficult to investigate without the data. 
I would lean toward "not a bug" bug but it is certainly worth investigating considering the risk is definitely here.

What does the classic tokenizer does?
Can you share your code and the corrupted index (Sharing only the corrupted segment is ok too).  If it is too big, I can send you code to extract a mini index that contains only the faulty document.

**Comment by fulmicoton** [comment]
Also please make sure you do not lose the index you believe is corrupted! Ideally, copy it somewhere, gzip it, or something.

**Comment by fulmicoton** [comment]
@ppodolsky friendly ping!

**Comment by ppodolsky** [comment]
Sure, I will do as it will be ready. My bad was that I reindexed data before creating issue so I have to wait for some time to reproduce it again. I check it every day and will post here results when detect broken segment again.

**Comment by fulmicoton** [comment]
@ppodolsky I was a bit scared of that. Please really make a frozen copy of your index when you detect it. If this is confirmed as a bug, consider your index as a precious artifact :)

**Comment by ppodolsky** [comment]
I would like to close this issue until I bring a metal proofs, original search index has been overwritten. Now I know how to debug corrupted segments thanks to #969. And another reason to close is that bare index format has been refactored since the time I had faced issue. 
I will reopen it if would find anything else.

**Comment by fulmicoton** [comment]
Thank you!
