### ISSUE TITLE
[feature] remove field from document for updating

### ISSUE THREAD

**Issue by sbeckeriv** [quickwit-oss/tantivy#900]
**Is your feature request related to a problem? Please describe.**
I searched my index and found a document. I delete it from the index. I want to update a single field. If i added the field again it does not replace the field but add a new one. 

https://github.com/tantivy-search/tantivy/blob/main/examples/deleting_updating_documents.rs  this example helps but i dont have the original data source. How do I update a single field?

**Describe the solution you'd like**

I would like to see an update_fields({field =>field_value,..}) to handle the logic but a remove_field(field) that removes it from field_values https://docs.rs/tantivy/0.13.2/src/tantivy/schema/document.rs.html#119 like add pushes it on.

**[Optional] describe alternatives you've considered**

**Comment by fulmicoton** [comment]
This is a common problem, but it won't be addressed within tantivy (just like it is not addressed in Lucene).

For reference, in Elasticsearch this is simply done by having a stored field called _source that contains the raw content of the original document.

**Comment by sbeckeriv** [comment]
Hello @fulmicoton 

Thank you for your work on this project. I have yet to come up with a way to store the full original data and I will consider this moving forward. I will be looking at how elasticsearch does this. I am very new to the concepts and thank you for the pointers.

I am wondering for ergonomics (i have yet to try this) I have 
```
    let mut schema_builder = Schema::builder();
    schema_builder.add_text_field("title", TEXT | STORED);
    schema_builder.add_text_field("url", TEXT | STORED);
    schema_builder.add_text_field("content", TEXT|);
    schema_builder.add_text_field("domain", TEXT | STORED);
    schema_builder.add_text_field("_source_json", STORED);
    schema_builder.add_i64_field("pinned", STORED | INDEXED);                                                                                                                             
    schema_builder.add_date_field("last_accessed_at", STORED | INDEXED);  
```
lets say _source_json is a string of json of title,url, content, last_accessed_at. This is a toned down version of the set of data I have.

I want to update last_accessed_at. I can reparse the source json as an object
```
 let doc = schema.parse_document(&_source_json)?;
doc.add_field(pinned, original_doc.pinned) // i need to copy pinned because its not in the json blob.
```
at this time if I add the last_accessed_at field it will have two in the field_values array? Which one will be written and which one will be read? I understand I can not just clone or duplicate the original document because content is not stored. I would have to reparse the json blob update the last_accessed_at value in the json blob and then parse from the new updated json. If i had an api to remove a field's data from the field_values directly I should be able to keep the code simple without reparsing and changing the json? 

I am i wrong about the two last_access_fields and which one will be written? I am doing this for pinned now. it writes both back but only reads the first value. Is there already a concept in tantivy for what i am doing?

Once again, thank you for your time on this project and all your advice. 
Becker
