### ISSUE TITLE
Dynamic compression format

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#904]
Right now, tantivy relies on compile-time feature flags to decide which store compression format (lz4, snappy, brotli) should be used.
The store compression algorithm is serialized within VersionFooter in every file and the compatibility check ensures that a meaningful error message is emitted if a user tries to open an index using a compression scheme that is incompatible with the feature flag they used at compilation time.

Ideally, a user should be able to compile tantivy with several compression algorithm  to enable to define in the schema which compression format is used.

Some user want to keep tantivy as light as possible, or prefer to work with a "pure rust" project with no C bindings. (for instance when working with WASM)
For this reason, the compression algorithm would still be enabled or disabled at compile time.

The compression algorithm would be specified in the meta.json AND this compression should also be written in the store file.
We can keep the compression algorithm in the VersionFooter for a bit, but only for backward compatibility version.

On read, the compression algorithm will be decided by read a specific store file.
On write, the compression algorithm used will be decided by what is defined in the meta.json file.

Changing the compression algorithm of an existing index will be handled. In that case, old segment and new segment may use a different compression algorithm. On merge, the new compression algorithm should be used systematically.

Note for the implementer: An optimization exists when merging store file that do not contain any deleted docs. In that case, the store blocks just get stacked. Please make sure that this optimization is disabled if the compression scheme are different.

**Comment by fulmicoton** [comment]
@ppodolsky volunteered to work on  this ticket and already implemented the Brotli support. I cannot set him as assignee for the moment as he is not part of the tantivy-dev team yet. (Just sent the invite).

Assigned @guilload as well for discussion and code reviews.

**Comment by PSeitz** [comment]
You may consider [lz4_flex](https://github.com/PSeitz/lz4_flex), if you want a pure rust lz4 implementation. The unsafe version is not too far from the c++ version in performance.

**Comment by fulmicoton** [comment]
@PSeitz Yes I am following your recent progress on lz4_flex :).

It is actually quite important for us, as the only reason we use snappy as a default is to ensure that vanilla tantivy is "pure rust".
I need to make perf test on our side to ensure that the regression is as small on our special use case (we compress very small blocks) and I think we can operate the switch.

**Comment by PSeitz** [comment]
@fulmicoton if there is a special use case, you could give me some example data which I would add to the benchmarks to track the performance. Currently the benchmarks are not super extensive.
What I plan next, and could provide some performance boost in compression in your use case, is to clear and reuse hashtables which are used to find duplicates. I did not yet benchmark this, but it could give an edge to the c++ implementation :)

**Comment by PSeitz** [comment]
I saw that the frame format of lz4 is used. It's not documented in the API, but you can see it in the source code. It has too much overhead for 16kb blocks.
https://github.com/tantivy-search/tantivy/blob/main/src/store/compression_lz4.rs
https://github.com/10XGenomics/lz4-rs/blob/master/src/decoder.rs#L80

Switching from the frame format to the (lz4_flex) block format increased document read speed up to 2x (https://github.com/PSeitz/veloci/commit/0fe989f25ad9cddc6e55db6f72f53d55e8c56598). 
But they are also incompatible.
