### ISSUE TITLE
negative timings on a served index being built

### ISSUE THREAD

**Issue by scampi** [quickwit-oss/tantivy#907]
**Describe the bug**

While trying out `tantivy` using the CLI crate, I wanted to search for documents while the wikipedia articles were being indexed. I got a response where timings reported negative times.
Probably I shouldn't get negative values there.

```
http localhost:3000/api q==barack+obama nhits==20
HTTP/1.1 200 OK
Content-Length: 279
Content-Type: application/json
Date: Sat, 10 Oct 2020 23:11:15 GMT

{
    "hits": [],
    "num_hits": 0,
    "q": "barack+obama",
    "timings": {
        "timings": [
            {
                "depth": 0,
                "duration": -194,
                "name": "search"
            },
            {
                "depth": 0,
                "duration": -4,
                "name": "fetching docs"
            }
        ]
    }
}
```

**Which version of tantivy are you using?**

tantivy-cli: https://github.com/tantivy-search/tantivy/commit/d63cae71b19b99fb9c7dbca49daf88339fae6e7a

**To Reproduce**

Serve index as it is being indexed and search it.

**Comment by fulmicoton** [comment]
This is bug... but please report it in the tantivy-cli repository in the future. Anywya it is fixed now.
