### ISSUE TITLE
Corrupt index when using index writer in background thread

### ISSUE THREAD

**Issue by maufl** [quickwit-oss/tantivy#928]
Hi, I'm probably not yet understanding how to use tantivy correctly, hence a question, not a bug.

I'm writing a REST API with Rocket and I want to index data from the Postgres DB into a tantivy index for full text search. I'm creating the tantivy index on startup and pass it as managed state into my request handlers, which only use an index reader to query the index. This works great.

I'm also starting a new thread and pass in the index and a database connection. In this thread I'm reading all ids of the indexed documents (`index_reader.searcher().field(id_field)`, is that the best way?) and collect them into a vector. Then I'm loading all offers from the database that are not yet indexed (as determined by their ids). For each new offer I create a document and add it to the index. At the end I `commit()` and for testing purposes I dropped the index writer in the hope that this would force a flush. Then the thread sleeps for a while and the loop begins again.

The second time the loop runs I get a panic when reading the value of the first term. While debugging, I found out that the term of the id field contains only 8 bytes instead of the required 12. I get a similar error when I try to open the index with tantivy-cli afterwards (`IOError(IOError { path: None, err: Custom { kind: InvalidData, error: "Reach end of buffer while reading VInt" } })`). While writing the issue I found out that I don't have this problem in my Rocket app when I don't try to read the id fields, but it does persist when trying to read the index with tantivy-cli.

Are there any requirements for safely using tantivy in a multithreaded app? Does it need to be gracefully shut down? (I could not figure out how to do that in Rocket) Should I use the field searcher at all? (It's not exported)

**Comment by maufl** [comment]
Here the currupted index. [index.tar.gz](https://github.com/tantivy-search/tantivy/files/5519824/index.tar.gz)

**Comment by fulmicoton** [comment]
I suspect you simply index with a new version fo tantivy and are using a tantivy-cli that is compiled with an older version of tantivy. I have no problem reading your index with tantivy-cli 0.13.2.

Can you check your tantivy-cli version, and let me known which version you are using right now? (tantivy --version)
Then upgrade to tantivy-cli 0.13.2.
If the problem persists, can you tell me precisely which query is broken?

**Comment by fulmicoton** [comment]
```
➜  tantivy-bug tantivy search -i . --query at
{"category":["Sport & Spielzeug"],"color":["mint-grün"],"description":["Et at dolorum. Sit natus voluptas. Vero quia ipsum. Corrupti qui ullam."],"gtin":["88014890"],"id":[11],"image":["https://i.picsum.photos/id/228/200/250.jpg?hmac=YYNLCIGU9NdZTXVBNdy_gTLTebzTEcSkuZ1704ZcPKA"],"name":["Salted Caramel Gummy Bears Sweet Bread"],"price":[38.19]}
{"category":["Outdoor & Industrie"],"color":["azur"],"description":["Veritatis aspernatur in. Qui harum quisquam. Id at reprehenderit. Alias iure est. Rerum est dicta."],"gtin":["34162088"],"id":[15],"image":["https://i.picsum.photos/id/1002/200/250.jpg?hmac=-EVK5Ah3L0dGLscUu-y9rwma0lX81N6HxPlo4yMZ8qU"],"name":["Cheesecake Cinnamon Frozen Yogurt"],"price":[70.04]}
{"category":["Industrie"],"color":["lila"],"description":["Consequuntur ut praesentium. Doloribus eum totam. At id neque. Omnis aut voluptas."],"gtin":["46679819"],"id":[8],"image":["https://i.picsum.photos/id/515/200/250.jpg?hmac=q1exlE5ffR_tOfz-31Hj1H02E2ujUKIaBbK3b1bdYxU"],"name":["Red Velvet Cheesecake Bites Key Lime Pie"],"price":[64.4]}
```

**Comment by maufl** [comment]
You're right, somehow I still had an older version of tantivy cli installed.

Now the only remaining problem is that the FieldSearcher crashes. As it is not documented, I'm probably not supposed to use it anyway. Is there a recommended way of retrieving all values of a field? Or another strategy of keeping track what needs to be indexed and what is already indexed?

I'll close this ticket, as my assumption that I was corrupting the index is not correct.

**Comment by fulmicoton** [comment]
> Now the only remaining problem is that the FieldSearcher crashes. As it is not documented, I'm probably not supposed to use it anyway. 

It should not crash.
Can you make sure you index and search using the same version of tantivy, and then open another ticket with the crash information?

**Comment by maufl** [comment]
Yes, I'll try to build a minimal example and then reopen a ticket. Might take until next week though.
