### ISSUE TITLE
Panic when reading fields with field searcher

### ISSUE THREAD

**Issue by maufl** [quickwit-oss/tantivy#933]
Tantivy panics when iterating a field with `IndexReader.searcher().field(...)`. I build a schema and an index and then, in a loop, index new documents and read all values of a field with a `FieldSearcher`. I expect to get the list of all values of the field, instead it panics with:
```
thread 'main' panicked at 'assertion failed: 8 <= buf.len()', /home/maufl/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.3.4/src/lib.rs:2007:9
```

I'm using Tantivy 0.13.2.

Attached a minimal example to reproduce this problem, invoke with `cargo run -- <empty_dir_for_index>`.

[main.txt](https://github.com/tantivy-search/tantivy/files/5533414/main.txt)

**Comment by fulmicoton** [comment]
Thank you for the great bug report! I think this is an actual bug. I was able to reproduce. I'll come up with a fix rapidly.

**Comment by maufl** [comment]
Thank **you** for the great library :) I come up with new ideas everyday where I could use it. It's so cool to be able to add an incredibly fast full text search to anything!

**Comment by fulmicoton** [comment]
I confirm there is a bug in `TermMerger::next()`. 

As a temporary workaround you can use the following snippet in place of your inner loop to iterate over the 
terms of the TermMerger.

```
    while terms.advance() {
        let mut term_bytes  = [0u8; 8];
        term_bytes.copy_from_slice(terms.key());
        let id_value = u64::from_be_bytes(term_bytes);
        indexed_ids.push(id_value as i32);
    }
```

**Comment by evanxg852000** [comment]
@fulmicoton  has this been taken?

**Comment by fulmicoton** [comment]
I think we just need to remove the .next() method.
