### ISSUE TITLE
Remove the searcher pool

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy#935]
The only mutable part of the searcher is the little cache in the StoreReader.

We could make the mutable cache safe and remove the extra complexity associated to the multiple Searchers and their pool.

**Comment by waywardmonkeys** [comment]
@fulmicoton Is this still something desired?

**Comment by PSeitz** [comment]
That's already solved: https://github.com/quickwit-oss/tantivy/pull/1411
