### ISSUE TITLE
Removing dynamic dispatch and allocations in tokenizer

### ISSUE THREAD

**Issue by troublescooter** [quickwit-oss/tantivy#961]
Would a pr removing the dynamic dispatch in the tokenizer be accepted? It does not seem necessary.
There's a comment indicating the API of the tokenizer trait may move to associated types, so this seems to already have been considered.

**Comment by fulmicoton** [comment]
I don't think it is possible so now I am curious :). Can you show an incomplete PR that compiles and contains your change?
