### ISSUE TITLE
Make NamedFieldDocument deserializable

### ISSUE THREAD

**Issue by mosuka** [quickwit-oss/tantivy#963]
Hi,
I'm working on a program that uses gRPC to exchange Tantivy's search results between servers in JSON format.
It would be helpful if I could deserialize the NamedFieldDocument from JSON. Can I send you a PR?

**Comment by ppodolsky** [comment]
Aren't these two functions what you are looking for?
https://github.com/tantivy-search/tantivy/blob/main/src/schema/schema.rs#L300
https://github.com/tantivy-search/tantivy/blob/main/src/schema/schema.rs#L278

**Comment by fulmicoton** [comment]
@mosuka, can you confirm that `Schema::parse_document` does not work for you?

**Comment by mosuka** [comment]
@ppodolsky @fulmicoton 
Thank you for the quick reply.
I want to deserialize directly a JSON string that serialized from a struct that wraps a NamedFieldDocument like this using serde_json.

https://github.com/mosuka/phalanx/blob/master/phalanx-index/src/index/search_result.rs

```
{
  "count": 2,
  "docs": [
    {
      "fields": {
        "category": [
          "/category/search/server",
          "/language/rust"
        ],
        "description": [
          "Phalanx is a cloud-based index writer and searcher written in Rust."
        ],
        "id": [
          "1"
        ],
        "name": [
          "Phalanx"
        ],
        "popularity": [
          0
        ],
        "publish_date": [
          "2020-06-21T01:41:00+00:00"
        ],
        "url": [
          "https://github.com/mosuka/phalanx"
        ]
      },
      "score": 1.7752718
    },
    {
      "fields": {
        "category": [
          "/category/search/library",
          "/language/rust"
        ],
        "description": [
          "Tantivy is a full-text search engine library inspired by Apache Lucene and written in Rust."
        ],
        "id": [
          "8"
        ],
        "name": [
          "Tantivy"
        ],
        "popularity": [
          3142
        ],
        "publish_date": [
          "2019-12-19T01:07:00+00:00"
        ],
        "url": [
          "https://github.com/tantivy-search/tantivy"
        ]
      },
      "score": 1.57912
    }
  ],
  "facet": {
    "category": {
      "/language/rust": 2,
      "/category/search/server": 1,
      "/category/search/library": 1
    }
  }
}
```

It is possible to deserialize such a struct directly from serde_json by just adding Deserialize to the NamedFieldDocument, how about that? Can you give me some advice?

**Comment by fulmicoton** [comment]
Yes the solution to your problem is very simple. I just wanted to make sure this discussion was not an occurrence of the XY problem.

**Comment by fulmicoton** [comment]
Let's  add the Deserialize trait.

**Comment by mosuka** [comment]
Thanks!
