### ISSUE TITLE
Can tantivy::collector::facet_collector::FacetCounts be exported to pub?

### ISSUE THREAD

**Issue by slckl** [quickwit-oss/tantivy#978]
Sorry, if I'm missing something obvious here, but...

As a user of Tantivy as a library and using a `FacetCollector`, I'd like to write a function that takes in [`FacetCounts`](https://github.com/tantivy-search/tantivy/blob/86d92a72e7483d04020f035c59e2fea2c04df5ec/src/collector/facet_collector.rs#L384) and process the results into something more fit for my application. Alas, the `FacetCounts` struct is not exported as public for users of Tantivy. 
I can only process the facet counts inside the same function I obtain the results in. This approach works, but limits how I as a user can organize my code around `FacetCounts`.

Are there any downsides to this type being exported publicly? Maybe in the same `tantivy::collector` module?

**Comment by slckl** [comment]
An alternative could be to use `MultiCollector`, which returns `MultiFruit`, from which you can extract results for each collector using a handle. Alas, `MultiFruit` is also not exported publicly, so there goes that plan.

Going with processing in-place for now, but I still think it would be nice, if I could write a separate function for each collector separately.

**Comment by fulmicoton** [comment]
I am ok to make it pub. Can you for tantivy, make it pub on your fork, depend on your fork to check that it addresses your problem, and send a PR? 

I'd hate to make it pub, and then realize it is not sufficient to fix your problem.
