### ISSUE TITLE
Configurable custom dictionary

### ISSUE THREAD

**Issue by carmel** [quickwit-oss/tantivy#989]
Custom dictionary in [jieba](https://github.com/fxsjy/jieba/blob/master/test/test_userdict.py).

Although it can be achieved through code just like [cang-jie](https://github.com/DCjanus/cang-jie), but I am a layman to the rust language.

Also, is there a golang client here?

**Comment by fulmicoton** [comment]
Because you talk about jieba, I will assume you mean tokenizer's dictionary.
Tantivy is a search engine library that makes it possible to plug your own tokenizer.

Your question is probably for the tantivy-jieba project. Not this one.

There are no golang bindings that i know of.

**Comment by carmel** [comment]
You are right, i understand wrong, thank you.
